### ISSUE TITLE
Work on improving the working of the chatbot and make it more interactive

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Suchitra-Sahoo/AgriLearnNetwork#10]
Implement various interactive features such as clickable buttons for quick navigation or response options can make the interaction more user-friendly and engaging, adding sound effects and feedback mechanism where users can rate the helpfulness of the chatbot's responses or provide suggestions.

**Comment by kairveeehh** [comment]
@Suchitra-Sahoo hi , as my expertise in LLMs and frontend I would like to take this issue and would request you to assign it to me.

**Comment by Suchitra-Sahoo** [comment]
@kairveeehh assigned. You may start working on it.

**Comment by kairveeehh** [comment]
@Suchitra-Sahoo after a good research over automated chatbots , I would request the permission to shift to a different platform than botpress which can allow us to add more and better features . 
waiting for you reply

**Comment by Suchitra-Sahoo** [comment]
@kairveeehh update me about your progress.

**Comment by kairveeehh** [comment]
> @kairveeehh update me about your progress.

@Suchitra-Sahoo  I am working on it and had asked you regarding this already , please see my previous comment done yesterday , I have changed integrations locally to make the chatbot more functionable and interactive but will need your permission as it is taken through a internet website via scripts

**Comment by palayushi293** [comment]
want to work on this and improve its working 
Waiting for your response
