### ISSUE TITLE
Google auth using firebase

### ISSUE THREAD

**Issue by naisargi17** [Suchitra-Sahoo/AgriLearnNetwork#1000]
### Describe the feature

Firebase make it easy to add google auth to websites

### Add ScreenShots

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/111778403/0b0cec67-bf6e-4ae8-a492-d8a9c3e65c73

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aradhyajha** [comment]
@Suchitra-Sahoo mam.. i want to work on that issue can you please assign this issue to me i will solve this issue as soon as possible from me

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned
