### ISSUE TITLE
Adding new social account at the end

### ISSUE THREAD

**Issue by NamanJain795** [Suchitra-Sahoo/AgriLearnNetwork#1003]
### Describe the feature

Hey Naman Jain a GSSOC 24 contributor
I think that telegram channel should also be added at the end of the webpage at the follow us on our socials so that the people are able to join the telegram group for information related to agriculture.

please assign me this task and mark this issue with gssoc level 1 issue.
looking forward for you reply

### Add ScreenShots

![agri](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/141808883/7206b72c-5e72-458e-9e72-b7a681322203)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aradhyajha** [comment]
@Suchitra-Sahoo... mam i want to work on that issue can you please assign this task to me

**Comment by Suchitra-Sahoo** [comment]
This is not required
