### ISSUE TITLE
Feat:In FAQ quations add hover effets when some one hover on quation text of that convert in green color 

### ISSUE THREAD

**Issue by zalabhavy** [Suchitra-Sahoo/AgriLearnNetwork#1009]
### Describe the feature

When someone hover on quation i want to add effects on text that text converts green color.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/d9232eec-93be-4715-8e74-5ecc2496b715)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Suchitra-Sahoo Please assign me this task !

**Comment by Suchitra-Sahoo** [comment]
This is not required.
