### ISSUE TITLE
Feat: Adding proper comments

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Suchitra-Sahoo/AgriLearnNetwork#1014]
### Objective
I want to add the proper comments so that user can understand the functionality of the code easily and can work on  the website with full his/her potential .

### Conclusion
It will surely help to get more knowledge about the text stack , and the code working .

### Add ScreenShots

![Screenshot 2024-06-27 220514](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/118350936/dcf88bb2-fa89-4e44-8c1b-b7b1ddcaff9e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
But this issue will not help you to get a level tag.
