### ISSUE TITLE
Feat:  Adding BEM Naming convention to the classes 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Suchitra-Sahoo/AgriLearnNetwork#1015]
### Describe the feature

I saw that the classes naming convention is not proper so i want to apply the naming convention 

### Use Case
It will allow the users to deeply understand the classes and html elements used for so that they make no mistakes on doing their work 

### Add ScreenShots

![Screenshot 2024-06-27 220731](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/118350936/3bc75848-6305-44e7-b183-00da5a2e5b08)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Not required right now.
