### ISSUE TITLE
Feat:Make website SEO friendly

### ISSUE THREAD

**Issue by chaanakyaaM** [Suchitra-Sahoo/AgriLearnNetwork#1017]
### Describe the feature

I would like to add the appropriate meta tags including descriptions , properties, keywords, etc, which makes the website more SEO friendly.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Not required right now.
