### ISSUE TITLE
Feat: Change font

### ISSUE THREAD

**Issue by chaanakyaaM** [Suchitra-Sahoo/AgriLearnNetwork#1018]
### Describe the feature

The website font can be improved by changing the font to poppins like font and more.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/131477601/f9f7dfff-efb7-4981-a12f-2a01bf4c1779)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
To which font?

**Comment by chaanakyaaM** [comment]
poppins
