### ISSUE TITLE
Feat: Decrease height of the nav bar

### ISSUE THREAD

**Issue by chaanakyaaM** [Suchitra-Sahoo/AgriLearnNetwork#1019]
### Describe the feature

The nav bar is covering a lot of space and does not look good, so i would like to decrease the height of the nav bar.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/131477601/06afdb23-3726-4ef1-b393-670e7d981357)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Navbar issue is already assigned.

**Comment by chaanakyaaM** [comment]
could you kindly view my other issues.
