### ISSUE TITLE
AI chatbot is not working

### ISSUE THREAD

**Issue by Anshika040** [Suchitra-Sahoo/AgriLearnNetwork#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Chatbot should work as desired to interact with user

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sailza** [comment]
HI please assign this issue to me . As i already user chat bot in my project so i can easily solve this problem

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
