### ISSUE TITLE
Feat: add blur effect

### ISSUE THREAD

**Issue by chaanakyaaM** [Suchitra-Sahoo/AgriLearnNetwork#1020]
### Describe the feature

The website would look more attractive if main card on the home page has blur effect.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/131477601/d31a1bd9-17da-4ff2-9e23-1b6bf0fe448c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required right now.
