### ISSUE TITLE
BUG: Navbar is not proper

### ISSUE THREAD

**Issue by Archiesachin** [Suchitra-Sahoo/AgriLearnNetwork#1023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login button in navbar is getting overlapped by the dark mode switch. 
![Screenshot (1130)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/103347688/40252219-6d6d-4227-ad5f-faf81a94fb9f)

In the Buy products page, when we scroll down the navbar items change their position resulting in misalignment

![Screenshot (1131)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/103347688/84052ad3-e623-4479-947a-a65d74e937ab)

 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Resolve this issue for all the pages where it exists.

**Comment by Archiesachin** [comment]
Okay
