### ISSUE TITLE
[BUG]: Responsive Issue

### ISSUE THREAD

**Issue by sivaprasath2004** [Suchitra-Sahoo/AgriLearnNetwork#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- In this Page not proper Resposive mode.
- The container outside the screen will overflow.
![Screenshot from 2024-05-11 13-12-03](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/121082414/3d1bf904-89c2-4436-92ac-fd4472a32283)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by soham-hecker** [comment]
@Suchitra-Sahoo I'm up for fixing the CSS and making the website resposive. Please assign me this task under GSSOC'24

**Comment by sivaprasath2004** [comment]
@Suchitra-Sahoo please add `level` label Your missing the label assigned for me.

**Comment by sivaprasath2004** [comment]
@Suchitra-Sahoo please add `level` label Your missing the label assigned for me.

**Comment by Suchitra-Sahoo** [comment]
Level label are added once you make a PR and it is merged.
