### ISSUE TITLE
Feat: change the theme of FAQ section 

### ISSUE THREAD

**Issue by CoderGirl2844** [Suchitra-Sahoo/AgriLearnNetwork#1036]
### Describe the feature

the FAQ section doesnt match the theme in light mode ... its background color needs to be changed.

### Add ScreenShots

![Screenshot 2024-06-30 215202](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/155231566/6ce38ecb-c129-41f8-ba54-252b4c264720)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It is already assigned.
