### ISSUE TITLE
Image gallery New Animation 

### ISSUE THREAD

**Issue by gupta-ritik** [Suchitra-Sahoo/AgriLearnNetwork#104]
### Describe the feature

I want to made image gallery with 3D effect in this with fully responsive 

### Add ScreenShots

![IMG_20240511_133530](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/127002992/80a58626-c3d6-4d94-b191-026fcecd6c57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@gupta-ritik assigned. You may start working on it.

**Comment by gupta-ritik** [comment]
Thanks Suchitra-Sahoo/AgriLearnNetwork

**Comment by gupta-ritik** [comment]
@Suchitra-Sahoo can you label the assign work

**Comment by gupta-ritik** [comment]
Please label the assign work.

**Comment by Suchitra-Sahoo** [comment]
@gupta-ritik as i also mentioned in your PR that i reverted your pull request as your image gallery is not working properly. As you have not raised any PR to correct it so I can't add a level label. Level label is added only when your PR is merged.

**Comment by gupta-ritik** [comment]
I am unable to push the code of your main branch .
It's showing no permission is granted 😞😞

**Comment by Suchitra-Sahoo** [comment]
You can't directly push the code to main branch. Create another branch after forking the repo, do your changes and raise a PR.

**Comment by gupta-ritik** [comment]
Ok, will do that.
