### ISSUE TITLE
BUG: TESTIMONIALS Next/Previous button not in center and home page scrollbar hover color is changed to red.

### ISSUE THREAD

**Issue by zalabhavy** [Suchitra-Sahoo/AgriLearnNetwork#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I will fix hover on scrollbar color light green that used in other page.

Also make Next/Previous  button in center of card.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/b3a2fc39-77e8-406b-8af7-920f44e69876)

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/36b9d3d0-f2c8-400f-9961-73949690bd2d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Suchitra-Sahoo Please assign me this task !

**Comment by Suchitra-Sahoo** [comment]
Try to make the testimonials section responsive.

**Comment by zalabhavy** [comment]
@Suchitra-Sahoo Sure 👍
