### ISSUE TITLE
Feat:Add actual colour hovering effect on footer .

### ISSUE THREAD

**Issue by ANKeshri** [Suchitra-Sahoo/AgriLearnNetwork#1047]
### Describe the feature

when we hover over the social icon it will be in its actuqal colour . 

### Add ScreenShots

before  : 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159682348/686a5a05-e1af-46bf-9b43-f5f9b7ba5d7a

Want to make it like this : 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159682348/9797d785-963d-4dcd-8f07-681583879dd0

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@Suchitra-Sahoo please assign me tis issue i want to work on it , I am sure user will like this featur .

**Comment by AbhiSharmaNIT** [comment]
I would like to work on this project , please assign it to me.

**Comment by ANKeshri** [comment]
@Suchitra-Sahoo mam please let me know if you want .
