### ISSUE TITLE
BUG: distorted and unaligned ui

### ISSUE THREAD

**Issue by Tanishashrivas** [Suchitra-Sahoo/AgriLearnNetwork#1051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar contents are not spaced properly, overlapping with other stuff. Also the hover effect of login button leads to overlapping,
![Screenshot 2024-07-02 123939](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114223066/7f74a323-8c66-4291-92b4-671e232dfb41)
![Screenshot 2024-07-02 123955](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114223066/86465770-0cee-4477-8fd1-c8cf311aae1d)
i want to fix this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AbhiSharmaNIT** [comment]
I would like to work on this project please assign it to me.

**Comment by Suchitra-Sahoo** [comment]
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123376847/4c591d2a-4475-41da-b298-ee3392139f76)
But i have just checked and it is working fine.
