### ISSUE TITLE
BUG: "buy products" and "login" overflowing from the navbar container when screen size is reduced

### ISSUE THREAD

**Issue by Maana-Ajmera** [Suchitra-Sahoo/AgriLearnNetwork#1055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

"Buy products" and "login" overflowing from the navbar container when screen size is reduced.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162733812/b579f8ac-f3c7-4163-93b2-790d4e06bb4e

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@Suchitra-Sahoo I want to work on this issue , please assign it to me .

**Comment by Suchitra-Sahoo** [comment]
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123376847/a18877b1-afb7-4d88-baa2-c421151d86ef)
I have just checked and it is working fine.
