### ISSUE TITLE
Feat: Redirecting to the top of the page when click on logo in the footer section

### ISSUE THREAD

**Issue by katarianikita2003** [Suchitra-Sahoo/AgriLearnNetwork#1063]
### Describe the feature

When user click on logo in the footer section, user will be redirected to the top of the page

### Add ScreenShots

![Screenshot 2024-07-03 233840](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/158465309/94f60b0a-c910-4d6d-b83a-a50636a21355)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required.
