### ISSUE TITLE
BUG: I want to improve the style for sign in page field

### ISSUE THREAD

**Issue by Maheshwari-Love** [Suchitra-Sahoo/AgriLearnNetwork#1074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142833275/0d1ce0a6-e4d6-4a1b-a86d-a1f87f78fdef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@Suchitra-Sahoo please assign me this task ...

**Comment by Suchitra-Sahoo** [comment]
What kind of sign up page you want to design?

**Comment by Maheshwari-Love** [comment]
> What kind of sign up page you want to design?

want to maintain the style as in current page fields of email and password are not aligned also the eye button icon is large as compare to field size
