### ISSUE TITLE
BUG: Price not increasing on adding a item more than once in the Cart

### ISSUE THREAD

**Issue by Maheshwari-Love** [Suchitra-Sahoo/AgriLearnNetwork#1075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142833275/a944d102-8cf5-415a-8f27-26b35e595d06)

the product is of 3500, but when i added 4 times the same product, the total amount should be updated to 4*3500 but it only takes the price of one item

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@Suchitra-Sahoo please assign me this task ...

**Comment by Suchitra-Sahoo** [comment]
I think its working fine. Can you attach a video or image to understand the issue

**Comment by Maheshwari-Love** [comment]
> I think its working fine. Can you attach a video or image to understand the issue


https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142833275/85543c78-d7f4-412b-8ac0-6f0c8adf032f

**Comment by Maheshwari-Love** [comment]
@Suchitra-Sahoo please refer above clip for this issue

**Comment by Maheshwari-Love** [comment]
@Suchitra-Sahoo can you assign me this I have solved this issue...
