### ISSUE TITLE
BUG:Agri bot is not working

### ISSUE THREAD

**Issue by nagamukesh** [Suchitra-Sahoo/AgriLearnNetwork#108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

for some reason i don't know, agribot feature is not working
I can try to fix it
please assign this issue to me under gssoc 2024

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@nagamukesh assigned. You may start working on it.

**Comment by nagamukesh** [comment]
I made the chatbot work and I made a pull request #132 
thanks for giving this opportunity
