### ISSUE TITLE
🌟 Feature: Add a Scroll "Progress Indicator Bar" 

### ISSUE THREAD

**Issue by Tejashri-Taral** [Suchitra-Sahoo/AgriLearnNetwork#1086]
### Describe the feature

Hey @Suchitra-Sahoo ,
I want to add a "Scroll Down Progress Bar"

This feature adds a scroll down progress bar to the website, which visually indicates the user's progress as they scroll down the page.
The progress bar enhances user experience by providing a clear visual cue of their location on the page and how much content remains to be viewed.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/160386036/cdc1f8a9-a557-4532-ad01-1cda3aaa1561)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by IshaanXCoder** [comment]
Hey @Suchitra-Sahoo , pls assign this issue to me, I'll surely do the desired task :)
