### ISSUE TITLE
Feat: update the favicon for the website

### ISSUE THREAD

**Issue by Singh-Divyansh** [Suchitra-Sahoo/AgriLearnNetwork#109]
### Describe the feature

there is no any favicon for the website currently

### Add ScreenShots

![Screenshot 2024-05-11 140905](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114223769/671cc49d-feab-4842-8cb0-ef54230fd914)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
