### ISSUE TITLE
Create a sign up page for the website 

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Suchitra-Sahoo/AgriLearnNetwork#11]
Add a sign up page which pops when the user opens the website for taking some basic information of the user. You can add your own creativity in its design.

**Comment by Jithendranath8** [comment]
I want to do this task of adding a sign-up page . i have experiences on this issue, because  i have done few of them .  I kindly request to assign this issue to me

**Comment by vaishnavip27** [comment]
Hey @Suchitra-Sahoo , I would like to work on this issue. I look forward to work on it. Looking forward for the approval

**Comment by dhruv389** [comment]
Hi @Suchitra-Sahoo ,

Could you assign me this issue??
I'll create the sign-up page as per the issue description. Expect a pop-up sign-up form with a touch of creativity in design. Any specific requirements you'd like me to consider?.

Thanks,

**Comment by kairveeehh** [comment]
hello @Suchitra-Sahoo I would like to contribute to this issue by making a signup page for the website , please assign this issue to me

**Comment by MattipaPoojitha** [comment]
Hi @Suchitra-Sahoo I would like to contribute for this issue of creating a sign up page with unique design I already have experience in website development using html and css so, I can make it in a most effective and unique way.Looking forward for your approval.
Thank you 😊!!

**Comment by Suchitra-Sahoo** [comment]
> Hi @Suchitra-Sahoo I would like to contribute for this issue of creating a sign up page with unique design I already have experience in website development using html and css so, I can make it in a most effective and unique way.Looking forward for your approval. Thank you 😊!!

@MattipaPoojitha assigned. You may start working on it.

**Comment by anushkapal28** [comment]
I'm eager to contribute by adding a sign-up page that pops up upon website opening, collecting basic user information. I'm excited to infuse creativity into designing a user-friendly and engaging sign-up experience. Could you please assign this task to me?

**Comment by anushkapal28** [comment]
I'm eager to contribute by adding a sign-up page to collect basic user information. I'm excited to infuse creativity into designing an engaging and user-friendly sign-up experience. Could you please assign this task to me?

**Comment by Shyambarua** [comment]
Assign this issue to me 
As a full stack Developer i can write optimized code and responsive and i can integrate with backend also.

**Comment by somaakash** [comment]
> Hi @Suchitra-Sahoo I would like to contribute for this issue of creating a sign up page with unique design I already have experience in website development using html and css so, I can make it in a most effective and unique way.Looking forward for your approval. Thank you 😊!!


I will try to imrovise the the sign up page.

**Comment by Yuvika-14** [comment]
Hey @Suchitra-Sahoo . I would like to contribute in this since I am very good in designing and will design the best sign up page. Please assign me this issue. Waiting for your reply

**Comment by Aryan-joh** [comment]
Hey @Suchitra-Sahoo i would like to work on this please assign this to me as i am fronted developer ...

**Comment by Suchitra-Sahoo** [comment]
@MattipaPoojitha update me about your progress.

**Comment by MattipaPoojitha** [comment]
@Suchitra-Sahoo  I will submit it by tomorrow

**Comment by aditijain704** [comment]
hello @Suchitra-Sahoo i have good skills in frontend development.I can make this page very well.So you can assign me this issue.

**Comment by MattipaPoojitha** [comment]
@Suchitra-Sahoo  hey i tried to push my pull request but i am getting access denied can u sort it out so that i can add my pr.

I am getting this error

<img width="683" alt="image" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/93569593/8930cdd9-54d2-4133-b201-7d127ff22925">

**Comment by bhaumik0307** [comment]
Hey, I want towork on this

**Comment by Suchitra-Sahoo** [comment]
The issue is being closed now.
