### ISSUE TITLE
BUG: Functionality of Login SignUp

### ISSUE THREAD

**Issue by Kiran-pande-30** [Suchitra-Sahoo/AgriLearnNetwork#1109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Login-signup is not properly functional

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Explain your issue

**Comment by Kiran-pande-30** [comment]
Hello @Suchitra-Sahoo After Successfully Sign-in, User should be directed to home page, the navbar should also be open for profile section.
