### ISSUE TITLE
Feat: Add a scroll down process bar

### ISSUE THREAD

**Issue by chaanakyaaM** [Suchitra-Sahoo/AgriLearnNetwork#1112]
### Describe the feature

Description: I would like to add a website progress indicator bar
Uses: it helps users to show how far the website has been scrolled.
Benefits: improves the overall website's UI and make it look professional.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/131477601/97771e4a-0f7b-4bee-b3bc-0e6e0a42d19d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
it is already assigned
