### ISSUE TITLE
Feat: Want to enhance hover effect of social icons on left side

### ISSUE THREAD

**Issue by Maana-Ajmera** [Suchitra-Sahoo/AgriLearnNetwork#1115]
### Describe the feature

I want to enhance the hover effect of social icons present on left hand side.

### Add ScreenShots

Before :

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162733812/1ecf197f-e980-450d-a176-10160d04a5cc

I want to add it like this ...I feel it would look more good

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162733812/df6bde81-0e87-4783-b3fd-a85aacec270f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@Suchitra-Sahoo please assign this issue to me

**Comment by Suchitra-Sahoo** [comment]
This is not required right now.
