### ISSUE TITLE
Feat: Adding a blog regarding government policies for farming in blog section

### ISSUE THREAD

**Issue by mittal246** [Suchitra-Sahoo/AgriLearnNetwork#113]
### Describe the feature

@Suchitra-Sahoo I am thinking of adding a new feature titled above. It will help the users to get knowledge about all the government policies, programs and subsidies regarding farming. We can also add some interviews with successful farmers, highlighting their journey, challenges they've overcome, innovative practices they've implemented, and lessons learned.

**Comment by mittal246** [comment]
@Suchitra-Sahoo Kindly assign this to me under gssoc'24 label .

**Comment by Suchitra-Sahoo** [comment]
Someone is already assigned for adding blogs.
