### ISSUE TITLE
[Feat] Add live falling leaves effect on Home page 

### ISSUE THREAD

**Issue by Trevisx07** [Suchitra-Sahoo/AgriLearnNetwork#1130]
### What's wrong with the existing documentation

Adding the leaf effect in the home page will look good and attractive.I am attaching screenshot of the page after changes in it.

Screenshot After changes:
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/171925392/ed68c983-a897-40e9-a5e8-c1008ac852ff)

### Add ScreenShots

![Uploading image.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Trevisx07** [comment]
@Suchitra-Sahoo Please Assign me this task.
Thank You.

**Comment by Suchitra-Sahoo** [comment]
This is not required right  now.
