### ISSUE TITLE
Feat: Animation and UI to FAQ page

### ISSUE THREAD

**Issue by TBorundia** [Suchitra-Sahoo/AgriLearnNetwork#1134]
### Describe the feature

To improve UI so that it matches theme of website.
Give animation and smooth transition to the questions and its answers.
Making the page responsive for all screens.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/168854094/75a9d12b-c312-4141-a61d-cbfbb906fa6d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TBorundia** [comment]
@Suchitra-Sahoo Mam,
Please assign this issue to me under GSSoC'24.
Thank You!

**Comment by Suchitra-Sahoo** [comment]
What kind of animation?

**Comment by TBorundia** [comment]
@Suchitra-Sahoo ,
Adding transition and hovering effect in appearing of questions and its answer.
As of now its look so simple.
