### ISSUE TITLE
BUG: Login and dark mode button over lapping

### ISSUE THREAD

**Issue by TBorundia** [Suchitra-Sahoo/AgriLearnNetwork#1136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Login button and dark mode button is overlapping in header of the every page.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/168854094/8acb06e9-4801-4b1c-a9f0-93245e1bb7a4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned
