### ISSUE TITLE
Feat: Add a progress bar on the AgroBlogs page similar to home page.

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#1138]
### Describe the feature

Add a progress bar above the navbar on the AgroBlogs page similar to home page.
This will progress as the page scrolls up or down.

### Add ScreenShots

![Screenshot (679)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143121854/9cd29b62-76de-46e5-9fcc-23fbbd29d50f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meetarora10** [comment]
@Suchitra-Sahoo this issue is still there , kindly assign it to me.

**Comment by Suchitra-Sahoo** [comment]
add it to all the pages

**Comment by meetarora10** [comment]
@Suchitra-Sahoo okay 👍👍
