### ISSUE TITLE
BUG: Hamburger icon and AgroProducts heading is not visible in small screens on the Buy Products page.

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hamburger icon and AgroProducts heading is not visible in small screens on the Buy Products and hence is not responsive.
![Screenshot (686)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143121854/ce120783-7987-492c-bd52-d70c8274fdc8)
Please assign this task to me and I can make the changes to fix this issue and make the page completely responsive .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
But it is visible.
