### ISSUE TITLE
BUG: header section 

### ISSUE THREAD

**Issue by Sandeepkumargond** [Suchitra-Sahoo/AgriLearnNetwork#1146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when we click on dark button the dot is not goes to right 

<img width="982" alt="Screenshot 2024-07-11 214509" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/157467932/afc443df-85a6-4d4b-a9d0-4ca65b3cbe47">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sandeepkumargond** [comment]
@Suchitra-Sahoo pls assign this task

**Comment by Suchitra-Sahoo** [comment]
But i just checked and it is working fine.

**Comment by Sandeepkumargond** [comment]
But in my pc it is not working fine
