### ISSUE TITLE
BUG: Navbar logo Navigate

### ISSUE THREAD

**Issue by AnshRehan04** [Suchitra-Sahoo/AgriLearnNetwork#1147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we are at any nav link Like when we are at blog tab and when we click logo it should redirect to the homepage which add a nice feature to the website.
Please assign me this task under GSSoC'24.
Thank you 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned.
