### ISSUE TITLE
Feat:Want to Allow user to filter Items like Blog/technique

### ISSUE THREAD

**Issue by nishant0708** [Suchitra-Sahoo/AgriLearnNetwork#1149]
### Describe the feature

Want to Allow user to filter Items like Blog/technique

### Add ScreenShots

![image](https://github.com/user-attachments/assets/dab97040-91f2-47ea-8aad-5c8cf1e378cb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
But this feature is already present.
