### ISSUE TITLE
Feat: Add Government Schemes Section

### ISSUE THREAD

**Issue by SCR01** [Suchitra-Sahoo/AgriLearnNetwork#1157]
### Describe the feature

Objective: Provide farmers with easy access to information about various government schemes, subsidies, and support programs related to agriculture.

### Add ScreenShots

![Screenshot 2024-07-13 111423](https://github.com/user-attachments/assets/1a665238-6031-4cdd-88b4-93497bce80a8)

Steps:

1.  Add New Section in the Navigation Bar:

- Label: "Govt Schemes"
- Position: Between "Resource Library" and "FAQs" for better visibility.

2. Create a Dedicated Section for Government Schemes:

Header: "Government Schemes for Farmers"

Content:
Introduction: Brief overview of the importance and benefits of government schemes for farmers.
Categorized Schemes: Divide the schemes into categories such as subsidies, insurance, loans, training programs, etc.
Details: For each scheme, provide the following details:

1. Scheme Name
2. Description
3. Eligibility Criteria
4. Application Process
5. Important Dates
6. Contact Information

Links to Official Websites: Provide direct links to official government pages for each scheme.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required right now.
