### ISSUE TITLE
BUG: No transition on scroll on the navbar of  FAQ page like the other pages .

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#1161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no transition on scroll of the navbar on the FAQ page like the other pages .
Assign this task to me and I can add the same transition on scroll of this navbar similar to the other pages .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vaishnavi-jais** [comment]
It looks like our FAQ page’s navbar is missing out on a little scroll magic—unlike the smooth transitions we have on other pages, it’s currently staying static and missing the flair.

I’m excited to step in and sprinkle some of that transition charm onto the FAQ page’s navbar, ensuring it scrolls with the same seamless effect as the rest of our site. Could you please assign me this task for GSoC '24? I’m ready to synchronize the transitions and make our FAQ page as fluid and polished as the others!

Thanks for considering my request!
