### ISSUE TITLE
Feat:ADDING SLIDESHOW IN BACKGROUND FOR FAQ AND BUY PAGE

### ISSUE THREAD

**Issue by Nih1tGupta** [Suchitra-Sahoo/AgriLearnNetwork#1163]
### Describe the feature

![image](https://github.com/user-attachments/assets/2e5ede5c-f719-4417-9b79-5c548a659cd9)
![image](https://github.com/user-attachments/assets/a3521a31-a9f4-4da5-ada7-7c2f0b9abd5c)

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Content should be clearly visible.
