### ISSUE TITLE
BUG: Minor UI errors on login page

### ISSUE THREAD

**Issue by justmirr** [Suchitra-Sahoo/AgriLearnNetwork#1165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The login page has some minor issues that reduce the visual appeal of the page, like the show-password icon isn't aligned with the input box; on clicking the icon it changes the size of the box; the FAQ icon doesn't have spacing; and the sign in and sign up containers have UI error on the bottom.

![agrilearn](https://github.com/user-attachments/assets/1f1410da-8fbc-49fe-8d1e-9708e104679b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vaishnavi-jais** [comment]
It looks like our login page has a few quirks that are dimming its visual charm! From the misaligned show-password icon to the size-shifting input box, and the crowded FAQ icon to the UI hiccups at the bottom of the sign-in and sign-up containers—our login page deserves a makeover!

I’m excited to tackle these issues and polish up the page to make it not only functional but visually delightful. Could you please assign me this task for GSoC '24? I’m ready to fine-tune these elements and elevate our login page to a whole new level of elegance!

Thanks for your consideration!
