### ISSUE TITLE
Feat: Structuring the Codebase

### ISSUE THREAD

**Issue by Kiran-pande-30** [Suchitra-Sahoo/AgriLearnNetwork#1172]
### Describe the feature

Currently, our codebase is not at all structured, we need to maintain a structure for frontend, components, and all CSS files in one place, images are also distributed in multiple files in the codebase.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ce075215-5e68-479c-8a30-5e133cda07ba)

issues with only this part of the code
1. images in both components and images folder.
2. Many files have not been named correctly. 
3. As we will also integrate the backend a particular file structure to be followed will be helpful

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kiran-pande-30** [comment]
@Suchitra-Sahoo please assign me this issue

**Comment by Suchitra-Sahoo** [comment]
It will be done later on as currently active changes are going on in the project. You can contribute in some other section also.

**Comment by Kiran-pande-30** [comment]
Sure @Suchitra-Sahoo if not under GSSOC, I would love to make that contribution you can tag me whenever the repo is less crowded
