### ISSUE TITLE
Feat: Add ₹ in place of Rupee in Buy Products page and Make Payment page .

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#1177]
### Describe the feature

I want to add ₹ in place of Rupee with the products price on Buy Products page and also in place of $ on Make Payment page .
Kindly assign this issue to me .

### Add ScreenShots

![Screenshot (732)](https://github.com/user-attachments/assets/4d670582-807e-4c44-a207-3113d210f647)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meetarora10** [comment]
![Screenshot (734)](https://github.com/user-attachments/assets/f36402d1-8f73-49ba-bc2c-bc8f3c571faf)

**Comment by nikhilnishadoo7** [comment]
I'd like to work on this, please assign this to me
