### ISSUE TITLE
Feat: Adding Hover to the Home button on nav Bar

### ISSUE THREAD

**Issue by shmbhvi101** [Suchitra-Sahoo/AgriLearnNetwork#118]
### Describe the feature

we can add a green hover on the home button on the nav bar. Please let me finish this easy task as it will contribute to my  gssoc'24 journey.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/156112383/a4f53013-8123-4999-9245-5967ad1783a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shmbhvi101** [comment]
hi please assign this issue to me as i'll quickly finish it and it'll be helpful for my gssoc'24 journey

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
