### ISSUE TITLE
Add hover effects

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Suchitra-Sahoo/AgriLearnNetwork#12]
Add hover effects to interactive elements such as buttons, links, and cards to provide visual feedback and make them more interactive and engaging.

**Comment by Mohit5Upadhyay** [comment]
I want to work and contribute under GSSoC'24 . Please assign the task of adding hover effect to various buttons , cards and so on , so that UI became more interactive and engaging. Please assign it to me .

**Comment by rishyym0927** [comment]
I'd like to handle the task of "Adding hover effects to interactive elements such as buttons, links, and cards to provide visual feedback and enhance interactivity." I'm confident I can implement visually appealing hover effects to improve user engagement.

**Comment by CharanAdithya6505** [comment]
Please assign this issue to me, i have made the local setup, i think i can resolve this issues

**Comment by vaishnavip27** [comment]
Hey @Suchitra-Sahoo I would like to work on this issue as a designer and a frontend developer. Please assign me this issue

**Comment by TechSenseiX** [comment]
Hii, 
Could you assign this issue to me. I have relevant skills to solve this issue.I'm eager to get started and make a meaningful contribution to the project.

**Comment by kairveeehh** [comment]
hi @Suchitra-Sahoo  with my efficiency in tailwind , css and animation effects I would like to work on this issue and improve and add various hover effects , please assign this issue to me

**Comment by Suchitra-Sahoo** [comment]
> Please assign this issue to me, i have made the local setup, i think i can resolve this issues

@CharanAdithya6505 assigned. You may start working on it.

**Comment by anushkapal28** [comment]
I'm interested in tackling the task of "Adding hover effects to interactive elements" to enhance user engagement. I'm confident I can implement visually appealing hover effects on buttons, links, and cards. Could you please assign this task to me?

**Comment by Shyambarua** [comment]
Assign this issue to me 
As a full stack Developer i can write optimized code and responsive and i can integrate with backend also.

**Comment by Dev-AyushTrivedi** [comment]
I am interested in working on this issue. Could you please assign it to me? I am participating in GirlScript Summer of Code (GSSoC) 2024 and would love to contribute to this project. I have experience in creating websites and i have strong command on designing.

**Comment by DARSHANITRIPATHI** [comment]
please assign this task to me as i am experienced in development

**Comment by CharanAdithya6505** [comment]
Thank you

**Comment by Mohammed-790** [comment]
Please assign this issue to me I will give my best😊

**Comment by LakshmanRam** [comment]
I can fix this issue, kindly assign it to me
Need to fix Contact Page >Send Message Button (Hover Effect).
It displays hover Effect with out Curse points to Button.

![Screenshot 2024-05-10 111823](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/89759292/e17f5f81-f675-4208-9571-4f82a83810f2)

**Comment by sahithinandikula** [comment]
@Suchitra-Sahoo looking forward to work on this .i will make the changes as mentioned

**Comment by debasmi** [comment]
hi Ma'am i would like to work on this issue by adding shadows to enhance the hovering effect such that it igves a better 3d effect

**Comment by SalehaTabassum** [comment]
Hi please assign this issue to me.i will add hover effects and make it look attractive

**Comment by Suchitra-Sahoo** [comment]
@CharanAdithya6505 update me about your progress.
