### ISSUE TITLE
BUG: Old twitter logo on the left of T&C and Privacy Policy page .

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#1200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Twitter logo on the left is still the old one on T&C and Privacy Policy pages .
I can change this to the new one on both the pages . Kindly assign this task to me .
![Screenshot (753)](https://github.com/user-attachments/assets/736b2775-6176-4356-89af-0d88a50c3311)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nikhilnishadoo7** [comment]
I would like to work on this project. please assign it to me.

**Comment by nikhilnishadoo7** [comment]
![image](https://github.com/user-attachments/assets/0c595b67-ac38-4874-848f-1f93ba38bacb)

already resolved

**Comment by meetarora10** [comment]
@nikhilnishadoo7 check T&C and Privacy page brother.
