### ISSUE TITLE
BUG: Nothing happens on click of the toggle mode button on T&C and privacy policy page .

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#1201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

No action takes place on click of the toggle mode button on the T&C and privacy policy page . 
Assign this to me and I can add functionality of this button in both these pages similar to other pages .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Implement on all the page where toggle option is present but dark and light mode changes are not implemented.

**Comment by meetarora10** [comment]
Okay @Suchitra-Sahoo
