### ISSUE TITLE
Adding dark mode to T&C page

### ISSUE THREAD

**Issue by Hemav009** [Suchitra-Sahoo/AgriLearnNetwork#1204]
### Describe the feature

Adding dark mode to T&C page 
and alignment of  toggle button in navbar

### Add ScreenShots

![image](https://github.com/user-attachments/assets/6a5e16c2-feb5-42e3-887a-f89a3bf42483)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
T&C page is already assigned so can you apply dark and light mode changes on other page where toggle option is present but changes for dark and light mode are not present like blog page.

**Comment by Hemav009** [comment]
@Suchitra-Sahoo  okay
