### ISSUE TITLE
UI  improvement  of buy products 

### ISSUE THREAD

**Issue by Hemav009** [Suchitra-Sahoo/AgriLearnNetwork#1205]
### Describe the feature

UI  improvement 
would like to create cards in more clearer way and  cart also

### Add ScreenShots

![image](https://github.com/user-attachments/assets/d9adfdbc-7b6a-4f87-8586-425308247599)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@Suchitra-Sahoo can you assign me this task
