### ISSUE TITLE
BUG: Fix login hover effect

### ISSUE THREAD

**Issue by chaanakyaaM** [Suchitra-Sahoo/AgriLearnNetwork#1207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When ever the login button is hovered , it is getting expanded and getting underneath the dark mode button, and also the text is shifting instantly from the 'Login' to 'Register'.
I would like to fix this bug

![image](https://github.com/user-attachments/assets/0f840510-5a03-4ade-a326-969086679f2a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It is already assigned.
