### ISSUE TITLE
Contributors not visible in readme.

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Suchitra-Sahoo/AgriLearnNetwork#121]
All the contributors are not visible in the readme section. Looking for someone who can resolve this issue.

**Comment by nisargaa20** [comment]
Can I work on this issue under #gssoc24 

and kindly let me know if contributors should be added automatically when PR has been merged ?

**Comment by Suchitra-Sahoo** [comment]
> Can I work on this issue under #gssoc24
> 
> and kindly let me know if contributors should be added automatically when PR has been merged ?

Yes it should happen automatically.

**Comment by nisargaa20** [comment]
@Suchitra-Sahoo gssoc label is considered as contribution or gssoc'24 label ( just a doubt)

**Comment by hasmithagunda123** [comment]
I wanna work on it assign me

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!
