### ISSUE TITLE
BUG:Adding an alert when user click on Send Message

### ISSUE THREAD

**Issue by pandey079** [Suchitra-Sahoo/AgriLearnNetwork#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are some issues like  when we click on "Send Message" :

1. Either form get refreshed or move to the top.
2. The form not getting reset, i.e., the content fill in the form remains as it is..
3.  The form does not give any alert to the user, if the form is filled or not.

Kindly assign it to me under GSSOC'24 .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dark-S8uL** [comment]
@Suchitra-Sahoo I'd like to contribute to this project by adding an alert when user click on send message. Assigning this task to me would be fantastic.
