### ISSUE TITLE
Feat: footer of sign in page

### ISSUE THREAD

**Issue by dhairyagothi** [Suchitra-Sahoo/AgriLearnNetwork#1228]
### Describe the feature

footer is not same as other page

### Add ScreenShots
![image](https://github.com/user-attachments/assets/ff176289-5ff6-423b-80d1-3247638270dd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
![image](https://github.com/user-attachments/assets/0d9f4550-d210-4133-97c0-e70cf4050bf6)
try to remove this gap too

**Comment by dhairyagothi** [comment]
please check pr @Suchitra-Sahoo
