### ISSUE TITLE
BUG: The website is not reponsive 

### ISSUE THREAD

**Issue by sujal1256** [Suchitra-Sahoo/AgriLearnNetwork#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Suchitra-Sahoo ,
I have gone through your website and I want to work on this project.
The website is not responsive which stands as a most important thing because most of the users will be using mobile phones so it should look good on mobile as well
I can fix this frontend 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114292400/03e4af73-4223-4e01-bbec-67bb26060ae8)

And improve this menu icon as well
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114292400/6fa8ac1c-d8f1-469a-8507-3315e778376d)
Please assign this issue to me 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@sujal1256 assigned. You may start working on it.

**Comment by sujal1256** [comment]
Thank you for assigning me,
Actually there is a criterion that the task we are working on needs to be assigned with a level tag.
Please assign a level tag
Out of Level 1, 2, 3

**Comment by Maheshwari-Love** [comment]
I can make this page Responsive , can you please assign  this issue to me?
