### ISSUE TITLE
BUG: Agro BLog Button clearly not visible 

### ISSUE THREAD

**Issue by SKSADIRUDDIN** [Suchitra-Sahoo/AgriLearnNetwork#1255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Text color and te background color is not matching 
Clearly its not visible properly 
**Specially the Blog text**
<img width="480" alt="Screenshot 2024-07-23 at 16 01 29" src="https://github.com/user-attachments/assets/38dc23f7-e737-4e2a-817b-69130e7098cb">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SKSADIRUDDIN** [comment]
### My Solution

- Now , You can clearly see the Text 
- The **Foreground** and **Background** color is well matched



<img width="351" alt="Screenshot 2024-07-23 at 16 28 10" src="https://github.com/user-attachments/assets/7a884b59-9b91-423c-b9b5-66412a8cc437">

**Comment by Suchitra-Sahoo** [comment]
You need to contribute more to get a level tag
