### ISSUE TITLE
Feat: Enhancement in Contributor page.

### ISSUE THREAD

**Issue by zalabhavy** [Suchitra-Sahoo/AgriLearnNetwork#1259]
### Describe the feature

I will make very attractive Contributor page with use of cards.

This method is takes more time to load contributors and not so attractive.

We can use 5 cards in one raw in full screen.

![image](https://github.com/user-attachments/assets/c06e2738-cc34-410f-84d6-df38fa52aca3)

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Work on the contributors's page navbar too so it similar to homepage.
