### ISSUE TITLE
Feat: Adding a logo or beautifying the name on top left

### ISSUE THREAD

**Issue by shmbhvi101** [Suchitra-Sahoo/AgriLearnNetwork#126]
### Describe the feature

we can add a logo along with the name of the website. 

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/156112383/c523c057-1e43-4c7a-8081-dfcce49f3ea4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shmbhvi101** [comment]
I'm great at logo designing and making the overall appearance pleasing to view. i have a strong grasp in html, css, js and react. Please assign this issue to me as it'll help me in my GSSoc'24 journey!

**Comment by TejaswiKandunuri** [comment]
I will be happy to contribute to this issue "Adding a logo or beautifying the name on top left" under GSSoc'24 , could you please assign this task to me

**Comment by Akshatakapare** [comment]
I want to add a customized logo on the top left to make this more appealing and attractive, please assign this task to me. I am contributing under GSSoC'24
