### ISSUE TITLE
BUG: AgroProducts heading and cart icon are not visible on mobile view on buy products page .

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#1260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

AgroProducts heading and cart icon are not visible on mobile view .
![Screenshot (820)](https://github.com/user-attachments/assets/38dcedda-b69b-4e3e-8d0d-5aed2184e68c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It is visible.
