### ISSUE TITLE
BUG: Login button and toggle button overlap in T&C and privacy policy page .

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#1262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Login button and toggle button overlap in T&C and privacy policy page . Assign this task to me and I can fix this issue in both the pages .
![Screenshot (824)](https://github.com/user-attachments/assets/33bcef8b-60b0-4663-af5a-73fc64a15b39)
![Screenshot (825)](https://github.com/user-attachments/assets/2d3ef2e8-fc0c-47fc-a869-34f5251ed0be)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
But it is working fine.
