### ISSUE TITLE
Feat: Add scroll to top button on the contributors page .

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#1263]
### Describe the feature

A scroll to top button is missing on the contributors page .
Assign this task to me and I can fix this issue .

### Add ScreenShots

![Screenshot (826)](https://github.com/user-attachments/assets/0a1cc3ac-6a04-4de7-bff2-e9b4f3b26c55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Not required
