### ISSUE TITLE
BUG: login page bug

### ISSUE THREAD

**Issue by Hemav009** [Suchitra-Sahoo/AgriLearnNetwork#1265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Without out event entering details it's giving a confirmation message 
I would like this in both sign-in and sign-up.

![Screenshot 2024-07-24 235840](https://github.com/user-attachments/assets/3c4348e5-92f8-4237-85fa-b4b397db2d2b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sanjanadas45** [comment]
@Hemav009 please assign this to me. I want to wok on this issue.
