### ISSUE TITLE
BUG: Website Logo Not Redirecting to Home Page

### ISSUE THREAD

**Issue by jency1** [Suchitra-Sahoo/AgriLearnNetwork#1267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an issue where clicking on the logo of the website does not redirect the user to the home page. This behavior is not consistent with standard website navigation practices and may cause confusion for users trying to return to the home page quickly.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Not required
