### ISSUE TITLE
Feat: Add a translate button popup aligned with the website theme

### ISSUE THREAD

**Issue by samarsajad** [Suchitra-Sahoo/AgriLearnNetwork#1268]
### Describe the feature

add a translate button popup which changes the language of the website as per the user's need

### Add ScreenShots

![Screenshot 2024-07-22 110417](https://github.com/user-attachments/assets/6eb42141-a77b-4bd1-8516-1f90473987a9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by samarsajad** [comment]
please assign this issue to me @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
Already assigned this issue
