### ISSUE TITLE
Adding logo in the navbar

### ISSUE THREAD

**Issue by AnushkaJainFirst** [Suchitra-Sahoo/AgriLearnNetwork#127]
### Describe the feature

I have designed a logo for this website and want to add it on the top-left of the website. Plz assign this task to me

### Add ScreenShots

<img width="332" alt="agri-logo" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142675883/c3d79d9f-ae07-49a8-8e07-867504b115c1">

If you want some changes in this logo, I will make or some other design then kindly tell! @Suchitra-Sahoo 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dark-S8uL** [comment]
I'd like to contribute to this project by adding a logo in the navbar in the Header Section. This will results in enhancing the interactivity and improving the overall visuals of the button. Assigning this task to me would be fantastic.

**Comment by alamzia23** [comment]
can you please assign this issue to me? I had done the similar task in my previous internship so I think i can do it also.

**Comment by AnushkaJainFirst** [comment]
@Suchitra-Sahoo ...Plz add **level** label on this issue. 
I have done adding the logo to navbar

**Comment by drashtigit** [comment]
@Suchitra-Sahoo can you please assign me this issue .I would be happy to do that.
