### ISSUE TITLE
BUG:search product not found then display not found type card

### ISSUE THREAD

**Issue by Varsani2520** [Suchitra-Sahoo/AgriLearnNetwork#1272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo ,

if search query not match then display not found product or no available :
![image](https://github.com/user-attachments/assets/a7228e2b-d78e-4ce1-9615-f601627304ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@Suchitra-Sahoo ,please assign me i really want to work on that

**Comment by Sanjanadas45** [comment]
@Suchitra-Sahoo please assign this to me.
