### ISSUE TITLE
Feat:Want to write backend of Signup/signIn Page

### ISSUE THREAD

**Issue by nishant0708** [Suchitra-Sahoo/AgriLearnNetwork#1294]
### Describe the feature

Currently Signup and Signin page are static i want to make them work

### Add ScreenShots

![image](https://github.com/user-attachments/assets/f31421c7-d9e5-4f8f-9430-4e66b8889ffa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by nishant0708** [comment]
Hey @Suchitra-Sahoo can I work on this?

**Comment by yashi301** [comment]
Please assign this issue to me
