### ISSUE TITLE
Improve the footer section

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Suchitra-Sahoo/AgriLearnNetwork#13]
The current footer lacks functionality and visual appeal, hindering user engagement. It needs additions like useful links, social media integration, and responsive design to improve user experience.

**Comment by Mohit5Upadhyay** [comment]
I  want to contribute under GSSoC'24. Please assign this task to make footer more engaging and responsive as well with all the social media link are in the working format . please assign this to me .

**Comment by rishyym0927** [comment]
I'm interested in addressing the issue of "Enhancing the footer functionality and visual appeal." I believe that adding useful links, integrating social media, and ensuring responsive design will significantly improve user engagement and overall user experience.

I'm eager to take on this task and enhance the footer to meet our project's needs.

Looking forward to your approval.

**Comment by CharanAdithya6505** [comment]
Please assign this issue to me, i have made the local setup, i think i can resolve this issues

**Comment by dhruv389** [comment]
I hope you're doing well. I noticed the issue regarding improving the footer, and I'd like to express my interest in working on it. As an experienced  developer, I believe I can contribute significantly to enhancing the footer's functionality and aesthetics.

Please consider assigning this issue to me. I'm eager to apply my skills and ensure the footer meets the highest standards. If you have any specific requirements or guidelines for this task, feel free to share them.

**Comment by kairveeehh** [comment]
I would like to contribute to this issue under gssoc'24 , please assign this issue to me so I can work over it.

**Comment by MattipaPoojitha** [comment]
I would like to contribute for solving the issue of "Enhancing the footer functionality and visual appeal".Thus providing user's better visual and user experience.
I am eager to apply my skills and the experience I have in web development for enhancement of footer.
Eagerly waiting for your approval thank you!!

**Comment by Suchitra-Sahoo** [comment]
> I hope you're doing well. I noticed the issue regarding improving the footer, and I'd like to express my interest in working on it. As an experienced developer, I believe I can contribute significantly to enhancing the footer's functionality and aesthetics.
> 
> Please consider assigning this issue to me. I'm eager to apply my skills and ensure the footer meets the highest standards. If you have any specific requirements or guidelines for this task, feel free to share them.

@dhruv389 assigned. You may start working on it.

**Comment by anushkapal28** [comment]
Hey there,

I'm eager to contribute to GSSoC'24! I'd like to take on the task of revamping the footer to be more engaging and responsive, ensuring all social media links are functional. Could you please assign this task to me?

**Comment by Yuvika-14** [comment]
I would like to fix this issue. Please assign this issue to me
