### ISSUE TITLE
Implement of about page

### ISSUE THREAD

**Issue by praveen-all** [Suchitra-Sahoo/AgriLearnNetwork#131]
I am good at HTML,CSS and js . Please assign me to about page task

**Comment by TejaswiKandunuri** [comment]
I will be happy to contribute to this issue under GSSoc'24 , could you please assign this task to me

**Comment by manishh12** [comment]
@praveen-all I will be happy to contribute on this issue under Gssoc'24 .kindly assign this task  to me .

**Comment by alamzia23** [comment]
I will be very happy if you please assign this task to me.

**Comment by Suchitra-Sahoo** [comment]
Elaborate on what you actually want to do.

**Comment by Anou25** [comment]
Hi, I want to work on this issue, please assign it to me, I am good at ui designing as well as frontend development along with some experiences too. Firstly the about us button navigation is not proper and the font and colour can be made more appealing. Can you please assign it to me, I can make it better.

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!
