### ISSUE TITLE
BUG:404 page not found in about page 

### ISSUE THREAD

**Issue by ranjaniav1** [Suchitra-Sahoo/AgriLearnNetwork#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo ,in `contributor/about.html route `

404 not found :
![image](https://github.com/user-attachments/assets/bbbbad10-eb73-499b-b994-2af635e123c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ranjaniav1** [comment]
@Suchitra-Sahoo ,please assign me

**Comment by Ranj8521Kumar** [comment]
please assign this issue to me.
