### ISSUE TITLE
Feat:Search Bar above blog page

### ISSUE THREAD

**Issue by Ishaparte** [Suchitra-Sahoo/AgriLearnNetwork#133]
### Describe the feature

I will add search bar above bolg page so user can search various blog from it.
@Suchitra-Sahoo Plz assign me this issue.

### Add ScreenShots

![search bar](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/113294672/e473967f-24b2-4beb-ab5a-907ebc4c60f4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@Ishaparte assigned. You may start working on it.

**Comment by ujj654** [comment]
I want to work on it. Please assign this issue to me @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
What is the update?

**Comment by Ishaparte** [comment]
I have created the pr but you closed it

**Comment by Suchitra-Sahoo** [comment]
> I have created the pr but you closed it

I might have also mentioned the reason like it might be not working properly or any changes required. But you can see that you are still assigned and can raise another PR or reopen the PR with the required changes. Do inform me whether you still want to continue with the assigned issue or not,

**Comment by Ishaparte** [comment]
Yes I am working

**Comment by Suchitra-Sahoo** [comment]
Okay then update me once you are done

**Comment by Ishaparte** [comment]
I have open a pr pls check

**Comment by Ishaparte** [comment]
Created a pr #558 pls check
