### ISSUE TITLE
Hover effects for logos in the footer bar 

### ISSUE THREAD

**Issue by lodhivishalcoder28** [Suchitra-Sahoo/AgriLearnNetwork#136]
### Describe the feature

When we click to the logo in the footer, they just show social media links, but they do not hover, I can add hover effects to the logos. Please assign me this task for GSSoC'24 contribution 

### Add ScreenShots

![Screenshot 2024-05-11 214115](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145546912/0df9c153-d56f-422f-9600-34c889775299)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Already assigned to someone.
