### ISSUE TITLE
Work on the scroll bar.

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#137]
I made a sleek scroll-bar, with transparent scroll-track bar and sleek, round border scroll-thumb. 

Before
![Screenshot 2024-05-11 215200](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146661411/63b64419-68fd-4ed4-9ee6-a09538b1b436)

after
![Uploading Screenshot 2024-05-11 215149.png…]()

**Comment by Nih1tGupta** [comment]
Hi, Suchitra Sahoo .please assign this issue to me.
I think I can fix this issue by adding a more beatufil custom scroll bar
Allow me to work on it under GSSOC 2024.

**Comment by Suchitra-Sahoo** [comment]
@sau-mili I can't see your after image?

**Comment by sau-mili** [comment]
> @sau-mili I can't see your after image?

[
![Screenshot 2024-05-11 215149](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146661411/975e68da-1856-4fd1-ae68-42105c0c2491)
](URL)

is it visible now?
