### ISSUE TITLE
No Login Page Available for Daily Users

### ISSUE THREAD

**Issue by aniket8000** [Suchitra-Sahoo/AgriLearnNetwork#138]
The application currently lacks a login page, which is essential for daily users to access their accounts securely. Without a login mechanism, users cannot authenticate themselves, leading to limited functionality and potential security risks.

**Brief Solution:**

Implement a login page where users can input their credentials to authenticate themselves. Ensure proper authentication mechanisms are in place to securely verify user identities.

@Suchitra-Sahoo  please assign this issue to me under GSOC

**Comment by Manishar55** [comment]
Hii @Suchitra-Sahoo kindly assign this issue to me under gssoc24
I would like to add a login page

**Comment by Suchitra-Sahoo** [comment]
@aniket8000 assigned. You may start working on it.

**Comment by aniket8000** [comment]
@Suchitra-Sahoo  Thank you for assigning the task to me , I appreciate the opportunity to contribute. I'll start working on it right away and will keep you updated on my progress.  Looking forward to delivering a solution promptly.

**Comment by aniket8000** [comment]
@Suchitra-Sahoo I am delighted to inform you that I have successfully completed the issue assigned to me and please change the status.

**Comment by Riyasharma28** [comment]
Please assign this issue to me (Riyasharma28) under GSSoC'24.

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!
