### ISSUE TITLE
Integrate backend with contact us section

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Suchitra-Sahoo/AgriLearnNetwork#14]
The current "Contact Us" section lacks functionality to process user inquiries effectively. Users are unable to submit messages or receive responses, hindering communication and potentially leading to missed opportunities for engagement.

**Comment by rishyym0927** [comment]
I would like to address the issue regarding the "Contact Us" section, which lacks functionality to process user inquiries effectively. I propose to implement a solution that allows users to submit messages and receive responses, thereby improving communication and enhancing user engagement.

I'm confident in my ability to develop a robust solution to meet this need and ensure seamless communication between users and the platform.

Looking forward to your approval.

**Comment by Suchitra-Sahoo** [comment]
@rishyym0927 assigned. You may start working on it.

**Comment by Shyambarua** [comment]
Assign this issue to me 
As a full stack Developer i can write optimized code and responsive and i can integrate with backend also.

**Comment by Suchitra-Sahoo** [comment]
@rishyym0927 update me about your progress.
