### ISSUE TITLE
Feat: Implement Hover Effects and Logo Color Change for Social Media Icons in Footer Bar

### ISSUE THREAD

**Issue by anurag-jaiswal-aj** [Suchitra-Sahoo/AgriLearnNetwork#141]
### Describe the feature

The footer bar of the project lacks hover effects and logo color changes for social media icons, diminishing user interactivity and visual appeal. This issue aims to enhance user engagement by implementing hover effects and logo color changes for the social media icons in the footer bar. By adding these interactive elements, we can improve the overall user experience and encourage users to explore and connect with the project's social media channels. Kindly assign this task to me, and I'll work on implementing the desired hover effects and logo color changes. Thank you for the opportunity to contribute!

### Add ScreenShots

![Screenshot 2024-05-11 224800](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144160916/f2f7986b-6766-4a52-be17-8a5e45afc7ac)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anu00009** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
 Please assign me this project

**Comment by drashtigit** [comment]
Please assign me this project. I will be happy to do it

**Comment by anurag-jaiswal-aj** [comment]
Fixed: #199
