### ISSUE TITLE
Organic Farming Page

### ISSUE THREAD

**Issue by 2024-SANDHYA** [Suchitra-Sahoo/AgriLearnNetwork#143]
- Organic farming block connects to a youtube video
- I want to develop the page and embed the video in the page itself.

**Comment by Sujitmaurya123** [comment]
@Suchitra-Sahoo  please assign this issues me

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!
