### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by 2024-SANDHYA** [Suchitra-Sahoo/AgriLearnNetwork#144]
- Flipkart has 24x7 customer support
- Will incorporate the responsive chatbot
@Suchitra-Sahoo 

Under GSOC

**Comment by alamzia23** [comment]
can you please assign this issue to me? In my previous internship I had done the same task with the help of the IBM watsonx.

**Comment by Riyasharma28** [comment]
Please assign this issue to me (Riyasharma28) under GSSoC'24.
