### ISSUE TITLE
add more features like  youtube video playing in the website itself

### ISSUE THREAD

**Issue by riffhi** [Suchitra-Sahoo/AgriLearnNetwork#145]
### Describe the feature

The current color palatte and UI can be improved into a more lavish and better looking design. Font style should be changed and we can write blogs into the website itself rather than redirecting to another website, same goes wit youtube videos. we can add youtube vdeos onto the website only and resource library can be improved.  we can add more languages features as all the farmers do not know the english language. we can also add more blogs about current trends of crops, etc

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/111896909/1b192149-76b8-4f2a-a320-d57916e11f1f)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/111896909/8e6561a1-7e4c-4e1a-aafe-3a2215e9a295)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@riffhi assigned. You may start working on it.

**Comment by Shadyx6** [comment]
I would like to contribute in the redesign  and add minimal animations on the website. Please assign me @Suchitra-Sahoo @riffhi

**Comment by ashwin-j-r** [comment]
I would like to contribute in the redesign process, and would also love to work together with @riffhi if it is possible . The changes I would love to do is that change the font styling , and there are issues in hovering like in hovering the AgroBlogs section , we dont want to underline the heading , as the zoom in effect with border colouring is enough. Make the card size equal to every blog card size. And the contact us page input fields shadows etc.. and the submit buttons hover effect also and reduce the size of the copyright text etc. 
![Screenshot 2024-05-12 154445](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/75122684/d1587773-6dea-46fc-aca6-ae0cacddfc1e)
![Screenshot 2024-05-12 154413](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/75122684/2fd34f37-e500-4231-a2af-e0fd7bb10283)

**Comment by Shadyx6** [comment]
i have added mouse follower seedling and created a pull request, please check it @riffhi @Suchitra-Sahoo 
![Screenshot (129)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140224513/c1953509-7e2f-4c60-b985-a5c60fa1a45a)
