### ISSUE TITLE
Add some more blogs to the Agro blogs 

### ISSUE THREAD

**Issue by SaiSathvik6** [Suchitra-Sahoo/AgriLearnNetwork#146]
Blog 1. Understanding the Different Types of Herbicides and Their Uses
Blog 2. Importance of Soil Health in Agriculture: Tips for Optimal Soil Management
we can add some other helpful blogs to our page.

**Comment by SaiSathvik6** [comment]
Please Assign this to me.

**Comment by alamzia23** [comment]
can you please assign this issue tome?

**Comment by Suchitra-Sahoo** [comment]
Issue already assigned.
