### ISSUE TITLE
Feat: Enhance the AI ChatBot Working

### ISSUE THREAD

**Issue by aryansharma220** [Suchitra-Sahoo/AgriLearnNetwork#147]
### Describe the feature

We can enhance the chatbot to work more efficiently and reply more quickly.

@Ridhima10 Please assign under gssoc 24

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/133234867/1172c6c2-e522-4528-8aa9-b454142156b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@aryansharma220 assigned. You may start working on it.

**Comment by aryansharma220** [comment]
Thank you Ma'am, glad to be able to help. Please add a label of from level 1,2 or 3 so that I can get the points accordingly.
