### ISSUE TITLE
Feat:Adding a Feedback Form

### ISSUE THREAD

**Issue by vedanshipathak** [Suchitra-Sahoo/AgriLearnNetwork#148]
### Describe the feature

@Suchitra-Sahoo Currently the website is lacking the feedback form .i can work on it .

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by alamzia23** [comment]
can you please assign  this issue to me? I know how to implement it, we can use the html tags to do that and some css to give it a attractive button ui,

**Comment by Suchitra-Sahoo** [comment]
@vedanshipathak assigned. You may start working on it.
