### ISSUE TITLE
The image keeps on moving with respect to the changing text

### ISSUE THREAD

**Issue by kairveeehh** [Suchitra-Sahoo/AgriLearnNetwork#15]
@Suchitra-Sahoo  hello ,
as we can see on the deployed version that the image on the right side keeps on moving along with the text length on the home page , it needs to be aligned properly to give a better UI look .
I would like to work on this issue and request you to assign it to me.

**Comment by Suchitra-Sahoo** [comment]
@kairveeehh you are assigned. You may start working on the issue.

**Comment by Shyambarua** [comment]
Assign this issue to me 
As a full stack Developer i can write optimized code and responsive and i can integrate with backend also.
