### ISSUE TITLE
Not responsive

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Home page is not responsive . Assign me this task and I can make website responsive and add more styling to make the website attractive.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@meetarora10 assigned. You may start working on it.

**Comment by meetarora10** [comment]
Yes sure I will work on it.Thank you

**Comment by Sujitmaurya123** [comment]
@Suchitra-Sahoo  please assign this issues me
