### ISSUE TITLE
Responsive Design for Mobile Views and Button for Closing Chat Bot , contact page is not working as expected

### ISSUE THREAD

**Issue by Ramu-chiluveru** [Suchitra-Sahoo/AgriLearnNetwork#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current implementation of responsive design for mobile views lacks consistency and proper usability. Additionally, there is no clear button or functionality provided to close the chat bot, causing inconvenience for users who wish to dismiss it. Furthermore, the contact page requires fixes to ensure it functions correctly.
Proposed Solution:
Implement responsive design improvements to ensure a consistent and user-friendly experience across all devices.
Introduce a visible and intuitive button or functionality to allow users to easily close the chat bot.
Addressing the bugs or issues on the contact page to ensure its proper functionality.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ramu-chiluveru** [comment]
As a GSsoc'24 contributor. I want to work on this issue. So, I request you to assign this to me.
@Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
