### ISSUE TITLE
Improve Font of the website

### ISSUE THREAD

**Issue by MonikaLuhach** [Suchitra-Sahoo/AgriLearnNetwork#155]
### Describe the feature

Font improvement can be done.
Fonts play an important role in a website's design and user experience. Fonts impact the overall user experience of a website. A well-chosen font improves user satisfaction by making the content more accessible and enjoyable to read. On the other hand, poorly selected fonts can frustrate users and drive them away from the site.

Solution:
Choose Appropriate Fonts:
Select fonts that align audience preferences, and content tone. Consider factors like readability and emotional impact. Choose fonts that support a wide range of languages and character sets.
Optimize Font Size and Spacing:
Ensure that text is adequately sized for comfortable reading on various screen sizes. Adjust line spacing (line height) to improve readability and prevent text from appearing cramped or crowded. Increase the font size and adjust the contrast ratio to improve readability.

### Add ScreenShots

![WhatsApp Image 2024-05-12 at 09 26 27](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/132975234/39290884-c3bb-4dd7-9df7-e9752f6dc3aa)

We can use these fonts for better user experience and better website design.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MonikaLuhach** [comment]
@Suchitra-Sahoo Hii, I am happy to work on this issue under GSSOC 24 contribution. Could you please assign it to me?

**Comment by alamzia23** [comment]
Can you please assign this issue to me, I will be very happy in doing it.

**Comment by Suchitra-Sahoo** [comment]
@MonikaLuhach assigned. After making the changes raise a PR with a video or screenshot demonstrating your changes.

**Comment by mb-aarfi** [comment]
@Suchitra-Sahoo Can you assign this issue to me, As I am UI/UX designer too so I know which font will match with your needs. Please assign this issue to me I will be very happy.

**Comment by drashtigit** [comment]
@Suchitra-Sahoo Can you please assign me this issue. I am eager to do it.

**Comment by shendgeshraddha** [comment]
@Suchitra-Sahoo Can you please assign me this issue. I am eager to do it.

**Comment by shendgeshraddha** [comment]
@Suchitra-Sahoo Can you please assign me this issue. I am eager to do it.

**Comment by Divi-1026** [comment]
@Suchitra-Sahoo Hii, I am glad to work on this issue under GSSOC 24 contribution. Could you please assign it to me?

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by harshcodesit** [comment]
assign me this issue
