### ISSUE TITLE
BUG: Hover effect not visible on active link in navigation bar

### ISSUE THREAD

**Issue by thevijayshankersharma** [Suchitra-Sahoo/AgriLearnNetwork#156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The hover effect on the active link in the navigation bar is not visible. Specifically, when the "Home" link is active, the hover effect does not apply, making it difficult for users to identify the active link visually.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@thevijayshankersharma assigned. After making the changes raise a PR with a video or screenshot demonstrating your changes.

**Comment by thevijayshankersharma** [comment]
@Suchitra-Sahoo I have updated the code in new branch, should I merge it with main of mine repo ?
