### ISSUE TITLE
Feat: Enhancement of Contact Page

### ISSUE THREAD

**Issue by harikasayani** [Suchitra-Sahoo/AgriLearnNetwork#157]
### Describe the feature

It is not attractive. I'll make the contact form more attractive by adding features to it.

### Add ScreenShots

![Screenshot (75)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143275265/dc39b7b5-263f-42a4-95b7-2f42efd921b5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by harikasayani** [comment]
I am GSSOC'24 Contributor. Please assign this issue to me.

**Comment by dhanushsurendra** [comment]
I can make this visually appealing. Assign this issue to me @Suchitra-Sahoo under gssoc'24

**Comment by Sujitmaurya123** [comment]
@Suchitra-Sahoo please assign this issues me

**Comment by sobithav18** [comment]
I would like to request to be assigned to the task of enhancing the appeal and functionality of our website. Given my strong background in web development and experience in creating several websites, including one for a recent hackathon, I believe I can contribute effectively to improving our website.
