### ISSUE TITLE
Feat: Improve home page

### ISSUE THREAD

**Issue by harinisayani** [Suchitra-Sahoo/AgriLearnNetwork#160]
### Describe the feature

Currently, the home page is not all attractive.  
I want to work on it.

### Add ScreenShots

 
![Screenshot (1)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143276011/c1516cd9-6d2a-41fe-b57f-cab884dd92e1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sujitmaurya123** [comment]
@Suchitra-Sahoo please assign this issues me
