### ISSUE TITLE
Feat: Improve AgroBlogs

### ISSUE THREAD

**Issue by dhanushsurendra** [Suchitra-Sahoo/AgriLearnNetwork#162]
### Describe the feature

The interface can be made better for agro blogs

### Add ScreenShots

![Screenshot 2024-05-12 113816](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/50047808/f4b8a9c0-beba-487a-924a-38056a2feb45)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sujitmaurya123** [comment]
@Suchitra-Sahoo please assign this issues me

**Comment by Manaswini123456** [comment]
@Suchitra-Sahoo please assign me with this issue.
