### ISSUE TITLE
alignment of the copyright line in the footer

### ISSUE THREAD

**Issue by kairveeehh** [Suchitra-Sahoo/AgriLearnNetwork#17]
please assign this issue to me 
the copyright line is not aligned in the centre
**To Reproduce**
1. Go to 'home page'
3. Scroll down to 'footer '

**Expected behavior**
it should be in the center
**Screenshots**
If applicable, add screenshots to help explain your problem.[

(![Screenshot 2024-05-09 172418](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145572028/f4ede0b1-f12d-4917-a493-9b8728b00183))))

**Comment by Damini2004** [comment]
Assign this issue to me 
i can make changes in the form that it will apper in center after the social media links in footer section.As major types of website do this things for seeking more number of users on their platform.
Please assign this to me i have more knowledge regarding this.
Lets hope for the best

**Comment by kairveeehh** [comment]
> Assign this issue to me i can make changes in the form that it will apper in center after the social media links in footer section.As major types of website do this things for seeking more number of users on their platform. Please assign this to me i have more knowledge regarding this. Lets hope for the best

well what "MORE" knowledge is required to centre something , raise new issues if required instead of this .
