### ISSUE TITLE
Feat:Crop recommendation System and also the plant diseases prediction model

### ISSUE THREAD

**Issue by palayushi293** [Suchitra-Sahoo/AgriLearnNetwork#172]
### Describe the feature

In this the Farmer enter many of the features like rainfall, humidity, ph of the soil and many more and we have to predict which crop is suitable for that particular features and that will be of higher accuracy greater than 95% 

### Add ScreenShots

[Crop_recommendation.csv](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/files/15285880/Crop_recommendation.csv)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
The issue is now being closed
