### ISSUE TITLE
Feat: Back-to-top

### ISSUE THREAD

**Issue by hars-21** [Suchitra-Sahoo/AgriLearnNetwork#173]
### Describe the feature

Making back to top button fixed for all sections and aligning it above chatbot icon.
It will enhance ui and ux of page and easy for user to navigate to top from any section.

### Add ScreenShots

![Screen Shot 2024-05-12 at 4 08 29 PM](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144909381/9d878217-ed1f-4d78-b7bc-78bd3cd70283)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@Suchitra-Sahoo I can fix this properly, assign this task to me

**Comment by hars-21** [comment]
@Suchitra-Sahoo PLease reassign me and I have made a PR. Please Review
