### ISSUE TITLE
Feat: Subscribe to newsletter

### ISSUE THREAD

**Issue by hars-21** [Suchitra-Sahoo/AgriLearnNetwork#175]
### Describe the feature

Adding subscribe to newsletter feature in footer.

### Add ScreenShots

![Screen Shot 2024-05-12 at 4 08 29 PM](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144909381/7bf86402-2f52-4204-80a2-b18d7c33abd5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubhra-Narang** [comment]
Hello, I'm a GSSOC'24 contributor
I would like to work on the same. Can you please assign this to me.
