### ISSUE TITLE
UNECESSARY SPACE AFTER NAVBAR ICON

### ISSUE THREAD

**Issue by Nih1tGupta** [Suchitra-Sahoo/AgriLearnNetwork#178]
### Describe the feature

Unecessary space after navbar  elements is present . which i have fixed
Also padding is not present .
Additional :
I have added some hover effect to be attractive.

### Add ScreenShots

![agri](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119615342/098a4c30-a832-4615-8b68-130079b062c7)
Kindly assign me this issue to work on under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by supriyagaut** [comment]
@Nih1tGupta i want to work for this please assign to me
