### ISSUE TITLE
Update Copyright Year Dynamically in Footer.

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Suchitra-Sahoo/AgriLearnNetwork#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Suchitra-Sahoo, the current footer in index.html contains a hardcoded copyright year. To ensure that the copyright year is always up-to-date, it would be beneficial to update it dynamically. This can be achieved by implementing a mechanism that automatically updates the year to the current year.

**Please assign this to me under GSSOC'24 and please add the GSSOC labels. Thank you!!** 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Srujitha-Raghava** [comment]
@Suchitra-Sahoo mam,please assign this to me so that i can work on this.As this is pure JavaScript, meaning it will refresh the year browser-side, depending on the user's time settings.

i want to  work on this issue
