### ISSUE TITLE
better social links in the footer

### ISSUE THREAD

**Issue by kairveeehh** [Suchitra-Sahoo/AgriLearnNetwork#18]
in the footer part only one social email is mentioned via text , we can improve this using an icon that on hover shows the mail to the user in form of blob and on click directs the user to the mail 

this will enhance the UI and we can add other social links as well (if required)
**please assign this issue to me as** I already have it forked to local and am working on other issues as well
![Screenshot 2024-05-09 172418](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145572028/7facebbd-d123-4af6-8409-18e96fadb660)

**Comment by kamalesh-og** [comment]
Hi
I would like to take up this project for adding elements to the footer section
We can make the footer section with more impressive UI and progressive elements to make it look amazing
We can add several icons and hyperlinks and lil more creative designs for better attractiveness 
I would be delighted to take up this task
Thank you.

**Comment by Damini2004** [comment]
I can handle this issue more efficiently 

1. Theme section for diverse individuals.
2. Even though we can add icons which make it more tempting in apperance.
3. Here we can add hover effect which make it more realistic.
4. Footer section will be responsive for all kind of screen sizes.
5. Back to Top button integration.
Please assigned this to me for revolutinary betterment in the footer section.

**Comment by kairveeehh** [comment]
@Suchitra-Sahoo,  Ma'am this is petition to let people who raised issues have the assignment , as it fosters a sense of engagement for the others to look up for issues themselves and be more creative in raising features and bugs.
thankyou

**Comment by Shyambarua** [comment]
Assign this issue to me 
As a full stack Developer i can write optimized code and responsive and i can integrate with backend also.

**Comment by kairveeehh** [comment]
@Suchitra-Sahoo the leaderboard isnt counting contributions before 7pm , please make sure to merge requests after that

**Comment by sahithinandikula** [comment]
@Suchitra-Sahoo please assign me this task as have a keen interest in working on this
