### ISSUE TITLE
Add Logo in the Navbar

### ISSUE THREAD

**Issue by mb-aarfi** [Suchitra-Sahoo/AgriLearnNetwork#181]
### Describe the feature

Hello PA,
There is no logo of AgriLearnNetwork in your navbar which is an important part of any website to attract the users.
As I am a graphic designer too so i can create an attractive logo for you and add it on your navbar.

Please assign this work to me, I will be very thankful to you.

### Screenshot - 

![Screenshot 2024-05-12 184143](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143268082/faa59fa1-4d17-4485-a67d-d7d5aa5018a6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubhra-Narang** [comment]
Hello, I'm a GSSOC'24 contributor
I would like to work on the same. Can you please assign this to me.

**Comment by codewithishu** [comment]
Hello, I'm a GSSOC'24 contributor.
I have better experience on HTML,CSS and JS.
I would like to work on the same. Can you please assign this to me.

**Comment by gundellyvamshiyadav** [comment]
I would like to work on this issue.Can you please assign this to me.

**Comment by Anshika2608** [comment]
Hello,I'm Gssoc contributor,i have build a full mern stack e-commerce website which is designed by myself.please assign this issue to me .I will feel blessed to contribute in your project

**Comment by cptainperoxide** [comment]
I would also Like to work on this. Please assign this issue to me

**Comment by niteshbca** [comment]
@mb-aarfi Please assign to me task and solve the problem.
