### ISSUE TITLE
Add CONTRIBUTNG.md file

### ISSUE THREAD

**Issue by krishnas005** [Suchitra-Sahoo/AgriLearnNetwork#182]
### What's wrong with the existing documentation

I propose adding a CONTRIBUTING.md file to the repository to provide contributors with guidelines and instructions for contributing to the project. This file will serve as a reference for newcomers and existing contributors, outlining the contribution process, coding standards, and other relevant information necessary for effective collaboration.

@Suchitra-Sahoo Assign this task to me under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
There is already a contributing.md file. Do you want to contribute in improving it?
