### ISSUE TITLE
Sign up and log in and create account page and will try to improvise the resource library section by adding more blogs 

### ISSUE THREAD

**Issue by somaakash** [Suchitra-Sahoo/AgriLearnNetwork#19]
Hello mam, 
I have experience in HTML,CSS and BOOTSTRAP .
So the isuue here-
There is no sign up page and account log in page .So I will try to make it by using html and css and bootstrap if needed.And will try to improvise few things which i can like resource library page by adding more blogs (1-2 max by me)
I request you assign me so that i will work on it.

And i am having a idea like creating a 1:1 mentoring feature for educating about farming or any techniques like that.if it is ok will try on that.
just got thought..

**Comment by Shyambarua** [comment]
Assign this issue to me 
As a full stack Developer i can write optimized code and responsive and i can integrate with backend also.

**Comment by surendar-05** [comment]
Hey!! Assign this issue to me i want to work on this?under Gssoc'24

**Comment by Suchitra-Sahoo** [comment]
> Hello mam, I have experience in HTML,CSS and BOOTSTRAP . So the isuue here- There is no sign up page and account log in page .So I will try to make it by using html and css and bootstrap if needed.And will try to improvise few things which i can like resource library page by adding more blogs (1-2 max by me) I request you assign me so that i will work on it.
> 
> And i am having a idea like creating a 1:1 mentoring feature for educating about farming or any techniques like that.if it is ok will try on that. just got thought..

The issue of adding the sign up page and blogs has already been assigned to someone.

**Comment by Suchitra-Sahoo** [comment]
> Hello mam, I have experience in HTML,CSS and BOOTSTRAP . So the isuue here- There is no sign up page and account log in page .So I will try to make it by using html and css and bootstrap if needed.And will try to improvise few things which i can like resource library page by adding more blogs (1-2 max by me) I request you assign me so that i will work on it.
> 
> And i am having a idea like creating a 1:1 mentoring feature for educating about farming or any techniques like that.if it is ok will try on that. just got thought..

Adding the signup page and blog has been assigned to someone.
