### ISSUE TITLE
BUG: AgroBlogs hover

### ISSUE THREAD

**Issue by hars-21** [Suchitra-Sahoo/AgriLearnNetwork#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

One of the card of agro blog behaves differently with respect to others.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is resolved
