### ISSUE TITLE
BUG: Home page is not responsive

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Suchitra-Sahoo/AgriLearnNetwork#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Home page is not responsive .. Home page left side is not visible for small devices

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SuhainaFathimaM** [comment]
@Suchitra-Sahoo Please assign me this issue.. I am good at front end development.. I have worked on many open source projects

**Comment by Suchitra-Sahoo** [comment]
issue already assigned.
