### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by sanjay-kv** [Suchitra-Sahoo/AgriLearnNetwork#2]
In GSSoC'24, GitHub Topics will help the discoverability of your project.

I see that you already have great topics on your repository!
I would recommend adding the name of the company like the software you use to build like "vs-code, ghdesktop" to improve your discoverability.

If you are happy with the topics you have, feel free to close this issue. 👍

**Comment by Suchitra-Sahoo** [comment]
Do you want me to add software used point in readme section?

**Comment by sanjay-kv** [comment]
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/30715153/bc28e353-f96c-41ea-8196-fce353e372ac)
yes, simillar to above sample

**Comment by Suchitra-Sahoo** [comment]
Okay now I have added.

**Comment by sanjay-kv** [comment]
thanks, Closing this issue now.
