### ISSUE TITLE
Changing of old twitter logo to X

### ISSUE THREAD

**Issue by Ariway** [Suchitra-Sahoo/AgriLearnNetwork#202]
changing the twitter logo to X since it is no more twitter

**Comment by Shubhra-Narang** [comment]
Hello, I'm a GSSOC'24 contributor
I would like to work on the same. Can you please assign this to me.

**Comment by Ariway** [comment]
Hello @Suchitra-Sahoo  Please assign this issue to me because i would love to solve this issue under GSSOC'24 and i have created this issue so would like to contribute to it

**Comment by chaitanyatamira** [comment]
I would really like to work on this .Please assign me this issue @Suchitra-Sahoo under GSSOC'24

**Comment by kartikmehta18** [comment]
I'm a GSSOC'24 contributor
plz assign me issue

**Comment by RekhaKushwaha01** [comment]
I would like to work on this .Please assign me this issue

**Comment by Tanu2205** [comment]
I am a Gssoc 2024 contributer, can you please assign me this issue?

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by anandita01** [comment]
I want to work on this please assign me the task

**Comment by gundellyvamshiyadav** [comment]
i would like to work on this issue under gssoc'24.
