### ISSUE TITLE
Enhancing blogs page

### ISSUE THREAD

**Issue by Deepspsps** [Suchitra-Sahoo/AgriLearnNetwork#204]
**Description:**
The blogs section looks uneven since each box is sized according to the matter within.

![Screenshot 2024-05-12 232722](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/86245344/662513b8-f1ec-44f6-a70b-f3f3ef46724f)

**My approach:**
- I would like to fix a size for all the blogs that are being displayed.
- Rephrase and modify the content within to make it more precise.

**Record:**
- [x] I agree to follow this project's Code of Conduct
- [x]  I'm a GSSOC'24 contributor
- [x]  I want to work on this issue

**My appeal:**
Kindly assign this issue to me as I'm experienced in this sector of Front end development and have worked on many personal projects.

**Comment by Suchitra-Sahoo** [comment]
@Deepspsps you are assigned.
