### ISSUE TITLE
Redesigning Contact us page

### ISSUE THREAD

**Issue by Rohitha-pudu** [Suchitra-Sahoo/AgriLearnNetwork#207]
### redesign the contact us for better UI and UX

**Comment by saumyajainnn** [comment]
Please assign this issue to me.. I would like to work on this issue

**Comment by Riyasharma28** [comment]
Please assign this issue to me (Riyasharma28) under GSSoC'24.

**Comment by kartikmehta18** [comment]
I'm a GSSOC'24 contributor
plz assign me issue

**Comment by Sailza** [comment]
hi I would like to contribute on this problem under GSSoC 2024 as a contributer
