### ISSUE TITLE
Text color while hovering on "resource library" card  to make it more visually clear an appealing

### ISSUE THREAD

**Issue by Ridhima10** [Suchitra-Sahoo/AgriLearnNetwork#21]
issue-
Current color on cards is not clear since it merges either with the background of color of the image.

![Screenshot 2024-05-09 212818](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/85826117/8da51d1f-ed03-41c7-a3e6-c33078d03a4f)
![Screenshot 2024-05-09 212900](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/85826117/82d87608-6a1f-4adb-a234-106dd3fd0ce9)

Solution/ Enhancement-
I will add the color of your theme pallete with a text shadow or highlight it so that it will improve the UI of the website 

Please assign this issue to me. 
Best regards.

**Comment by Suchitra-Sahoo** [comment]
@Ridhima10 assigned. You may start working.

**Comment by Ridhima10** [comment]
Hello PA @Suchitra-Sahoo ,
I did this with 2 approaches
1. I have changed the text with the most dominating color so that it will not overlap in any sense 
![Screenshot 2024-05-10 184959](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/85826117/84f07674-1378-4948-bf25-7296930968d6)
![Screenshot 2024-05-10 185036](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/85826117/edf3a292-1afa-4f1a-843a-cffba2977b91)

2. Since previous color was something light so i added a text shadow to make it more appealing

![Screenshot 2024-05-10 190511](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/85826117/6eb6093e-bf58-455d-bab9-a396ada5e909)


Both of the options are suiting well with the cards.  You tell me which one do you prefer ?

**Comment by sahithinandikula** [comment]
@Suchitra-Sahoo I am frontend developer having interested in the project ,I would like to contribute for this
