### ISSUE TITLE
Feat: Add GitHub icons

### ISSUE THREAD

**Issue by codewithishu** [Suchitra-Sahoo/AgriLearnNetwork#211]
### Describe the feature

GitHub icons should be added to the footer section .
It will allow the user to review the code.

### Add ScreenShots

![Screenshot 2024-05-13 002621](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146975269/04b71386-2188-4af4-a06c-5f06502ed16f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by codewithishu** [comment]
Please assign this issue to me.

**Comment by Suchitra-Sahoo** [comment]
It is not required.
