### ISSUE TITLE
Feat:Add a dark mode feature

### ISSUE THREAD

**Issue by Shivam250702** [Suchitra-Sahoo/AgriLearnNetwork#213]
### Describe the feature

Dark mode feature to reduce eye stress for some of the users

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/103785990/9f6a3c5a-f20b-4ff9-9f35-dc1d8e71892d)

Add a dark mode button in this navbar

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swatiinigam** [comment]
I would like to contribute please assign it

**Comment by Suchitra-Sahoo** [comment]
@Shivam250702 what's the update?

**Comment by abhinavraajput** [comment]
@Suchitra-Sahoo Please assign this issue under GSSOC'24 , i will fix this issue.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
