### ISSUE TITLE
Improving the contact page

### ISSUE THREAD

**Issue by Manishar55** [Suchitra-Sahoo/AgriLearnNetwork#214]
### Describe the feature

Hii @Suchitra-Sahoo 
I want to improve the UI of contact page, i will change the color combination to make it more attractive.
can you please assign this issue to me under gssoc24.

### Add ScreenShots

![Screenshot 2024-05-13 012713](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/154615478/0dc78e57-5dd4-4467-85ec-3982dd03026f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by khushilatey16** [comment]
hey @Suchitra-Sahoo plz assign this issue to me I'll make updation in contact us page and make it more attractive

**Comment by pujakulkarni** [comment]
I want to improve the colors to make it more aesthetically appealing . A well-designed "Contact Us" page can significantly enhance user experience &  build trust . I want to work on this project so please assign this issue to me.

contact us improved
![feedbackform](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/128357290/7e035ff0-92a8-4b94-a308-7630b9118a73)
