### ISSUE TITLE
Hovering effect on form fields

### ISSUE THREAD

**Issue by Nehakumari1208** [Suchitra-Sahoo/AgriLearnNetwork#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

on clicking it get hover effect

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Nehakumari1208** [comment]
Assign this to me

**Comment by CHITRA2445** [comment]
Hi @Suchitra-Sahoo . I am interested in working in this issue under the  label GSSOC'24

**Comment by niteshbca** [comment]
@Nehakumari1208 Please assign to me task and solve the problem.

**Comment by nishitasinghhh** [comment]
@Suchitra-Sahoo I am willing to work on this issue, kindly assign me this issue
