### ISSUE TITLE
Feat: Adding Animation 

### ISSUE THREAD

**Issue by harshmishra19** [Suchitra-Sahoo/AgriLearnNetwork#220]
### Describe the feature

- I would like to add animation on the about pages image to make it look more appealing 
- Your landing page already looks fantastic, but incorporating animations could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement.
- If you could assign me this task under GSSOC24, I would be thrilled to work on it.

### Add ScreenShots

![Screenshot (116)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115486960/0d74a1a4-426a-4046-bc4d-4d51a7c5d3ec)
![Screenshot (115)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/115486960/388183e8-de4c-40d6-ad1b-116617ed14da)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@harshmishra19 you are assigned.
