### ISSUE TITLE
Footer moves upwards

### ISSUE THREAD

**Issue by Priyal208** [Suchitra-Sahoo/AgriLearnNetwork#221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer should remain sticky to the bottom, it moves away to the top when scrolling , so make it sticky.
![Screenshot 2024-05-13 104445](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/135015851/0090e264-6460-48c6-bf7b-6b332fe70f40)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by swatiinigam** [comment]
I would like to work on it please assign

**Comment by Priyal208** [comment]
@Suchitra-Sahoo Thank you for assigning!

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
