### ISSUE TITLE
adding more Agroblogs

### ISSUE THREAD

**Issue by Hemav009** [Suchitra-Sahoo/AgriLearnNetwork#232]
### Describe the feature

I want to add more Agroblogs about(smart farming, AI in farming, Vertical farming).

Please assign me 

Thank you!

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/4856306f-d9bc-4f6c-83d5-98c5957eb0a1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Can you write your own blogs using html css and link it.? If you can then I may assign you.

**Comment by Hemav009** [comment]
Yeah sure I will do that.

**Comment by Suchitra-Sahoo** [comment]
@Hemav009 are you done with the work?

**Comment by Hemav009** [comment]
I will make a PR tomorrow.

**Comment by Hemav009** [comment]
@Suchitra-Sahoo  now can I add more blogs to the blog page?
