### ISSUE TITLE
BUG: The agroblogs section and the cards below it don't have proper margin.

### ISSUE THREAD

**Issue by Rakshit-gen** [Suchitra-Sahoo/AgriLearnNetwork#233]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/64471316/0a1e8e51-1292-478d-aa86-1fd07377c9b8)

The margin in this screenshot when we hover on the card is not enough. We can increase the margin more to make it look better. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sambangiadharsh** [comment]
i think i can solve this issue please assigned this work to me.
