### ISSUE TITLE
BUG:  Incorrect Paragraph Linking in Card Component

### ISSUE THREAD

**Issue by Astha86** [Suchitra-Sahoo/AgriLearnNetwork#236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I've identified a bug in the card component under AgroBlogs section on website. In 4th card, not only the card headings but also the paragraphs are redirecting users to any other website.

The hover effect underlines the paragraph, affecting the UI negatively.

![Screenshot 2024-05-13 140908](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142304973/c98d7501-ff79-42e5-867d-9cfd9aa1fdd0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Astha86** [comment]
Hello @Suchitra-Sahoo, I want to fix this bug. Please label it under GSSOC'24 and assign this to me.

**Comment by Suchitra-Sahoo** [comment]
I want you to fix it by making sure that the user can be directed to the website by clicking any region of the card and not just heading.

**Comment by Astha86** [comment]
Ok, I will fix this problem.

**Comment by Suchitra-Sahoo** [comment]
This issue has been resolved.

**Comment by Astha86** [comment]
Hey @Suchitra-Sahoo 

I added 1 more feature on hovering over the cards the cursor becomes pointer that enhance UI. 

Currently: 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142304973/eb34b00a-fecc-4a80-a4b7-f88df41ed6f5

What I want to Change: 


https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142304973/4c038499-e750-4639-ba92-6d4a86daa713


I made this change ... I want to raise the PR . Please...re-assign this to me .
