### ISSUE TITLE
NAVBAR CONTACT ICON LACKS HOVER EFFECT

### ISSUE THREAD

**Issue by Nih1tGupta** [Suchitra-Sahoo/AgriLearnNetwork#237]
### Describe the feature

NO DESCRIPTION NEEDED

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119615342/bdb5a1b6-cb02-4b09-87c3-e79a288ef389)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Already assigned to someone.
