### ISSUE TITLE
Feat: Change Footer design 

### ISSUE THREAD

**Issue by Amrit49** [Suchitra-Sahoo/AgriLearnNetwork#243]
### Describe the feature

I would like to change the footer design and give proper layout to footer .

### Add ScreenShots

![Screenshot 2024-05-13 173837](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/121235681/47c98e8a-a837-4b9d-8083-63b7ebafeb75)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
How will improve. Please elaborate.

**Comment by Suchitra-Sahoo** [comment]
issue is resolved
