### ISSUE TITLE
Feat: It should capture number of views and likes /review on blogs

### ISSUE THREAD

**Issue by KanodiaKash** [Suchitra-Sahoo/AgriLearnNetwork#248]
### Describe the feature

Blogs should have number of views and rating captured and should have option to sort on basis of this

### Add ScreenShots

<img width="1470" alt="Screenshot 2024-05-13 at 6 36 39 PM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143932704/823b0236-1718-4a4f-8753-3a22d677026a">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
How will you implement this?

**Comment by KanodiaKash** [comment]
We will call a javascript function  in HTML onclick every time a user clicks on a blog. The function will maintain a counter for each blog and increase by one on every click. 
We will return this value on homepage by using HTML.

**Comment by KanodiaKash** [comment]
@Suchitra-Sahoo - any update?

**Comment by Suchitra-Sahoo** [comment]
Sorry for late reply, a lot of issue came above yours due to which it got missed. This feature is not required right now.
