### ISSUE TITLE
Feat: Adding a logo beside the title 

### ISSUE THREAD

**Issue by Saimanjari777** [Suchitra-Sahoo/AgriLearnNetwork#249]
### Describe the feature

It would look good if there is a logo beside the heading "AgriLearn Network".
Please assign this task to me!

### Add ScreenShots

![Screenshot 2024-05-13 190246](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/130165687/7c4cf245-9b42-4b13-b0af-d9f797834f57)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue already assigned.
