### ISSUE TITLE
Feat: Contact Us can be redesigned

### ISSUE THREAD

**Issue by AshAk0** [Suchitra-Sahoo/AgriLearnNetwork#251]
### Describe the feature

I can rework with the contact us page design

### Add ScreenShots

![Screenshot 2024-05-13 200403](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/130728058/17bde62a-d990-46a7-82e5-18c41f4a221b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AshAk0** [comment]
Can you checkout this design and confirm is it ok or you need any changes in it

https://www.figma.com/design/wlFqjCIbofjbN9Ryyorfti/AgriLearnNetwork-ContactUsPage?node-id=0%3A1&t=SRWLcyBkJ7FIhQwU-1

**Comment by AshAk0** [comment]
Check out the design have added few more context to the design

**Comment by Suchitra-Sahoo** [comment]
@AshAk0 its looking great! You may proceed.

**Comment by divyalaldinani** [comment]
@Suchitra-Sahoo can i work on this issue, i cant see a PR on this issue and its been 4 days since this issue was opened.

**Comment by AshAk0** [comment]
I have started with the coding and the work is going on

**Comment by Suchitra-Sahoo** [comment]
@AshAk0 what is the update?

**Comment by divyalaldinani** [comment]
> @AshAk0 what is the update? I hope you are working on it. Just a slight change that create a separate contact page instead of including on main page.

I can contribute, you can let me know.

**Comment by AshAk0** [comment]
> @AshAk0 what is the update? I hope you are working on it. Just a slight change that create a separate contact page instead of including on main page.

ok i will do it

**Comment by divyalaldinani** [comment]
@Suchitra-Sahoo hey let me know if i can start working on this issue, i will create a PR till tomorrow afternoon
