### ISSUE TITLE
Add Login and Signup page

### ISSUE THREAD

**Issue by Sneha123-zudo** [Suchitra-Sahoo/AgriLearnNetwork#252]
### Describe the feature

I want to add login and signup page page for this website.
I will create responsive and good UI page.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145490348/e47b5e2f-f949-411c-9805-0088044de11e)

This type of page.
Please assign me this issue under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SantoshiVerma** [comment]
hey @Suchitra-Sahoo ,I would like to work on thi issue under GSSOC2024.Please assign this to me.

**Comment by brewcoder6113** [comment]
hey @Suchitra-Sahoo ,I would like to work on this issue under Gssoc'2024 .Please assign this to me.

**Comment by nikhilchopra08** [comment]
hey @Suchitra-Sahoo ,I would like to work on this issue under Gssoc'2024 .I will also try to write backend along with frontend

**Comment by Supraja-Gao** [comment]
I would like to work on this issue please assign it to me.
