### ISSUE TITLE
Improve the UI of the background of about section, blogs sections, and resources section.

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Suchitra-Sahoo/AgriLearnNetwork#256]
Can implement Animated Backgrounds/ video background or use any other interactive implement to make other sections of the website go along with the home page as currently its just a green background.

**Comment by sancharigandhi** [comment]
Hi @Suchitra-Sahoo,

I'm eager to take on the task of implementing animated backgrounds or video backgrounds for GSSoC 24. With my experience in website development using HTML, CSS, and JavaScript, I'm confident I can bring an engaging and interactive element to the website.

Please assign this task to me under GSSoC 24, and I'll begin working on incorporating animated backgrounds or video backgrounds to enhance the user experience across various sections of the website.

Thank you!

**Comment by Nih1tGupta** [comment]
Please assign this task to me under GSSoC 24
Uploading AgriLearnNetwork - Google Chrome 2024-05-14 09-56-09.mp4…

**Comment by Nih1tGupta** [comment]
**Please assign** this task to me under **GSSoC 24.**
I **will add** some cool **pictures** for background apart from this.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119615342/4b710f2f-20b8-4776-ad37-06b1bec9cb64

**Comment by PuR-vI** [comment]
Please assign this task to me under GSSoC 24, and I'll begin working on creating appealing backgrounds and working towards making the website engaging. 

Thank you!

**Comment by Anshu3301** [comment]
Hello @Suchitra-Sahoo, just Updated the About section, currently working on Blog & Resource section thinking about adding video background... Can you please assign me this task under GSSOC'24 ?

Updated page:
![Screenshot (167)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/134282893/807c2dc7-9c95-499c-94cd-775c9d0c1dba)

**Comment by Anshi150** [comment]
Hi @Suchitra-Sahoo,
I also make that I can make an animated background.
Can you please assign me the project to solve the problem and make your project different.

**Comment by vipinmishra0852** [comment]
Hey @Suchitra-Sahoo I would love to work on this task I'll add animation and I will redesign some parts keeping in my that it is for agricultural practices and make it responsive too please assign me this task....

**Comment by Suchitra-Sahoo** [comment]
@Anshu3301 more than one person can't work on the same issue. Already some people are working on about and home section so you may look into blog and resources section. But for that raise another issue so that you can raise PR under that issue number.

**Comment by Anshu3301** [comment]
OK, got it...
