### ISSUE TITLE
BUG: Validation in Contact us form

### ISSUE THREAD

**Issue by dhruv8433** [Suchitra-Sahoo/AgriLearnNetwork#258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo 
please checkout this there is no contact validation
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/f159f70b-101a-4a92-814e-fdfec4487839)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sagargupta028** [comment]
Assign this isssue to me

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

# need-help
please add level lable

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

add level lables
