### ISSUE TITLE
BUG: Image Resourse Library Image not set properly

### ISSUE THREAD

**Issue by dhruv8433** [Suchitra-Sahoo/AgriLearnNetwork#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo 

please check out this, image width overflow and not visible properly
and also hover effect not l
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/3ea2bd59-d213-4005-84e0-850e39887a55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
I have checked the website but didn't find any such problem. In what kind of device this issue is being faced?
