### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by anshgautam-github** [Suchitra-Sahoo/AgriLearnNetwork#26]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Can you assign this issue to me under GSSOC 24

**Comment by Suchitra-Sahoo** [comment]
> The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.
> 
> Can you assign this issue to me under GSSOC 24

@anshgautam-github assigned. You may work on it.

**Comment by anshgautam-github** [comment]
@Suchitra-Sahoo  Sure!
