### ISSUE TITLE
hover effect on the card

### ISSUE THREAD

**Issue by Varsani2520** [Suchitra-Sahoo/AgriLearnNetwork#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo 
 hover on the card then then it outside the glow ,
it come in proper card then look like good 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/137641079/99fcec86-df0b-409d-be66-f8c127387bdb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Issue already assigned.
