### ISSUE TITLE
BUG: Responsive Feedback form not look and overflow

### ISSUE THREAD

**Issue by dhruv8433** [Suchitra-Sahoo/AgriLearnNetwork#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo 

check out this pic, feedback form not display perfect in responsive screen
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/2195ffd7-2bec-46b8-87e7-4282b1258b3e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue already assigned
