### ISSUE TITLE
BUG:user hover on the card then it is not in perfect layout 

### ISSUE THREAD

**Issue by Varsani2520** [Suchitra-Sahoo/AgriLearnNetwork#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo  user hover on the card then card img width is cut the right section ,thats why proper border radius not display 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/137641079/41f98532-1de5-4c43-8c6f-b5c1af2ebefe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Is it happening in mobile device?

**Comment by Varsani2520** [comment]
@Suchitra-Sahoo  ,it is happenig in all devices

**Comment by Suchitra-Sahoo** [comment]
But I just checked and everything is working properly.
