### ISSUE TITLE
BUG:user hover on the card display poiner cursour 

### ISSUE THREAD

**Issue by Varsani2520** [Suchitra-Sahoo/AgriLearnNetwork#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @Suchitra-Sahoo  ,when user hover or click on card then display pointer type cursour instead of arrow 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/137641079/1c58fc43-a88e-4b18-917e-302a8c0c46ce)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
I have checked the website but I can't find this problem. In what knid of device you are facing this problem?
