### ISSUE TITLE
BUG: Card layout of Blogs Section

### ISSUE THREAD

**Issue by dhruv8433** [Suchitra-Sahoo/AgriLearnNetwork#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo 

Please check out this card layout is not same in blogs card
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/dd42c154-fc35-48cc-a146-51b7aa4bb458)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue already assigned.
