### ISSUE TITLE
Hover effects on Social Icons

### ISSUE THREAD

**Issue by shubhisingh184** [Suchitra-Sahoo/AgriLearnNetwork#265]
### Describe the feature

Want to add Hover effects on social media icons as it will give it a more appropriate look to the website and provide good user experience.

### Add ScreenShots

It will brighten when user hover over any social media icon button.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by BhumikaRahwani** [comment]
Hi!! @Suchitra-Sahoo I am Bhumika Rahwani, contributor in GSSoC. I would like to address this issue and make the respective changes.

**Comment by cptainperoxide** [comment]
I would also Like to work on this. Please assign this issue to me
