### ISSUE TITLE
Footer section is static 

### ISSUE THREAD

**Issue by reshamsai150** [Suchitra-Sahoo/AgriLearnNetwork#266]
### Describe the feature

I want to add hovering effects for icons and make the footer  section more attractive assign this issue to me @Suchitra-Sahoo 

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/164533685/67d387a2-d5f8-4da1-9bde-f769486c7941)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue assigned already
