### ISSUE TITLE
Feat: Beautify the Blog Cards

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#268]
### Describe the feature

I wish to add images with filter as background of each card which disappear on hover to solid color

### Add ScreenShots

![Screenshot 2024-05-14 000155](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146661411/03ad22a6-ef72-4214-baf7-edc68f2eb3b6)
Left: In general view
right: on hover

N.B: The screenshot might be brighter due to some setting on my device which I use for my graphic design works.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Make sure your design don't overpower the text part

**Comment by SMARTHMALIK** [comment]
Greeting @Suchitra-Sahoo 
I request you to assign me this issue . I try to resolve this in the best possible way . Thankyou.

**Comment by shreyasupe35** [comment]
Hi,I wish to solve the issue in the best possible way,please assign me the issue

**Comment by CHITRA2445** [comment]
Hi @Suchitra-Sahoo . I am interested in working in this issue under the  label GSSOC'24
