### ISSUE TITLE
Unnecessary Dropdown in Mobile Number section in Forms.

### ISSUE THREAD

**Issue by anshmanitripathi** [Suchitra-Sahoo/AgriLearnNetwork#27]
There is no need of dropdown in the mobile number section in form.

This dropdown may leads to enter wrong phone number by accidently touching the drop down.

**Comment by anshmanitripathi** [comment]
i want to work on this please assign this task to me.

**Comment by Suchitra-Sahoo** [comment]
@anshmanitripathi assigned. You may work on it.

**Comment by pandey079** [comment]
i want to work on this please assign this task to me.

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!
