### ISSUE TITLE
Feat: Add a Testimonial Section to feature feedbacks

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#270]
### Describe the feature

We are collecting feedbacks so there must be a section to display reviews and testimonials.  I wish to add this

### Add ScreenShots

It will be simple, name/anonymous and some text. I can give screenshot once I start working on this after assignment

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anamika-Ratna** [comment]
Hi ! I would like to work on this issue, kindly assign me this under gssoc tag.
