### ISSUE TITLE
Feat: Agriculture policies

### ISSUE THREAD

**Issue by Anamika-Ratna** [Suchitra-Sahoo/AgriLearnNetwork#271]
### Describe the feature

I would like to add a section of agricultural policies that describes some of the imp policies related to farming or agriculture after the " resource library"  section .

### Add ScreenShots

![Screenshot (671)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/122286548/9437017e-2236-4537-96c9-4041dc4d56a3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This feature is not required
