### ISSUE TITLE
 "Hey, I think your footer could be improved. The font-family and color palette should be updated."

### ISSUE THREAD

**Issue by rabinarayanpadhy07** [Suchitra-Sahoo/AgriLearnNetwork#274]
### Describe the feature

"Footer could be improved. The font family may be updated for improved readability and visibility, as may the color palette.

### Add ScreenShots

Please assign me this issue to fix it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AdhithiManjunath** [comment]
i want to work on this issue , please do assign this

**Comment by shubham6m** [comment]
please assign this task to me

**Comment by niteshbca** [comment]
@rabinarayanpadhy07 Please assign to me task and solve the problem.

**Comment by Gauri-Dabhade** [comment]
assign me this task under gssoc 
Selecting a modern, readable font-family can significantly improve the appearance of your footer.
and some general design will improve it
