### ISSUE TITLE
Feat: Adding testimonials or feedback section

### ISSUE THREAD

**Issue by Chelseasingla1** [Suchitra-Sahoo/AgriLearnNetwork#278]
### Describe the feature

I would like to add a feature where we will be taking or displaying testimonials of people who benefited from this website

### Add ScreenShots

Something like this:
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/129886894/5f505141-af47-462d-b64d-b8503aa8d9dc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chelseasingla1** [comment]
> ### Describe the feature
> I would like to add a feature where we will be taking or displaying testimonials of people who benefited from this website
> 
> ### Add ScreenShots
> Something like this: ![image](https://private-user-images.githubusercontent.com/129886894/330309247-5f505141-af47-462d-b64d-b8503aa8d9dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2Njk3NzEsIm5iZiI6MTcxNTY2OTQ3MSwicGF0aCI6Ii8xMjk4ODY4OTQvMzMwMzA5MjQ3LTVmNTA1MTQxLWFmNDctNDYyZC1iNjRkLWI4NTAzYWE4ZDlkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQwNjUxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGM0YTVmYmNhYTFmNjcwNDU4ZTk0NTBhMGIzMmJjMGJiNmY3ZGM2NWYwNTJkNGQ2Mzc0NzRmYzVjYWVlNjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.l90zP1cXk6l_hPIzbdSRd4KXAaE34VEbQOUL1HFRO7k)
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Please assign me this issue under GSSoC'24.

**Comment by Aradhya-005** [comment]
i would like to work on this. Please assign it to me

**Comment by Suchitra-Sahoo** [comment]
This feature is not required
