### ISSUE TITLE
Feat: Adding surveys to make it more interactive

### ISSUE THREAD

**Issue by Chelseasingla1** [Suchitra-Sahoo/AgriLearnNetwork#279]
### Describe the feature

I would like to add a feature where new users could do some surveys it will make website more interactive.

### Add ScreenShots

Like this:
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/129886894/ea97ff52-5a28-4966-b503-e6b16d1f98cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Chelseasingla1** [comment]
Please assign me this issue under GSSoC'24

**Comment by supriyabharane** [comment]
I would  Like to work on this. Please assign this issue to me

**Comment by niteshbca** [comment]
@Chelseasingla1 Please assign to me task and solve the problem.

**Comment by Suchitra-Sahoo** [comment]
This feature is not required
