### ISSUE TITLE
Changing the logo of Twitter icon

### ISSUE THREAD

**Issue by TBorundia** [Suchitra-Sahoo/AgriLearnNetwork#284]
As twitter logo has changed. I want to work on this issue to update it to new logo.
please assign this issue to me under GSSoC'24
![Screenshot 2024-05-14 132022](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/168854094/17c883c8-3c11-4e2d-8532-88ecd56158e2)

New logo is 
![Screenshot 2024-05-14 131642](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/168854094/aa30bd7b-38b3-4d43-85e3-99e4d57bc704)

**Comment by shrutisachan08** [comment]
@Suchitra-Sahoo 
I can successfully update it to new twitter logo and fix the issue.
please assign me this under GSSoC'24 lablel.

**Comment by 20ankur07** [comment]
@Suchitra-Sahoo Please assign this issue to me i can fix it adding the hover feature as well

**Comment by cptainperoxide** [comment]
I would also Like to work on this. Please assign this issue to me

**Comment by supriyabharane** [comment]
I would also Like to work on this. Please assign this issue to me

**Comment by CHITRA2445** [comment]
Hi @Suchitra-Sahoo . I am interested in working in this issue under the  label GSSOC'24

**Comment by niteshbca** [comment]
@TBorundia Please assign to me task and solve the problem.
