### ISSUE TITLE
BUG: Uneven Navbar spacing and distribution

### ISSUE THREAD

**Issue by chhavx1618** [Suchitra-Sahoo/AgriLearnNetwork#285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Navbar has unnecessary spacings, uneven arrangement of icons. Under GSSOC'24, I would like to work on this project and improve this particular feature.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152146397/ea2ef941-6794-4aad-bb02-2803717dc7ad)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by cptainperoxide** [comment]
I would also Like to work on this. Please assign this issue to me

**Comment by supriyabharane** [comment]
I would also Like to work on this. Please assign this issue to me

**Comment by niteshbca** [comment]
@chhavx1618 Please assign to me task and solve the problem.
