### ISSUE TITLE
SUGGESTION: Increase opacity of the text box of main page

### ISSUE THREAD

**Issue by chhavx1618** [Suchitra-Sahoo/AgriLearnNetwork#286]
The text box over the carousel of the main page has very little opacity, making its text difficult to read and comprehend. The opacity should be increased for better readability and visibility. 

Under GSSOC'24, I would like to work on this issue and make improvements to the website's UI.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152146397/24870193-7a96-4777-a7f8-8ab3fa87c103)

**Comment by Harshit7492** [comment]
I am looking to fix this bug if @Suchitra-Sahoo allow me to fix this particular bug

**Comment by Madhav060** [comment]
Hi !! Using my css knowledge would like to fix this issue kindly assign it to me ..
