### ISSUE TITLE
Homepage Image doesn't fit the styling

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#29]
Enhancement request: I would like to change the homepage image with better styling to it.

**Comment by DARSHANITRIPATHI** [comment]
Please assign this task to me

**Comment by Sathya-reddy1658** [comment]
i will add  animations to the homepage and make it look very attractive

**Comment by Abhinavagarwa** [comment]
please assign this to me

**Comment by nishant0708** [comment]
i can fix it

**Comment by vaishnavikarra** [comment]
I am GSSoC '24 contributor please assign me this issue. I will make sure I will resolve it.

**Comment by Mohammed-790** [comment]
Please assign this issue to me I am Beginner just wana experience the first contribution

**Comment by pranav-666** [comment]
I am a GSSoC'24 contributor I request you to please me this issue, I can guarantee you I will resolve this issue

**Comment by sakshiiiii26** [comment]
Hello!! @Suchitra-Sahoo I am a contributor of GSSoC 24 and I would like to design this page in attractive way. So I request you to please assign me this task thankyou!!

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
