### ISSUE TITLE
Fix: Footer image not expanded

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The footer image doesn;t look good, i wish to fix its position

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by supriyabharane** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by CHITRA2445** [comment]
i am interested in working with the issue
