### ISSUE TITLE
BUG: Website scrolling remains enabled despite the feedback form being open.

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [Suchitra-Sahoo/AgriLearnNetwork#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The user is able to scroll the website despite the feedback form being open.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/128472306/7ce05d54-5a32-4fb0-97f7-8e30ba91a07b

<br>
Hello @Suchitra-Sahoo , Please assign this issue to me in gssoc 24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
