### ISSUE TITLE
Feat: Navbar elements are overlapping

### ISSUE THREAD

**Issue by vedanshipathak** [Suchitra-Sahoo/AgriLearnNetwork#296]
### Describe the feature

@Suchitra-Sahoo Currently ,there is a misplacement of navbar elements .The icons and the text are misplaced .I can work on that. Kindly assign me this issue.

### Add ScreenShots

![Screenshot 2024-05-14 210049](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/141757766/7f1f9fef-878e-4f57-ae9c-54a16f254b67)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by cptainperoxide** [comment]
I would also Like to work on this. Please assign this issue to me

**Comment by Tanu2205** [comment]
Can you please assign me this issue?
