### ISSUE TITLE
Feat: Improving the UI effect and Contact us!!

### ISSUE THREAD

**Issue by sshivangi882** [Suchitra-Sahoo/AgriLearnNetwork#297]
### Describe the feature

The navbar and the background color coincide and both look same, and adding features to the contact us section such as grid, box and hover..

### Add ScreenShots

![Screenshot (867)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/122531720/32ea34e8-554b-49e5-b957-c7a7ddac5ef7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akshitha-reddy-13** [comment]
Can you assign it to me? @sshivangi882 @Suchitra-Sahoo 

Full name: Akshitha Reddy
GitHub profile link: [Akshitha-reddy-13](https://github.com/Akshitha-reddy-13)
Email ID: akshithajagan13@gmail.com
Approach for this project: CSS and JavaScript
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, please?
Thanks.

**Comment by Amitesh-Mishra-AM** [comment]
## Can you assign it to me 
### The Contact Us section is not visually appealing, I would like to work on the issue.
### If you like you can assign it to me, so that I can start working on it.

## Thank you

**Comment by Suchitra-Sahoo** [comment]
Explain what kind of changes you will implement.

**Comment by sshivangi882** [comment]
I will make the Contact Us page, look beautiful and since the whole website color is only dark green, I don't think it looks appealing, let me add some color features related to agriculture only and give a proper grid and flexbox and buttons containing hovering effect, etc to the page.

**Comment by Akshitha-reddy-13** [comment]
I will implement changes in the frontend using grid and flex techniques accordingly, make it more attractive, and add some more features to make it interactive for the user, as it is such a basic design. Also, I would like to change the logo design to make it more appealing.

**Comment by Amitesh-Mishra-AM** [comment]
@Suchitra-Sahoo The contact us is getting mixed up with all the other sections, I will change the background color to light green which is also used in the about section, this will make the website look good and more visually appealing. And also the borders and shadow affect of the cards make it look dull.

**Comment by Suchitra-Sahoo** [comment]
Issue is already assigned
