### ISSUE TITLE
BUG :Icons In Footer Section are hidden

### ISSUE THREAD

**Issue by Harshit7492** [Suchitra-Sahoo/AgriLearnNetwork#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# Discription
  - In the footer section there is a bug all the icons are invisible 
## More Features 
  - Also the UI design of this website is dark green which can be converted into RGB color of light green 
 # Screenshot
![Screenshot 2024-05-14 232447](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114082380/7d07c22e-1b67-42b1-98a2-55bfc4e935b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshit7492** [comment]
I am happy to work on this issue if @Suchitra-Sahoo will allow me to solve this issue

**Comment by Suchitra-Sahoo** [comment]
But i can see the icons are visible.
