### ISSUE TITLE
Improve Home Page ( Add Carousel instead of image)

### ISSUE THREAD

**Issue by sarthak-stranger** [Suchitra-Sahoo/AgriLearnNetwork#30]
**Describe the bug**
if we add carousel then home page looks better 
 
**Expected behavior**
UI Looks so simple and ugly.

**Screenshots** 

![Screenshot (211)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/92575432/2a326c1e-5a4c-49b2-93bf-c482b68e9b9b)

**Comment by Swapnita06** [comment]
Please assign this to me . I can work on carousel

**Comment by sarthak-stranger** [comment]
Thank you for assigning this issue to me.

**Comment by sarthak-stranger** [comment]
@Suchitra-Sahoo Can you please give your discord id or something else , so i can discuss you more about the work.

**Comment by Suchitra-Sahoo** [comment]
I guess soon a seperate discord group will be formed for each project.

**Comment by sarthak-stranger** [comment]
@Suchitra-Sahoo Ok

**Comment by sarthak-stranger** [comment]
@Suchitra-Sahoo Hi, why you removed GSSOC24 tag ?

**Comment by sarthak-stranger** [comment]
@Suchitra-Sahoo Please Add GSSOC 24 Tag, i am contributor and also i have started work on your home page.
