### ISSUE TITLE
Feat:Appearance of Navbar

### ISSUE THREAD

**Issue by K-Tikaraya** [Suchitra-Sahoo/AgriLearnNetwork#301]
### Describe the feature

In navbar of website distribution of each component is not correctly done its looking very assymetrical and little bit confusing
I can make it more attractive

### Add ScreenShots

![Screenshot (220)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/165303736/b19f7c5c-051c-4611-91fc-b12b33a63516)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AdhithiManjunath** [comment]
i have tried solving the issue , please look into #302

**Comment by adii9410** [comment]
Please assign me this work so i can fix it with a dynamic layout and i can contribute also

**Comment by AdhithiManjunath** [comment]
Hey @Suchitra-Sahoo , I have made appropriate changes , please do check .

**Comment by vipinmishra0852** [comment]
Hey @Suchitra-Sahoo I want to work on this issue please assign me this issue

**Comment by niteshbca** [comment]
@K-Tikaraya Please assign to me task and solve the problem
