### ISSUE TITLE
[BUG] : Image Responsive Issue

### ISSUE THREAD

**Issue by sivaprasath2004** [Suchitra-Sahoo/AgriLearnNetwork#303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

- In the page `Resource Library` content image can be `mobile` site doesn't proper align.
- In the image align in the `left` i will recomand for the image to the proper alignment to change.
- please assign i will fix the bug issue.. 
- i will ready for work.. :rocket: 

![Screenshot from 2024-05-15 17-46-19](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/121082414/1e6436b2-14f2-49ec-ab21-216aebb683fb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by supriyabharane** [comment]
I Want To Work On This Issue,Please Assing me this

**Comment by Suchitra-Sahoo** [comment]
In what kind of device you are facing this issue as i have just checked and it seems fine.

**Comment by sivaprasath2004** [comment]
@Suchitra-Sahoo please switch to responsive mode and check `600 to 700` image not proper in the center of the page..

**Comment by niteshbca** [comment]
@sivaprasath2004 Please assign to me task and solve the problem.
