### ISSUE TITLE
Feat: Contact us Section's UI is not looking Good

### ISSUE THREAD

**Issue by Ujjwal807** [Suchitra-Sahoo/AgriLearnNetwork#304]
### Describe the feature

The contact us section is not looking Good, We should change its style so I can improve its UI kindly Assign me so I can make this into a modern UI.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/121127299/5cefa25a-99ed-4490-bc82-e4c393cfa770)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Explain how will you improve.

**Comment by Ujjwal807** [comment]
> Explain how will you improve.

I will convert the contact section UI to Modern UI by changing its style to Glassmorphism that will look nice on this website.

**Comment by Suchitra-Sahoo** [comment]
add a reference image

**Comment by Ujjwal807** [comment]
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/121127299/470b5572-b699-4101-95b1-db4622302948)
like this , it is looking like a glass landing page

**Comment by Suchitra-Sahoo** [comment]
But you wanted to work on contact us page so add reference about that only.

**Comment by Ujjwal807** [comment]
> But you wanted to work on contact us page so add reference about that only.

the image that I share is how I change the style of the Contact Us page , how can I share the images for contact us section without styling it
