### ISSUE TITLE
Feat: Addressing Inactive Background Carousel Slideshow in Mobile Mode Transition

### ISSUE THREAD

**Issue by TARUN2K3** [Suchitra-Sahoo/AgriLearnNetwork#306]
### Describe the feature

The website's background carousel fails to slide when switched to mobile mode. This undermines user engagement and detracts from the site's appeal. Fixing this glitch is crucial to ensuring a seamless transition and maintaining a captivating user experience across all devices.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/127468524/a919231e-0a59-473d-8c1f-1a3bab017209)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by supriyagaut** [comment]
i want to work on this please assign to me

**Comment by shamayitadatta** [comment]
i want to work on this please assign to  me
