### ISSUE TITLE
Feat: Make 'Resource Library' cards redirect to respective resources upon clicking on card.

### ISSUE THREAD

**Issue by RanjanaShenoy** [Suchitra-Sahoo/AgriLearnNetwork#309]
### Describe the feature

Currently, in the "resource library", to redirect to videos and resources, we need to click on the link/attachment icon. Only then it redirects. I wanted to improve it in such a way that upon clicking anywhere on card, it should redirect to resource. This improves user experience in 2 ways:
1. User need not make an effort to click only on link/attachment icon to redirect to respective resource. 
2. User can click anywhere on card to redirect. 

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/63968799/93465351-4435-4696-a5a4-3f592dd31d3d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RanjanaShenoy** [comment]
Hi @Suchitra-Sahoo , Please assign this issue to me. I would like to contribute. 
I am GSSOC contributor.

**Comment by CHITRA2445** [comment]
hi @Suchitra-Sahoo . I am interested in working in the issue . Please assign it to me.

**Comment by Suchitra-Sahoo** [comment]
This issue is resolved
