### ISSUE TITLE
Add Slider 

### ISSUE THREAD

**Issue by Sonaliparte** [Suchitra-Sahoo/AgriLearnNetwork#31]
#Description 
I would like to add a slider in the Blogs section.@suchitra-sahoo
want to work on this issue can you please assign it to me.

Screenshots
![slider](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114504015/d9d407fc-940a-4030-867e-ae28f6dcde37)

**Comment by urgetolearn** [comment]
Hey @Suchitra-Sahoo can I please work on this issue

**Comment by Mystery-Shashwat** [comment]
Hey @Suchitra-Sahoo please can I work on this issue

**Comment by Suruchibharti** [comment]
Hii! @Suchitra-Sahoo 
I'm GSSoc'24 contributor, I want to work on this issue,
so, I kindly requested to  assign the task to me.
