### ISSUE TITLE
Typos Error in script.js

### ISSUE THREAD

**Issue by NIKHIL0VERMA** [Suchitra-Sahoo/AgriLearnNetwork#310]
Hey @Suchitra-Sahoo,
I found a typo error in script at line 104 'spped'
I would like to fix this. Please add level and tag under GSSOC'24.
Best Regards,
Nikhil Verma

**Comment by Suchitra-Sahoo** [comment]
can you highlight the errors

**Comment by NIKHIL0VERMA** [comment]
Typing error Script.js

`const typed=new Typed('.multiple-text',{
    strings:['Sow','Learn','Grow' ],
    typeSpeed:100,
    backSpped:100, // this should be backSpeed for better understand 
    backDelay:1000,
    loop:true

});`

**Comment by Suchitra-Sahoo** [comment]
@NIKHIL0VERMA you are assigned.
