### ISSUE TITLE
Feat:Multi-Lingual feature

### ISSUE THREAD

**Issue by keerthitalakoti** [Suchitra-Sahoo/AgriLearnNetwork#311]
### Describe the feature

Generally farmers are not well educated to go through the website and search for the necessary resources.So adding the feature of multi languages where farmer can first easily select their language and go through the website may actually make this project more efficient 

### Add ScreenShots

I could actually work on this for sure if this project is assigned to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
How will you implement this?

**Comment by keerthitalakoti** [comment]
This may be implemented using Weglot Plug-in by configuring this in our
website.Please do assign this to me.
