### ISSUE TITLE
Signup page to track the info of learners

### ISSUE THREAD

**Issue by NamanJain795** [Suchitra-Sahoo/AgriLearnNetwork#317]
### Describe the feature

Hi I am Naman Jain a Gssoc 24 contributor
i think as u have made the content open for all the learners there should be a track of the learners.
The future scope of this is that when there is heavy traffic on your website u can make some paid services and keep track of it.
at time of signup google authentication should also be there. And i can do this.
so hope u will assign me the issue.
please label this issue with gssoc level 3 .
waiting for you response. thank u

**Comment by Suchitra-Sahoo** [comment]
This feature is not required now
