### ISSUE TITLE
BUG: Enhancing the onhover property

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [Suchitra-Sahoo/AgriLearnNetwork#318]
![Screenshot 2024-05-16 124149](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125359008/ee8036ab-1a46-4398-a529-89e40fa08700)

Hey @Suchitra-Sahoo  ...Here when we hove on the container with images (**Resource** **Library**)  when we hover on it property applies for the extra space right to that. This is the issue I found. On solving this we can enhance the UI . Please provide the GSSOC label so that I can work on this issue and fix it

**Record**
 

 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by RiyaRanka** [comment]
Hello, Please assign me this as I am starting my contribution journey of GSSOC'24 and also have done past contribution in open source regarding Frontend Tech Stack.
