### ISSUE TITLE
Adjust Content for Display Within Box

### ISSUE THREAD

**Issue by SaiTejaswaniBikkasani** [Suchitra-Sahoo/AgriLearnNetwork#319]
### Describe the feature

Hey @Suchitra-Sahoo . Ensuring that the content fits within the designated box by adjusting the text size. This issue involves optimizing the display of the content to maintain readability and visual appeal within the given constraints.

In the ScreenShots, there is only for three techniques. I would like to change the content for sowing techniques, irrigation techniques and Climate smart Agriculture also. I want to change the content to precise and upto the point required as shown in the ScrrenShots.

**please assign the gssoc labels and I would like to work on it under GSSOC'24. Thank you!!**

### Add ScreenShots

Before making the changes:

![Screenshot 2024-05-16 135022](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159511364/1ee999ad-1a60-434e-b6f0-d4bd17f7b92c)

After making the changes:

![Screenshot 2024-05-16 134941](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159511364/40d289a4-9a66-469c-afc4-5f939ef97165)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
I have checked just now and the text is within the card only.
