### ISSUE TITLE
Add a Login/SignUp page

### ISSUE THREAD

**Issue by Swapnita06** [Suchitra-Sahoo/AgriLearnNetwork#32]
We can add a login/signup page for this project which will increase the proffesionalism. Please assign me to do it.

**Comment by Nayanika1402** [comment]
I can add a login/signup page for this project.Please assign this task to me

**Comment by Mohammed-790** [comment]
I'm eager to contribute! Could you please assign me this issue under GSSOC 2024

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by Swapnita06** [comment]
@Suchitra-Sahoo Mam as I brought the Login/Sign-up page issue into light above, Please do assign me this under GSSOC'24.

**Comment by Suchitra-Sahoo** [comment]
> We can add a login/signup page for this project which will increase the proffesionalism. Please assign me to do it.

This issue is already being handled by someome.
