### ISSUE TITLE
Enhancement: Increase Navbar Opacity

### ISSUE THREAD

**Issue by Anuragsingh013** [Suchitra-Sahoo/AgriLearnNetwork#322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current opacity of the navbar in the project is not optimal for user experience. Users may find it difficult to read content or navigate the site due to the lack of contrast between the navbar and the background

Proposed Solution:
I propose to increase the opacity of the navbar to improve its visibility while maintaining its aesthetic appeal. By increasing the opacity, we can ensure that the navbar stands out more prominently against various backgrounds, enhancing the overall user experience.

 I have over 2 years of React experience and I'm keen to contribute to the navbar opacity enhancement project for GSoc24. Please consider assigning me to this task. Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@Anuragsingh013 will you able to contribute in styling the about section too? Do let me know then i'll assign.

**Comment by Anuragsingh013** [comment]
> @Anuragsingh013 will you able to contribute in styling the about section too? Do let me know then i'll assign.
Thank you for considering me for the navbar opacity enhancement. I'm certainly willing and able to contribute to styling the about section as well. Please go ahead and assign me to both tasks. I'm eager to get started and contribute to improving the user experience of the project. Thank you!

**Comment by Anuragsingh013** [comment]
> @Anuragsingh013 will you able to contribute in styling the about section too? Do let me know then i'll assign.
Thank you for considering me for the navbar opacity enhancement. I'm certainly willing and able to contribute to styling the about section as well. Please go ahead and assign me to both tasks. I'm eager to get started and contribute to improving the user experience of the project. Thank you!

**Comment by Suchitra-Sahoo** [comment]
Hey I just wanted to update you that now someone is already working on about section so you may contribute in styling of rest of the sections.
