### ISSUE TITLE
Feat: Enhance the Footer

### ISSUE THREAD

**Issue by Sambit-Mondal** [Suchitra-Sahoo/AgriLearnNetwork#323]
### Describe the feature

This will make the footer look better and arranged.

### Add ScreenShots

Right now, the image in the footer doesn't cover the whole footer. I'll make sure the image covers the whole footer, as well as I'll rearrange the Social Media links and Quick links to ensure it looks great.

![Screenshot 2024-05-16 183223](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/138088550/e1215d0f-2bc4-4ee2-a7f3-860f76a99ac8)

Kindly assign me this issue under GSSoC '24.

Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by CHITRA2445** [comment]
Hi @Suchitra-Sahoo . I am interested in working in this issue under the  label GSSOC'24

**Comment by Suchitra-Sahoo** [comment]
Add some images about what kind of changes will you implement

**Comment by Sambit-Mondal** [comment]
Sure mam, on it!

**Comment by Sambit-Mondal** [comment]
This is the basic sample I've created, open to any kind of suggestion from your side to enhance it more.

![Screenshot 2024-05-16 222604](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/138088550/9be3b3e5-1ac3-4a0b-99e5-215e2370c2df)

**Comment by Suchitra-Sahoo** [comment]
But i feel the current one is looking better than this. Go through other websites if you find any feature which is currently not present but can be added you may raise an issue.

**Comment by Sambit-Mondal** [comment]
Okay mam, sure!
