### ISSUE TITLE
BUG: Improve the responsiveness

### ISSUE THREAD

**Issue by Sambit-Mondal** [Suchitra-Sahoo/AgriLearnNetwork#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The responsiveness isn't working properly, as the navbars are getting clumsy, when trying to decrease the screen width.

![Screenshot 2024-05-16 184258](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/138088550/d8eb7f47-1dc6-4495-8368-9f4c6d297823)

Please assign me this issue under GSSoC '24.
Thank you!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aradhyajha** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue please assign me this work
