### ISSUE TITLE
Feat: Enhance the styling and hover experience in Agro Blog cards

### ISSUE THREAD

**Issue by AbhiJay1287** [Suchitra-Sahoo/AgriLearnNetwork#326]
### Describe the feature

I would like to work on Enhancing and implementing the styling and hover experience in Agro Blog cards
will style according to the color theme of the website

### Add ScreenShots

![Screenshot (125)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/105973197/e1d9ae2d-c6fc-426e-b09d-5b687aea4515)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Add some images to see what kind of changes you may implement

**Comment by Suchitra-Sahoo** [comment]
It will be even more better if you can create a seperate blogs page and implement this kthis kind of design.

**Comment by Suchitra-Sahoo** [comment]
Do let me know if you can implement this then i'll assign

**Comment by vaishnavip27** [comment]
Hey @Suchitra-Sahoo  I can work on the enhancement of the page as a designer and a developer. Please assign this issue to me. Looking forward for your approval

**Comment by harshcodesit** [comment]
Hey @Suchitra-Sahoo I can work on the enhancement of the page as a designer and a developer. Please assign this issue to me. Looking forward for your approval

worked on similar projects 
here is a SAMPLE
![Screenshot 2024-05-22 024535](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145207595/48ae2085-1447-4ebd-a4e7-91140107002f)

HOVER:
![Screenshot 2024-05-22 024601](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145207595/b44bd1c8-4f37-4d0a-a4f7-599d39a250a4)
