### ISSUE TITLE
BUG: AgriBoT

### ISSUE THREAD

**Issue by Pujan-sarkar** [Suchitra-Sahoo/AgriLearnNetwork#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image_2024-05-16_202838804](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144250917/5accbac8-206c-4de0-be75-d32f9f07ceb9)
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@Pujan-sarkar you are assigned.

**Comment by Suchitra-Sahoo** [comment]
This issue is resolved
