### ISSUE TITLE
Adding a suitable Logo

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Suchitra-Sahoo/AgriLearnNetwork#33]
**Is your feature request related to a problem? Please describe.**
Adding a suitable logo for AgriLearn throughout the website would help in its overall enhancement.

**Comment by Soumya6Tiwari** [comment]
@Suchitra-Sahoo  kindly assign me this issue under gssoc'24

**Comment by Nayanika1402** [comment]
@Suchitra-Sahoo I would like to really add a nice and meaningful logo to this website which would add to the overall effectiveness and user-friendly nature of this website.Kindly assign me this task.

**Comment by Soumya6Tiwari** [comment]
@Nayanika1402  please create your own issue and work upon it. @Suchitra-Sahoo  kindly assign this issue to me since I created The issue

**Comment by Arpingh** [comment]
@Suchitra-Sahoo kindly assign me this issue

**Comment by sahithinandikula** [comment]
@Suchitra-Sahoo i would like to make changes in   color , font , font weight and other necessary by adding a suitable logo
