### ISSUE TITLE
Feat: Creating a Query and Discussion section

### ISSUE THREAD

**Issue by TanayMaurya84** [Suchitra-Sahoo/AgriLearnNetwork#333]
### Describe the feature

There should be a section in the site where farmers can post queries regarding new technologies, new government schemes, etc.,
This is keep them updated about new trends in the agriculture industry.
So, I want to work for this issue.

### Add ScreenShots

![Blog_Agri](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/128279252/22f57e6f-50d6-457c-851d-049269b12ed4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
How will you implement this?

**Comment by TanayMaurya84** [comment]
@Suchitra-Sahoo 
Since, the platform is currently static, we need to make it dynamic by:
1) Setting up server for posting queries & replies, and retrieving all the queries
2)  Database to store username & password of user, and queries asked by the user
