### ISSUE TITLE
adding a scroll back to top button

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Suchitra-Sahoo/AgriLearnNetwork#338]
### Describe the feature

adding a scroll back to top button on the bottom right of the website , by clicking on which it will take to the home page of the website.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/117037441/0acae0d2-db62-4155-b2a5-c9c9ae058669)

something like this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It is already present.
