### ISSUE TITLE
Feat:Home page is undecorative and does not have any footer

### ISSUE THREAD

**Issue by gopalepic** [Suchitra-Sahoo/AgriLearnNetwork#339]
### Describe the feature

I would like to add footer and 
I make some changes on the frontend bach so that it can have dynamic scrolling like a video

### Add ScreenShots

as like every website , yours website will have a decorative attractive home page 

added enhancement : adding a footer

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
People are already assigned for home page. Are you willing to work to improve background of sections below about us?

**Comment by gopalepic** [comment]
if you need that , i am willing to put all of my efforts to make it attractive and beautiful

**Comment by gopalepic** [comment]
if you have want me to redesign in a way you want , just let me know your type for the designs , assign the task under GSSOC 2024 and I am ready to go !!

**Comment by Suchitra-Sahoo** [comment]
But footer is already present. Recently the home and about section are also updates. So please explain what additional changes you may contribute?

**Comment by gopalepic** [comment]
![Screenshot 2024-05-18 100346](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145182240/a7f29916-85a2-4588-bc62-33d7dbe08a79)
1)The content on home page is great but a little bit blurry 
2)The blogs section have some card displayed over there , there height is a bit too much , make them a bit shoter leads to more beautiful blog section 

other than that , footer is good 

if you want, I can work on this and show some samples to you , if you find that good , then merge the PR

**Comment by gopalepic** [comment]
Raised a PR @Suchitra-Sahoo  , the problems i mentions to you , are solved now , 

1) I solved the home page text problem , it really looks beautiful
2) I Solved the Blog Card height issue , now it looks neat
just check the PR and screen shots 
![Screenshot 2024-05-18 183957](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145182240/9915cef9-be41-4810-9790-0dde0bb00156)
![Screenshot 2024-05-18 184049](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145182240/9d4f9d7f-9bed-48ff-9974-0e838b0c052d)
