### ISSUE TITLE
Adding Icons on the navbar

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Suchitra-Sahoo/AgriLearnNetwork#34]
**Is your feature request related to a problem? Please describe.**
Adding suitable icons on the navbar  for different sections such as home about us , etc would help in enhancing the website

**Comment by harshmishra19** [comment]
I can add icons to the navbar according to the website 
Can you please assign me this issue under GSSOC'24

**Comment by Soumya6Tiwari** [comment]
@Suchitra-Sahoo  since I have created the issue kindly assign it to me Under Gssoc'24

**Comment by Mohammed-790** [comment]
Please assign this issue to me it will be a great pleasure i will give my best

**Comment by pranav-666** [comment]
I can resolve this issue according to your needs and also design it with respect your website under GSSoC'24

**Comment by Suchitra-Sahoo** [comment]
@Soumya6Tiwari assigned. You may start working on it.

**Comment by Soumya6Tiwari** [comment]
@Suchitra-Sahoo  Thanku , I will start working on it
