### ISSUE TITLE
add logo before title bar

### ISSUE THREAD

**Issue by shuhaki** [Suchitra-Sahoo/AgriLearnNetwork#340]
### Describe the feature

step1. make a logo realted to this website by UI/UX.
step2. add in title bar

please assign me i want to do...

### Add ScreenShots

n

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shuhaki** [comment]
please assign me, i want to do..

**Comment by newcodergit** [comment]
Please assign me this issue under gssoc'24.

**Comment by Suchitra-Sahoo** [comment]
Its already present
