### ISSUE TITLE
Feat: making scroll to top feature button sticky

### ISSUE THREAD

**Issue by reshamsai150** [Suchitra-Sahoo/AgriLearnNetwork#343]
### Describe the feature

A sticky scroll-to-top button is always visible as the user scrolls down the page
On lengthy pages, a sticky button ensures users don’t have to scroll up to find the button.
Assign this issue to me @Suchitra-Sahoo 

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/164533685/7e9754f2-c6f2-41dc-b5e3-fa6d94b656a9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Utkarsh7368** [comment]
Please assign this issue to me. I'm Contributor at GSSOC'24

**Comment by Suchitra-Sahoo** [comment]
Where are you plaaning to place it?

**Comment by reshamsai150** [comment]
I will make it sticky it will be available through the page @Suchitra-Sahoo

**Comment by reshamsai150** [comment]
Assign the level label also @Suchitra-Sahoo
