### ISSUE TITLE
Feat: Fully working Contact Us form

### ISSUE THREAD

**Issue by Pujan-sarkar** [Suchitra-Sahoo/AgriLearnNetwork#344]
### Describe the feature

I will try to make the contact us form fully working that if anyone try to contact by this form , so they can do it . By using SmtpJS the data will go form user mail to admin gmail. It will be a great feature for this website.

### Add ScreenShots

![image_2024-05-17_091107286](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144250917/b2a906f7-e55e-4151-a184-8a5809361c71)

@Suchitra-Sahoo  so please can you assign this issue to me , i will try my best to contribute.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pujan-sarkar** [comment]
@Suchitra-Sahoo  please mention the level lable for this issue

**Comment by Suchitra-Sahoo** [comment]
Level label will be added after you solve the issue by raising PR and once your PR is merged.

**Comment by Pujan-sarkar** [comment]
@Suchitra-Sahoo can you provide me any gmail id , in which i will send the data....

**Comment by Suchitra-Sahoo** [comment]
Which data are you taling about?

**Comment by Pujan-sarkar** [comment]
@Suchitra-Sahoo i am talking about the data which you will get from the feedback from... For that i want an official email or something.
