### ISSUE TITLE
DOC: Enhancing readme.md

### ISSUE THREAD

**Issue by AnushkaJainFirst** [Suchitra-Sahoo/AgriLearnNetwork#345]
### What's wrong with the existing documentation

<img width="535" alt="agri-12" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142675883/683cecfc-7ba9-4a05-babf-68b0bb0453e0">

@Suchitra-Sahoo ...Can I left-align the content of let's get started in order to bring all the pts starting from same position in order to enhance readme.md

<img width="536" alt="agri-13" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142675883/86c412a3-7f9d-44b6-b6d8-120a52fabc00">

Also highlighting the sub-headings of key features to improve readability.

### Add ScreenShots

<img width="502" alt="agri-14" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142675883/86f73ade-b046-4f4c-9663-0428c98c761e">
<img width="502" alt="agri-15" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142675883/41168ebd-4487-43a5-82b7-df20179434c0">

OR
<img width="533" alt="agri-16" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142675883/3d90c0fe-a4d5-4519-a106-7295a0a672ba">

Changes will look like this!(Whichever suits you more in key-features, kindly tell!)

If you find them applicable, kindly assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Do these changes under the same issue number #63

**Comment by AnushkaJainFirst** [comment]
Ok @Suchitra-Sahoo ...In key-features, which one is better, centre or left-aligned in the ss above?

**Comment by AnushkaJainFirst** [comment]
PR done under issue no #63
Kindly review @Suchitra-Sahoo
