### ISSUE TITLE
BUG:Follow us on our socials: is not properly alligned

### ISSUE THREAD

**Issue by ChethanaPotukanam** [Suchitra-Sahoo/AgriLearnNetwork#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In contact page Follow us on our socials: is not properly alligned.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ChethanaPotukanam** [comment]
I want to work on this issue please assign this issue to me and also please add labels like gssoc  and level 1.

**Comment by Suchitra-Sahoo** [comment]
But I just checked and it seems properly alligned.
