### ISSUE TITLE
Feat: FAQ Page 

### ISSUE THREAD

**Issue by paulkrishanu4** [Suchitra-Sahoo/AgriLearnNetwork#350]
### Describe the feature

this site should have a FAQ page link to navbar that contains all the information about basics of agriculture and farming

### Add ScreenShots

content should be like this:

![Screenshot_17-5-2024_133153_www tractorjunction com](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/169196836/3b03d15a-db84-4b86-8b3a-b38a5eb10b06)

style like this:

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/169196836/84611ab8-ae5c-4b31-9429-c5e92340e9df

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
These kind of questions can be answered by chatbot too. So this feature is not required.
