### ISSUE TITLE
Feat: Implement Hover Effect for Footer Links

### ISSUE THREAD

**Issue by thevijayshankersharma** [Suchitra-Sahoo/AgriLearnNetwork#351]
### Describe the feature

This feature involves adding a hover effect to the links present in the footer of our website. The footer currently contains the following links:

Home
About Us
Blogs
Resource Library
Contact Us

### Add ScreenShots

Once assigned I will share the screenshot of hovering effect.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Siddhi561** [comment]
Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.

**Comment by Suchitra-Sahoo** [comment]
This feature is not required.
