### ISSUE TITLE
Feat: Footer not taking up full width, emply space on right side

### ISSUE THREAD

**Issue by Shelbybosss** [Suchitra-Sahoo/AgriLearnNetwork#353]
### Describe the feature

Footer not taking up full width, emply space on right side

### Add ScreenShots

![footer2](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/102911609/d9632a79-237e-4561-859b-4fe3ffa6bd7d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shelbybosss** [comment]
@sanmarg Assign me this issue, I will also improve the UI of footer which will make it a better UI

**Comment by Siddhi561** [comment]
Hey, can you please assign me this issue if it is not solved? This is my first time making an open-source contribution, and I really want to showcase my skills. I am very familiar with languages like Java, HTML, CSS, and JS. Apart from coding, I'm an ux/ui freelancer as well.

**Comment by Suchitra-Sahoo** [comment]
Its because of the slider present.

**Comment by Shelbybosss** [comment]
Nope. Anyways leave it
