### ISSUE TITLE
Elements disappear as we scroll down.

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Suchitra-Sahoo/AgriLearnNetwork#354]
As we scroll down the website starting from the resource library section the elements start disappearing from above. Looking for a contributor who may resolve this issue.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123376847/e26e1877-049b-4933-a8bd-994833023aff

**Comment by shreyasupe35** [comment]
hi @Suchitra-Sahoo ,I am insterested to solve this issuse ,please assign me the issuse
