### ISSUE TITLE
Animating the HEADER section 

### ISSUE THREAD

**Issue by anshgautam-github** [Suchitra-Sahoo/AgriLearnNetwork#36]
**Is your feature request related to a problem? Please describe.**
In the project, the header portion is quite simple, I can do some animations in the header section to make it look more appealing.

**Describe the solution you'd like**
By using the GSAP library , I can achieve the required animations.

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?
TO make it look  more nicer!!

**Comment by Suchitra-Sahoo** [comment]
@anshgautam-github assigned. You may start working on it.

**Comment by anshgautam-github** [comment]
@Suchitra-Sahoo    Thanks for assigning me, I would like to know, there are some issues where I have been assigned the level also but here I couldn't see it.

**Comment by Suchitra-Sahoo** [comment]
@anshgautam-github mention your issue number and your PR number. I'll check whether I have merged your PR or not and add label accordingly.
