### ISSUE TITLE
BUG: Content Overflowing in Cards in 'AgroBlogs' section

### ISSUE THREAD

**Issue by divyalaldinani** [Suchitra-Sahoo/AgriLearnNetwork#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/82147067/977ba811-9a05-42c9-b551-1de1e4fc4bce)

Clearly the content here is overflowing, so should i increase the height of card or decrease the text-content of card

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
