### ISSUE TITLE
Feat: Adding home page link to title

### ISSUE THREAD

**Issue by harinisayani** [Suchitra-Sahoo/AgriLearnNetwork#363]
### Describe the feature

I want to add link to title.
So whenever the title is clicked it moves to the home page.
Please assign me this task.

### Add ScreenShots

![Screenshot (99)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143276011/c5a09e21-9348-468d-aa9d-2617e0571e87)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aditi10113** [comment]
I want to work on this issue.
please assign me this task

**Comment by Suchitra-Sahoo** [comment]
This feature is not required as there is already a home button.
