### ISSUE TITLE
BUG: Invalid Mobile number getting submitted in 'Contact Us' page

### ISSUE THREAD

**Issue by divyalaldinani** [Suchitra-Sahoo/AgriLearnNetwork#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/82147067/991eb034-b0ec-4941-ab55-f9609303a339)

Here, 1 digit mobile number is getting submitted(which is INVALID MOBILE NUMBER), thus need to modify the regex to check for valid mobile number.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@divyalaldinani don't fix the issue only for mobile no but other details too. Also work on submission message which comes after form subission.

**Comment by divyalaldinani** [comment]
alright, gotcha, will be working on it.

**Comment by divyalaldinani** [comment]
hey @Suchitra-Sahoo 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/82147067/582ae408-14f8-462b-bf44-35630945e2bc)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/82147067/b5bd7cc8-3b37-471f-b07e-1a1f1b3b70c0)
are these okay?

**Comment by HimangshuRanjan** [comment]
@Suchitra-Sahoo  I would like to fix this issue. Please do assign me this.
