### ISSUE TITLE
Add PR template

### ISSUE THREAD

**Issue by suhanipaliwal** [Suchitra-Sahoo/AgriLearnNetwork#371]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by Suchitra-Sahoo** [comment]
There is already a PR template so do changes in that itself.

**Comment by sakshiSakshi77** [comment]
@Suchitra-Sahoo hey ,i would like to contribute to this , could u pleaser assign me this task

**Comment by suhanipaliwal** [comment]
Please add the label of appropriate level according to GSSOC guidelines.
