### ISSUE TITLE
BUG: For some medium screen sizes the navbar is not responsive .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Suchitra-Sahoo/AgriLearnNetwork#372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

For screen size approx 1223x695 the navbar is overlapping with the text and not responsive as well .
![Screenshot 2024-05-18 092645](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/118350936/a436fa7d-83d8-4024-bc78-6f6b015fa4ff)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Will you be able to solve the issue in a such a way that the content looks sam for all screen sizes?

**Comment by Ayushmaanagarwal1211** [comment]
Yes i can
