### ISSUE TITLE
Feat:Least optimal SEO

### ISSUE THREAD

**Issue by gopalepic** [Suchitra-Sahoo/AgriLearnNetwork#375]
### Describe the feature

As i was scrolling your website , it take minutes to even load the whole site , I guess you should move you tech stack to React , cause it can help you with whole website speed , I can implement lazy loading and contextAPIs to help your whole website to fastest possible loading 

we both can do this  , my expertise in React 

Can we work together>>??

### Add ScreenShots

Time consuming website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@gopalepic you may start working on it. Make sure you keep pulling changes as everyday various PRs are getting merged. Also keep a note that you don't make any changes in design.

**Comment by gopalepic** [comment]
Thankyou very much @Suchitra-Sahoo for assigning the task , As we both are thinking to shift your project stack to React, it itself a big project , 

instead of rising a PR every day , we both should make a new repo for this ,

Do you agree?

**Comment by Suchitra-Sahoo** [comment]
I think there is a misunderstanding. I thought you want to do this as gssoc'24 contribution. But I can't allow you to make another repository of this project as now its officially listed under gssoc.
