### ISSUE TITLE
Feat: Feedback form enchancing

### ISSUE THREAD

**Issue by harinisayani** [Suchitra-Sahoo/AgriLearnNetwork#377]
### Describe the feature

I want to enhance the feedback form by adding icons to it.
Please assign this task to me.

### Add ScreenShots

![Screenshot (101)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143276011/fd57d6f3-9cf9-4d9a-87e4-39a39b309dbf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Husan7** [comment]
Hello sir I'm Husandeep Singh here GSSOC contributor .  I would like to work on this issue .

BEFORE

![Screenshot 2024-05-18 142843](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162671639/7e9ab0f4-5310-4be4-ba8b-d6ca09658525)

AFTER

![Screenshot 2024-05-16 132432](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162671639/dc8bc3db-e43a-44de-93d4-93d5d6d2f742)
![Screenshot 2024-05-16 132736](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162671639/b1470b37-1518-4961-b8f2-ba322038f4c8)

**Comment by Husan7** [comment]
Hii , @Suchitra-Sahoo please see this Responsive  feedback in both desktop and tablet mode . if you like it then please assign me this issue 
by @Husan7

**Comment by Suchitra-Sahoo** [comment]
Issue already assigned. But can you work on creating a separate page for contact us where the user gets redirected on clicking with proper design and styling as provided by you in sample.
