### ISSUE TITLE
Feat:  Adding a glossary of agricultural terms for quick reference

### ISSUE THREAD

**Issue by Nihita123** [Suchitra-Sahoo/AgriLearnNetwork#378]
### Describe the feature

The Glossary feature can be designed to serve as a quick and easy reference for users to understand common agricultural terms. I would like to add this section under the resource library.
please assign this task to me under GSSOC'24

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/165240257/6a8fbc41-69f0-4a46-b07f-96ca9ad1fe43)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This feature is not required.
