### ISSUE TITLE
BUG: Extra space after footer section 

### ISSUE THREAD

**Issue by Husan7** [Suchitra-Sahoo/AgriLearnNetwork#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[
![Screenshot 2024-05-18 135944](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162671639/251e83e2-4bf3-45d7-a02c-3577bdacf89f)
](url)

please assign this issue to me . I will remove this bug

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Husan7** [comment]
Hello sir I'm Husandeep Singh here GSSOC contributor . plesae assign me this issue i will remove this bug so that AgriLearnNetwork looks more attractive.

**Comment by Suchitra-Sahoo** [comment]
How come you are able to see this extra space. I just checked and I can't scroll after the footer.
