### ISSUE TITLE
Feat: Animation in links of footer section

### ISSUE THREAD

**Issue by Husan7** [Suchitra-Sahoo/AgriLearnNetwork#381]
### Describe the feature

 I would like to animation in links of footer part so trhat AgriLearnNetwork looks more atrractive .

### Add ScreenShots

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162671639/4485043c-bdf9-49c6-98db-a9f27ab78c6b

please assign me this issue .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Husan7** [comment]
SIR,  please assign me this issue

**Comment by Husan7** [comment]
Hii, @Suchitra-Sahoo please see this effect . if you like it then please assign me this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required.
