### ISSUE TITLE
[Feature]: Add Horizontal scroll bar into Blog section

### ISSUE THREAD

**Issue by ujj654** [Suchitra-Sahoo/AgriLearnNetwork#383]
### Describe the feature

Want to add Horizontal scroll bar into the Blog section because it will improve the user experience and it will also improve the UI of the website.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/81877649/5b5fd5c1-114f-491c-9fd1-aa4a4e0b2c49)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ujj654** [comment]
@Suchitra-Sahoo  Please assign this issue to me i want on work on it. #GSSoc'24

**Comment by ujj654** [comment]
@Suchitra-Sahoo 
Before commit the code i forgot to add image file so that it is showing error in the cards.
I want to commit again so that the error could resolve.
should I add arrow in the Blog cards or not ????
before I did add arrow into blog card but it not look so good so I remove it.

**Comment by akilesh1706** [comment]
@ujj654 Can you assign it to me. I'll work as part of gssoc'24
