### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by mehrun171** [Suchitra-Sahoo/AgriLearnNetwork#389]
### Describe the feature

We can enable a option for Light theme as current background is dark it will be dark theme and according to user preference he can switch to light theme.
Please i would like to work on this feature,, So please assign me this task.
Please include the gssoc level2 label

### Add ScreenShots

![Uploading agri.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by rajanarahul93** [comment]
Hi, I'd like to work on this issue as well. If @mehrun171  is not available or if multiple contributors are allowed, please consider assigning this issue to me. Thank you!

I agree to follow this project's Code of Conduct.
I'm a GSSOC'24 contributor.

**Comment by mehrun171** [comment]
Thanks for assigning me the issue...I will solve the issue by tomorrow
surely... pls also do add the GSSoC and level 2 label

Mehrun Shamshi

**Comment by mehrun171** [comment]
I have enabled the light theme and improved the UI of the website...so
please do look at the changes made and please add the level of GSSoC in the
GitHub so that it can count towards my contributions leaderboard.


Mehrun Shamshi

**Comment by Suchitra-Sahoo** [comment]
@mehrun171 mention your PR number so that i can check.

**Comment by Suchitra-Sahoo** [comment]
I have found your PR now.

**Comment by mehrun171** [comment]
Pr number is 428
Mehrun Shamshi
