### ISSUE TITLE
Card issue

### ISSUE THREAD

**Issue by pankaj-bind** [Suchitra-Sahoo/AgriLearnNetwork#39]
**Describe the bug**
Cards given in "Resource Library" do not have border-radius like others.
It is looking quite odd.

**To Reproduce**
1. Go to 'home page'
2. Scroll down to '....'
3. See error

**Expected behavior**
All the cards should have proper border-radius to maintain uniformity.

**Screenshots**
![tg](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/73558583/52a938c1-21d3-4c3f-92b4-6ca6fca31b55)

Desktop (please complete the following information):

OS: Windows 11
Browser Microsoft Edge
Version 124.0.2478.80
Smartphone (please complete the following information):

Additional context
I'm a GSSoC'24 contributor please assign me this work.

**Comment by SrinivasDevolper** [comment]
please assign this issue to me i already solved it and I am ready to add a pull request solved the issue

**Comment by Sudhan22z265** [comment]
I want to contribute under GSSoc'24. Please assign me for this.

**Comment by Sujitmaurya123** [comment]
@Suchitra-Sahoo please assign this issues me
