### ISSUE TITLE
BUG:Date time alignment on blog card

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Issue discussed on oull req #268 
fixed with #369 
![Screenshot 2024-05-18 172851](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146661411/62d1c65e-8c6e-4153-a84f-a3001242cf55)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
I have added your label in your previous PR and issue.

**Comment by sau-mili** [comment]
Can you please add another level label? Similar task in other repo is giving at least one level 2 tag. This is just a request.
