### ISSUE TITLE
BUG: overlapping of text align with image 

### ISSUE THREAD

**Issue by thekirti02** [Suchitra-Sahoo/AgriLearnNetwork#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an overlapping of the image, it hides the text written below the image in the "About AgriLearnNetwork" section.

<img width="950" alt="agrilearnNetwork" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/105008820/c76f42d6-36be-4863-82e4-83d3bf9dd21f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akenji** [comment]
Please assign me this issue, I would like to solve it
