### ISSUE TITLE
Move "Back to Top" Arrow to Side of Screen While Scrolling

### ISSUE THREAD

**Issue by kushalkumar1362** [Suchitra-Sahoo/AgriLearnNetwork#399]
### Description
**Issue:**
The "Back to Top" arrow is currently only visible in the footer section of the website. This placement reduces its usefulness, as users must scroll all the way to the bottom of the page to access it. It would be more user-friendly to have the "Back to Top" arrow appear on the side of the screen while scrolling.

**Steps to Reproduce:**
1. Navigate through any page on the website.
2. Scroll down the page and notice that the "Back to Top" arrow is only visible in the footer section.

**Expected Behavior:**
The "Back to Top" arrow should be visible on the side of the screen as the user scrolls down, allowing for quick access to return to the top of the page.

**Actual Behavior:**
The "Back to Top" arrow is only visible at the bottom of the page.

**Suggested Fix:**
- Implement a floating "Back to Top" arrow that becomes visible on the side of the screen after the user scrolls down a certain distance.
- Ensure the arrow is prominent but does not obstruct other page content.

**Additional Context:**
- This improvement will enhance navigation and user experience by providing a quick and easy way to return to the top of the page without scrolling to the footer.

![Screenshot_20240519-105106.png](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140513098/d049fde8-3377-4468-9700-6db828280d22)

# **_Please Assign this issue to me under gssoc with issue level_**

**Comment by anshupriya12** [comment]
please add the label

**Comment by kushalkumar1362** [comment]
@Suchitra-Sahoo please assign a task you are not active

**Comment by ParthNakum21** [comment]
@Suchitra-Sahoo, Please reply.
