### ISSUE TITLE
Responsiveness Problem

### ISSUE THREAD

**Issue by bibhabasuiitkgp** [Suchitra-Sahoo/AgriLearnNetwork#40]
**Describe the bug**
During mobile/tablet, the text has no gap with borders and there are many other responsive problem

**To Reproduce**

**Expected behavior**
After the changes, the mobile view would be great of the whole website

**Screenshots**
![2](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/122109000/a6042f44-6d8a-47b7-9dc0-eae3b7d09ccc)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari]  Chrome
 - Version [e.g. 22] 11

**Smartphone (please complete the following information):**

**Additional context**
please allow me to contribute under GSSOC'24

**Comment by bibhabasuiitkgp** [comment]
please assign the issue to me

**Comment by SrinivasDevolper** [comment]
please assign the issue to me

**Comment by Ramsey99** [comment]
I want to contribute under GSSoc'24. Please assign me for this.

**Comment by Sudhan22z265** [comment]
I want to contribute under GSSoc'24. Please assign me for this.

**Comment by vansh-attri** [comment]
Hi @Suchitra-Sahoo , If anyone is not working on this issue, Can you please assign it to me?

**Comment by Mohit5Upadhyay** [comment]
I want to work under GSSoC'24. Please assign this task to me  to make the web application responsive  and to make the navbar that is more engaging that will over all enhance the UI/UX.
