### ISSUE TITLE
Improvement of Agro Blogs

### ISSUE THREAD

**Issue by melapuswathi** [Suchitra-Sahoo/AgriLearnNetwork#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Agro blogs section, 
1. There is more space between "climate" and "smart" in "climate smart agriculture". 
2. 4 cards per row is reducing the readability. So, 3 cards per row will be better than this.
3. The heading and content and date are not evenly aligned- varies with each card, we can make it look consistent and even through all the cards. Which will improve user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Hey can you design a separate blog page where the user gets redirected on clicking blog option of navbar.

**Comment by melapuswathi** [comment]
Yes, I can do that!
