### ISSUE TITLE
Improving the ui/ux of the scroll to top button

### ISSUE THREAD

**Issue by Soumya6Tiwari** [Suchitra-Sahoo/AgriLearnNetwork#404]
### Describe the feature

improving the ui/ux of the scroll to top button and making it visible throughout the website , so that the user can even return back to the home page directly from the middle of the website.
@Suchitra-Sahoo kindly assign me this issue

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/117037441/09ac9542-ee24-4693-ba9c-fca534ef4462)
somewhat like this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue already assigned.
