### ISSUE TITLE
BUG:FONT VISIBILITY IN AGRO BLOG

### ISSUE THREAD

**Issue by Nih1tGupta** [Suchitra-Sahoo/AgriLearnNetwork#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Beacuse of Background, text written on  blog  is difficult to read.
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119615342/e787be9e-869b-4f73-9e86-e8561f39fe07)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akuu-27** [comment]
I agree to follow this project's Code of Conduct. I'm a GSSOC'24 contributor. I want to work on this issue. i want to add some styling to font and want to do changes in css

**Comment by Nih1tGupta** [comment]
@Suchitra-Sahoo , please consider this issue.
