### ISSUE TITLE
Feat:  To reduce line height and space in About section

### ISSUE THREAD

**Issue by Prakrati1907** [Suchitra-Sahoo/AgriLearnNetwork#407]
### Describe the feature

in about section the context is wide spread and doesnt look good , will reduce the line height and spacing to make it more attractive and take less space.
@Suchitra-Sahoo please aasign this issue to me

### Add ScreenShots

![Screenshot 2024-05-19 150312](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/120261907/b2cbc80f-925f-4fd2-9710-dd6d84374700)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by abhinavraajput** [comment]
@Suchitra-Sahoo Please assign this issue under GSSOC'24 , i will fix this issue.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
