### ISSUE TITLE
Feat: removing quick links at the bottom

### ISSUE THREAD

**Issue by anushkab2508** [Suchitra-Sahoo/AgriLearnNetwork#408]
### Describe the feature

Quick links are always on the top right header... so I feel like in the footer section we can remove that as it might feel a bit cluttered.

Please assign me this issue @Suchitra-Sahoo 

### Add ScreenShots

![Screenshot (62)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/99462578/766b7d00-ad25-443c-b410-c884e40b5c39)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sanujkumar** [comment]
I will be resolve this issues , please assign to me in this task

**Comment by Suchitra-Sahoo** [comment]
footer issue is already assigned
