### ISSUE TITLE
[Enhancement]: Re-design the Footer

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#411]
I wish to redesign the footer with little addition in details like privacy policy and terms &conditions

**Comment by Akuu-27** [comment]
I agree to follow this project's Code of Conduct. I'm a GSSOC'24 contributor. I want to work on this issue. I want to enhance foot with adding some extra content and styling to font.

**Comment by Akenji** [comment]
can I please get assigned this issue? I want to add some styles

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned.
