### ISSUE TITLE
Feat: Feedback button revamp

### ISSUE THREAD

**Issue by heyyvanshika** [Suchitra-Sahoo/AgriLearnNetwork#413]
### Describe the feature

Feedback button should be highlighted. Currently, it's visibility is next to negligible.  

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162312146/acccb48c-eb4e-45b2-9124-1c505ca7cf29)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akenji** [comment]
please assign me this issue
