### ISSUE TITLE
Feat: Update the image alignment and hover effect on the Resource Cards

### ISSUE THREAD

**Issue by AbhiJay1287** [Suchitra-Sahoo/AgriLearnNetwork#414]
### Describe the feature

The hover effect on the Resource Cards is not right , 
The image of these cards is not set to cover the entire dimension of the Card 

I would like to fix this issue and enhance the look of the cards 

### Add ScreenShots

![Screenshot (138)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/105973197/c0bd8124-f15a-407d-8850-631cdbb27a08)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
But on my side its not visible like that.
