### ISSUE TITLE
BUG: Unneccessary quick links in the footer section

### ISSUE THREAD

**Issue by ASLSwetha** [Suchitra-Sahoo/AgriLearnNetwork#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have found that the quick links section in the footer is unneccesary because navbar is doing the exact same thing
![Screenshot 2024-05-19 225610](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/99135533/1bab6ae6-5e48-475e-98b4-176b1e0b6d3c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akuu-27** [comment]
I agree to follow this project's Code of Conduct. I'm a GSSOC'24 contributor. I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
So how will you improve?

**Comment by Akuu-27** [comment]
We can improve it by side it all quick links in 1 section and create another 2 sections for address and contact number. so that in foot it will be 3 section like left, right, middle.

**Comment by niteshbca** [comment]
@ASLSwetha Please assign to me task and solve the problem.
