### ISSUE TITLE
BUG:  Poor alignment of content insid cards of  Agroblogs section 

### ISSUE THREAD

**Issue by prachipatil13** [Suchitra-Sahoo/AgriLearnNetwork#416]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the Agroblogs section, the card content is not aligned properly.the section is not responsive. The card size is much bigger than needed. The date and time on these cards are touching the boundaries, making them not properly visible. This results in a poor look for the website. I can solve this alignment issue and beautify the website. Please assign this issue to me.
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/94395731/f54ef2b3-c865-4234-a4d1-a0ea3be45c87)

#GSSOC'24 #CONTRIBUTOR

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by prachipatil13** [comment]
i want to fix this issue.please assign me to work on it.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
