### ISSUE TITLE
Feat: Navbar dropdown animation in mobile devices

### ISSUE THREAD

**Issue by Sypher0Dronzer** [Suchitra-Sahoo/AgriLearnNetwork#420]
### Describe the feature

I wish to add a dropdown animation when the menu bar is pressed in mobile devices

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/83546205/95b5dbd6-6f6a-4686-af7e-ebdf630c2471)

please assign this issue to me @Suchitra-Sahoo 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Can you explain what exactly you want to do?
