### ISSUE TITLE
Adding Sliders under Resource Library section

### ISSUE THREAD

**Issue by anagha-chaudhari** [Suchitra-Sahoo/AgriLearnNetwork#421]
### Describe the feature

I would love to work on adding the sliders here for the resource library section. Please assign me with this under GSSOC'24

### Add ScreenShots

![agriLearnNetwork](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143149376/80d38663-a7f3-45d2-a74f-4ceaef26625c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Kindly elaborate what exactly you want to apply.
