### ISSUE TITLE
BUG: alignment of navbar elements

### ISSUE THREAD

**Issue by suma30** [Suchitra-Sahoo/AgriLearnNetwork#422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-05-20 132033](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/112741893/7bd04291-cbf5-472d-b2a6-2c816e3d053d)

the elements in navbar are not properly aligned, I can fix this, 
please assign me this issue @Suchitra-Sahoo 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue already assigned.
