### ISSUE TITLE
Feat: addition of icons in footer

### ISSUE THREAD

**Issue by Nihita123** [Suchitra-Sahoo/AgriLearnNetwork#423]
### Describe the feature

Adding icons next to the quick links in the footer of a website can enhance its design and improve user experience.
please assign me this task under GSSOC'24.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/165240257/20f0d429-264e-41c7-a384-25c562c51cd7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by numitasahu** [comment]
I would like to work on this issue so Please assign me

**Comment by Suchitra-Sahoo** [comment]
This is not required.
