### ISSUE TITLE
BUG: change cursor option at logo

### ISSUE THREAD

**Issue by raushankcse** [Suchitra-Sahoo/AgriLearnNetwork#424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

# adding cursor as a pointer at logo will improve the ui for desktop app

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/75777726/23305f8d-02d3-4d59-acb9-3197e2b65588)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shamayitadatta** [comment]
want to contribute please assign me

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
