### ISSUE TITLE
Feat: Light / Dark Mode

### ISSUE THREAD

**Issue by Niyatizzz** [Suchitra-Sahoo/AgriLearnNetwork#425]
### Describe the feature

Hey! I would like to add a feature of the light or dark mode for the website and add this along with an icon for indication on the navbar, this will aim to enhance the UI and make it user-friendly.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145595531/d404a75e-490d-4907-91fc-f75cb3e2cdb9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ParthNakum21** [comment]
Hello @Suchitra-Sahoo, I'm interested in contributing to the project by adding theme button (dark/light). Could you please assign this task to me?

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by gundellyvamshiyadav** [comment]
I would like to work on this issue under gssoc'24.Please assign it to me.
