### ISSUE TITLE
BUG: change the blog content

### ISSUE THREAD

**Issue by usharani222** [Suchitra-Sahoo/AgriLearnNetwork#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the blog content in the blog section is conjusted i want to make it as you have provided in the design
<img width="960" alt="Screenshot 2024-05-20 192900" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126246565/add7b94c-5550-4e78-b679-aa13cf132634">

i want to fix this issue under gssoc
Can you assign it to me?
Full name: Usha Rani
GitHub profile link: https://github.com/usharani222
Email ID: [usha78633@gmail.com](mailto:usha78633@gmail.com)
linkedin: https://www.linkedin.com/in/usha-rani-a26098264/
What is your participant role?: GSSoC-2024 contributor

Can you add the label for GSSoC, please?
Thanks.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Can you create a separaate blog page and write your own blogs as currently its just linked to various blogs on internet.

**Comment by usharani222** [comment]
Yes sir i will work on that
Assign me this issue

**Comment by Suchitra-Sahoo** [comment]
@usharani222 you are assigned.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
