### ISSUE TITLE
BUG: Fixing "scroll to top" arrow on the screen

### ISSUE THREAD

**Issue by bhumika-1127** [Suchitra-Sahoo/AgriLearnNetwork#429]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo I want to fix this issue under GSSOC'24. Kindly assign me this issue.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/137604220/15e8a4e7-3621-4002-bc75-7ca69b8e48a0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue already assigned.
