### ISSUE TITLE
Make UI better to 

### ISSUE THREAD

**Issue by sarcaxticlarka** [Suchitra-Sahoo/AgriLearnNetwork#43]
Can we make ui more better to enhance user experiment..! we can take inspiration of agriculture design inspiration from Pinterest dribble and form more  platform like this...

**Comment by aditi1807** [comment]
Hey,
I am  an aspiring developer can you please assign me this issue

**Comment by Mohammed-790** [comment]
I'm eager to contribute! Could you please assign me this issue under GSSOC 2024

**Comment by ivarcodes** [comment]
Hi mam, i would love to contribute on this project

**Comment by kanikaa-3018** [comment]
please assign this issue to me for GSSoc'24, i have experience with ui and design, keeping all the aesthetics

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned to someone.
