### ISSUE TITLE
BUG: Alignment issue

### ISSUE THREAD

**Issue by bhumika-1127** [Suchitra-Sahoo/AgriLearnNetwork#430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to add margin to make the "time" inside the block. @Suchitra-Sahoo kindly assign me this issue.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/137604220/5a0d8e7d-7d62-4b14-a30f-d7faf3bf7775)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akenji** [comment]
can I please also get assigned this issue?

**Comment by bhumika-1127** [comment]
@Suchitra-Sahoo Let me know if you need help regarding this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned.
