### ISSUE TITLE
BUG:Isolated Hover Effect on Blog Sections.

### ISSUE THREAD

**Issue by tanya-54** [Suchitra-Sahoo/AgriLearnNetwork#432]
### Describe the feature

The current implementation of the hover effect on the blog sections within the blog container causes all blog sections to slightly increase in size when the cursor hovers over any one of them. This is not the desired behavior. The enhancement request is to modify the hover effect so that only the individual blog section under the cursor will increase in size, providing a more intuitive and user-friendly experience.

Expected Behavior:
When a user hovers over a blog item, only that specific item should increase in size. Other blog items should remain unaffected by this interaction.

Current Behavior:
Hovering over a single blog item causes all blog items in the blog container to increase in size slightly.

### Add ScreenShots

![Uploading Screenshot 2024-05-20 223525.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

i want to correct this feature . @suchitra-Sahoo, please assign me this issue.

**Comment by nancyvaryani** [comment]
Hey @Suchitra-Sahoo , I can work on this. Can you please assign me the issue

**Comment by Akenji** [comment]
can you please assign me this issue?

**Comment by vaishnavip27** [comment]
hey can you assign me this issue?
