### ISSUE TITLE
BUG:Missing Hover Highlight on Navbar Dropdown in Mobile View

### ISSUE THREAD

**Issue by tanya-54** [Suchitra-Sahoo/AgriLearnNetwork#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

On applying different dimensions, such as viewing the website on an iPhone Pro, the upper navbar dropdown menu containing items like Home, About, Blogs, etc., does not display a highlight or hover effect when interacted with. This is a feature bug as it affects the visual feedback and user experience on mobile devices.

Description:
When the website is accessed on mobile devices, particularly in responsive view dimensions like that of an iPhone Pro, the navbar dropdown menu items do not show any highlight or hover effect when hovered or tapped. This lack of visual feedback can lead to a poor user experience as users might not get a clear indication of which menu item they are interacting with.

Expected Behavior:
When a user taps or hovers over a navbar dropdown menu item in mobile view, the item should be highlighted or display a hover effect, providing clear visual feedback to the user.

Current Behavior:
Currently, there is no highlight or hover effect when interacting with the navbar dropdown menu items in mobile view, making it difficult for users to know which item they are about to select.

Impact:
Improving the hover and active state feedback for navbar dropdown items on mobile devices will enhance the user experience by providing clear and immediate visual feedback during navigation. This will make the website more intuitive and user-friendly across all devices.

Submitted by:@tanya-54 
Project: AgriLearnNetwork
GSSoC 2024 Participant

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Akuu-27** [comment]
I agree to follow this project's Code of Conduct. I'm a GSSOC'24 contributor. I want to work on this issue
