### ISSUE TITLE
Footer styling should be improved

### ISSUE THREAD

**Issue by vanisharma2003** [Suchitra-Sahoo/AgriLearnNetwork#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Footer styling is not up to the mark. Some changes are to be so that it's UI can improve. For the change we can change  alignment of font content and should also change it's font styling.
![agrilearn](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/137780818/79cdbe1d-0e2f-46ff-b908-043b02af523f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Explain how will you improve.

**Comment by vanisharma2003** [comment]
See all the footer content present now is in row format and their styling is also normal.
To made website look professional we can place these content in column with proper styling, margin, padding etc. This will enhance overall look of the website.
I have experience of working in front end and also I have contributed to various projects in GSSOC.
I will do this task in given time frame.
Thanks and regards

**Comment by GSGore** [comment]
can you please assign me the issue ?

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
