### ISSUE TITLE
Feat: Improve Contact form

### ISSUE THREAD

**Issue by riffhi** [Suchitra-Sahoo/AgriLearnNetwork#436]
### Describe the feature

i want to improve the contact form

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/111896909/8d3051a8-c74c-4a0a-972c-6ae7a29a2c40)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by bilalshahid707** [comment]
Can you please assign me this issue?

**Comment by Suchitra-Sahoo** [comment]
@riffhi I want you to create a separate contact page.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by harshcodesit** [comment]
Hey @Suchitra-Sahoo 
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .

**Comment by RohanDable** [comment]
assign me i will fix it quickly
