### ISSUE TITLE
Feat: Add smooth scrolling transitions and integrate Tailwind CSS and node

### ISSUE THREAD

**Issue by Mujtabaa07** [Suchitra-Sahoo/AgriLearnNetwork#438]
### Describe the feature

I'll enhance the user experience on our website by adding smooth scrolling transitions and integrating Tailwind CSS for consistent styling. This will improve both the aesthetic and functional aspects of the site.
And I'll add new features .
And I'll Improve Footer design.
I'll be happy to reslove it asap.

### Add ScreenShots

[
![Screenshot 2024-05-21 164726](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/70109255/4fa71ceb-a353-4234-9005-a9f0d48224e9)
![Screenshot agri](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/70109255/e188c0db-bfff-48eb-ab66-fce77f4bfcac)
]

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@Mujtabaa07 you are assigned.
