### ISSUE TITLE
Footer should be better 

### ISSUE THREAD

**Issue by rko0211** [Suchitra-Sahoo/AgriLearnNetwork#440]
### Describe the feature

The current footer can be better in terms of look and for better user experience.

### Add ScreenShots

![footer](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/97402824/fa1615a2-bd90-448d-9138-e88205a96c83)

In this footer it is difficult to use bottom to top  arrow and the alignment of item can be better for better user experience purpose.

Kindly assign me this task under GSSOC24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue already assigned.
