### ISSUE TITLE
Responsive issue 

### ISSUE THREAD

**Issue by rko0211** [Suchitra-Sahoo/AgriLearnNetwork#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

in Mobile device some cards are not align properly . i.e they are not responsive . So kindly assign me this task.
![blog](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/97402824/dd01cfb6-b55c-4ae4-a16a-3eabe8168fc4)

Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by niteshbca** [comment]
@rko0211 Please assign to me task .
