### ISSUE TITLE
BUG: Hover on blog section and scroll top button

### ISSUE THREAD

**Issue by HK853** [Suchitra-Sahoo/AgriLearnNetwork#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Bug
1. Also there is bug in blogs section in your website that is whenever we hover on cards it apply on whole blog section so this cannot be happen in that way.
only apply to particular cards in blog section this can be looks good.

2. scroll top button should be always fixed at bottom right. what if user want to goes on top at middle of page. then top button cannot be shown that's what always fixed at bottom right or left .

So, can you assign me that because i want to contribute in your project.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue already assigned.
