### ISSUE TITLE
BUG: Adding google fonts

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Suchitra-Sahoo/AgriLearnNetwork#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125277258/a8790d09-ec4d-432c-8103-d7462edbcd6b)
the fonts are not looks good in your website

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by niteshbca** [comment]
@RamakrushnaBiswal Please assign to me task.

**Comment by Dhevamuthu** [comment]
I'm a GSSOC'24 contributor
Please assign this issue for me
