### ISSUE TITLE
Feat: Separate Pages

### ISSUE THREAD

**Issue by Prachurya-Ray** [Suchitra-Sahoo/AgriLearnNetwork#447]
### Describe the feature

Separate pages for every modules like About, Blogs etc with tailwind effect.

### Add ScreenShots

<img width="960" alt="image" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/70370699/27a3d923-2ed9-4bfe-bd6a-0a2ee2a97057">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@Prachurya-Ray you are assigned.

**Comment by Prachurya-Ray** [comment]
Thanks. Can you also please add GSSoC Level to it? (Level 1, 2 or 3)

**Comment by Suchitra-Sahoo** [comment]
@Prachurya-Ray level tag is added once you raise a PR and if everthing works fine your PR will be merged and level tag will be added accordingly.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
