### ISSUE TITLE
Feat: Option to add new blogs

### ISSUE THREAD

**Issue by AMANVISHWAKARMA27** [Suchitra-Sahoo/AgriLearnNetwork#448]
### Describe the feature

Below the blogs' div, there should a button that takes us to another page where someone can write a new related blog and submit. This new blog must show up in the blog section.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143862235/f9036441-7295-4ea1-bdd2-7025510047a1)

Here at the side we can add .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

@Suchitra-Sahoo , kindly assign the issue to me.

**Comment by Suchitra-Sahoo** [comment]
@AMANVISHWAKARMA27 you are assigned.
