### ISSUE TITLE
Feat:In Button for adding new resources.

### ISSUE THREAD

**Issue by AMANVISHWAKARMA27** [Suchitra-Sahoo/AgriLearnNetwork#449]
### Describe the feature

There should be a button below the resources option that allows someone to add new resources. Since only videos are available at present, we can allow addition of docs also.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143862235/8e23d78e-a1f4-4670-8f48-66bc2a0ca45a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

@Suchitra-Sahoo , kindly assign the issue to me.

**Comment by shamayitadatta** [comment]
want to contribute please assign me
