### ISSUE TITLE
Convert your project to react js 

### ISSUE THREAD

**Issue by Vishnu1804K** [Suchitra-Sahoo/AgriLearnNetwork#45]
I want to convert your project into react js so that it will be easy for the contributors to implement new features in your wbsite please assign me this issue under GSSOC'24

**Comment by ridhi-ahuja** [comment]
Hello , as a Contributor in GS'SOC 2024 I am looking forward on working and contributing in this project .
I've developed skills in JAVA , C , Javascript ,Python , WEB development and basic Machine Learning ,currently under Artificial Intelligence training on implementing AI tools ,exploring more in tech.

**Comment by Vishnu1804K** [comment]
Hey you raise your own issue it is my issue

**Comment by parth3083** [comment]
Hey I am frontend developer and i make stunning and modern websites in React.js.
I have done internship in frontend developer.
So i have better experience with making the websites in react.
The following are my some works made in react : 
https://ochi-clone-parth.netlify.app/
https://exoape-clone-parth.netlify.app/

**Comment by nakshatravyas** [comment]
Hey, I want to contribute to this project. I am a MERN stack developer and I have worked on several projects and won hackathons as well. I can convert whole project into Reactjs.
Here's my linkedin profile : https://www.linkedin.com/in/nakshatravyas/
Github profile : https://github.com/nakshatravyas

**Comment by Vishnu1804K** [comment]
hey it is my issue you raise your own issue

**Comment by Suchitra-Sahoo** [comment]
Converting the entire project to reactjs is not required right now.
