### ISSUE TITLE
BUG: Date and time is not matching with the blogpost shown in website.

### ISSUE THREAD

**Issue by ShreyaMathur19** [Suchitra-Sahoo/AgriLearnNetwork#450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The date and time which is given at the bottom of the blog is incorrect and is not matching with the correct one as every blog post is showing the same date and time . Hence it may leave negative impact on the user surfing through the website .Please allow me to fix this issue under GSSoC . I can fix it which will enhance the real time experience of the website.
 
 
![Screenshot (138)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145053811/f1a29ebf-fb8e-445a-849b-f52bf9cf9a08)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Personalised blogs are being prepared after which the dates will be updated.
