### ISSUE TITLE
Feat:Enhancing FeedBack form

### ISSUE THREAD

**Issue by kashisharora9462** [Suchitra-Sahoo/AgriLearnNetwork#451]
### Describe the feature

To redesign and enhance the feedback form on your website to create a more visually appealing and user-friendly experience. My goal is to improve user interaction and satisfaction by implementing a modern UI design.Please assign me this task.

### Add ScreenShots

no

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
