### ISSUE TITLE
Better UI and responsiveness of blog 

### ISSUE THREAD

**Issue by divyanshi-sachan** [Suchitra-Sahoo/AgriLearnNetwork#456]
Issue Description:
Currently, when the cursor passes over blog cards in the UI, there is a lack of smoothness and responsiveness, leading to a subpar user experience. Users expect seamless interactions, but the current setup lacks the desired level of engagement and dynamism.

Proposed Solution:
To enhance the blog UI, we propose implementing a hover effect that displays additional details when the cursor passes over the blog cards. This effect will add an element of interactivity and delight for users, providing them with quick access to more information without having to click through to the full blog post. The additional details can include a brief summary, author information, or key points from the post.

To ensure a smooth transition and prevent a jarring user experience, the display of additional details should be accompanied by a subtle animation, such as a fade-in effect or a smooth transition from the card's surface. This animation will create a visually appealing experience that feels responsive and intuitive to users.

By incorporating this hover effect with additional details and animations, we can elevate the user experience of the blog UI, making it more engaging and enjoyable for visitors.

**Comment by niteshbca** [comment]
@divyanshi-sachan Please assign to me task

**Comment by Twisha-coder** [comment]
@divyanshi-sachan please assign this task to me
