### ISSUE TITLE
Update Readme.md DOC:

### ISSUE THREAD

**Issue by Meetjain1** [Suchitra-Sahoo/AgriLearnNetwork#458]
### What's wrong with the existing documentation

small update in readme.md 
we can add animated emojis in place of static emojis to our readme to look it more fascinating and attracting .

![agrilearn](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/133582566/4a8eeb43-f9ab-4746-b633-e2d5f340d6b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Niyatizzz** [comment]
I am willing to contribute to this issue and update the readme, kindly assign me with this issue under gssoc'24

**Comment by nishitasinghhh** [comment]
@Suchitra-Sahoo I am willing to make your Readme more attractive, kindly assign me this issue under GSSoC'24
