### ISSUE TITLE
Feature: Improve the UI of the 'Contact Us' page to enhance its appearance and make it more visually appealing.

### ISSUE THREAD

**Issue by Arnavsao** [Suchitra-Sahoo/AgriLearnNetwork#462]
### Describe the feature

Enhance the 'Contact Us' page with a modern design and intuitive layout. This includes organizing elements neatly, ensuring responsiveness across devices, simplifying form usage with clear labels and validations, maintaining consistent styling, and incorporating engaging visuals. Accessibility features and user feedback mechanisms will also be implemented to ensure a seamless user experience.

### Add ScreenShots

<img width="1710" alt="Screenshot 2024-05-23 at 4 48 11 PM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140349606/54ba5bb3-47d2-450a-a0dc-c48716bf2922">

![contact us page](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140349606/b3d5a95c-8f00-46c3-83eb-f3e62b423472)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.

**Comment by Yatra052** [comment]
Hi i want to work on this part please assign me this task. I'm disable person and highly in need of help. I am UI/UX designer and have good experience over it. Please assign this task to me. I am contributor in GSSOC'24
attaching my email vishwayatra919@gmail.com. Hope so you'll help me

**Comment by Arnavsao** [comment]
<img width="1710" alt="Screenshot 2024-05-25 at 12 23 54 AM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/140349606/e7072579-d154-4997-b009-293e5a51ffee">
Hey Suchitra, I’ve made the changes you asked for. Let me know what you think!

**Comment by Stuti-soni** [comment]
I want to work in this issue. Please assign me this task.
