### ISSUE TITLE
creation of seperate blog page

### ISSUE THREAD

**Issue by Hemav009** [Suchitra-Sahoo/AgriLearnNetwork#463]
### Describe the feature

creation of separate pages for blogs.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/c3ff6674-c65d-4cb9-af47-a7306c078cde)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mahimatestgithub** [comment]
I want to work in this issue. Please assign me this task.
