### ISSUE TITLE
Lacking dark mode in navbar

### ISSUE THREAD

**Issue by Sudhan22z265** [Suchitra-Sahoo/AgriLearnNetwork#47]
**Is your feature request related to a problem? Please describe.**
Users are experiencing discomfort due to the absence of a dark mode option in the navbar. 

**Describe the solution you'd like**
Implement a dark mode feature in the navbar to enhance user experience and provide visual relief, especially during low-light conditions.

**Describe alternatives you've considered**
1. Adding a toggle switch in the navbar to enable/disable dark mode.
2. Automatically switching to dark mode based on system settings or user preferences.
3. Providing a settings option where users can customize their preferred theme, including dark mode for the navbar.

**Additional context**
Consider providing customizable options for dark mode, such as different shades of dark backgrounds or accent colors, to cater to varying user preferences. Additionally, ensure that text and icons are appropriately contrasted for readability in dark mode.

**Comment by Sudhan22z265** [comment]
I want to contribute under GSSoc'24. Please assign me for this. I have experience in mern stack for 2 years

**Comment by krish-san** [comment]
Hello, I'd like to contribute to this issue under GSSoc'24. I've noticed that your website has a nature theme, and I think adding a toggle button in the navigation bar to switch between dark and light modes could enhance its appeal to users. I'm also open to incorporating any additional features you'd like in the navigation bar. Please assign me this issue.

**Comment by SkandSingh** [comment]
Hello, I'd like to contribute under GSSoc'24. I have added dark mode feature in many of my projects. I think I can really add some value to the project.

**Comment by Suchitra-Sahoo** [comment]
@Sudhan22z265 assigned. You may start working on it.

**Comment by Suchitra-Sahoo** [comment]
@sudan are you working on the dark mode feature?
