### ISSUE TITLE
Feat: User login and registration

### ISSUE THREAD

**Issue by Shivani756** [Suchitra-Sahoo/AgriLearnNetwork#473]
### Describe the feature

This feature will enable user to login and register and keep track of their activities om the website .
I want to create a user responsive and user interactive login and signup page which aligns with the attractiveness of the website 
Respected mentor if this issue hasn't been raised yet please assign this to me . I'm willing  to work on this.

### Add ScreenShots

![agro farm](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/139329176/9073848a-86ca-4a76-94ea-8ba4ab37fb14)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Dhevamuthu** [comment]
Please assign this issue for me
under GSSOC 2024

**Comment by Shivani756** [comment]
@Suchitra-Sahoo Hello Ma'am 
Ma'am I would request you to please assign me the issue label
Thank you ma'am

**Comment by litesh1123** [comment]
@Suchitra-Sahoo mam I would like to contribute in this issue @Shivani756 we can collab in this issue if it's OK with you ,i have sent some suggestions we can work on it

**Comment by Shivani756** [comment]
Hello ma'am
I request you to allow @litesh1123 to team up with me and we can work together. ma'am please assign this to @litesh1123 as well so we could incorporate both our ideas

**Comment by Pranaviveeramallu** [comment]
@Suchitra-Sahoo Please assign this issue.Thank You!
Under GSSOC'24

**Comment by Suchitra-Sahoo** [comment]
Sorry but only one person can be assigned a task.
