### ISSUE TITLE
DOC: Adding more info button at the below of the each container in blogs option

### ISSUE THREAD

**Issue by SHANMUGAPRIYA-1** [Suchitra-Sahoo/AgriLearnNetwork#475]
### What's wrong with the existing documentation

There is no specific button to go and refer the information of the content present in blogs in specific. Hence i can add MoreInfo button at the below of the each container so that the user can identify that more brief information is available for ecah topics. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This feature is not required right now.
