### ISSUE TITLE
IMPROVE FEEDBACK BUTTON STYLING AND INCREASE MESSAGE AREA 

### ISSUE THREAD

**Issue by ayushkrrana** [Suchitra-Sahoo/AgriLearnNetwork#479]
### Describe the feature

Change CSS properties to style the feedback button 
Expanded the message area

### Add ScreenShots

before:
![before](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/160728166/42ecfd84-5579-457e-a06e-255bce8fa356)
after:
![after](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/160728166/0097b13b-b28b-490d-a6a5-147de810f31c)
updated:
[
![updated version](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/160728166/2953e443-ea2e-4eef-bf0a-ee4e5538a2d5)

Please Assign it to me 
Thank you @Suchitra-Sahoo 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vaidehi0207** [comment]
I want to work on this project. Please assign it to me.
