### ISSUE TITLE
add logo in title 

### ISSUE THREAD

**Issue by shuhaki** [Suchitra-Sahoo/AgriLearnNetwork#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

**Comment by shuhaki** [comment]
i have very good experience in fronted part, i did some good projects related to fronted so, could you please assaign it to me i will do it

**Comment by krish-san** [comment]
hello , I'd like to contribute to this issue. I have extensive experience in website development, particularly in the area of front-end development.Please assign me on this issue under GSSoc'24

**Comment by GAGGZ1** [comment]
@Suchitra-Sahoo I'd like to suggest incorporating a logo into the project to strengthen its brand identity and improve visual appeal. As a designer with experience in logo creation and integration, I'm excited to contribute to this aspect of the project. Let's work together to craft a memorable and impactful logo that enhances the project's overall aesthetic.

Looking forward to collaborating on this exciting addition!

**Comment by Gauri-Dabhade** [comment]
i would love to work on this project could you plzz assign this task to me

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
