### ISSUE TITLE
Feat: Add Newsletter Subscription Feature

### ISSUE THREAD

**Issue by Srujitha-Raghava** [Suchitra-Sahoo/AgriLearnNetwork#482]
### Describe the feature

The AgriLearnNetwork repository lacks a newsletter subscription feature, which is crucial for keeping users informed about the latest blogs, news, and developments related to agriculture. This feature would greatly enhance user engagement and retention by providing a means for users to opt-in to receive regular updates

### Add ScreenShots

![Screenshot 2024-05-24 161622](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143430142/60944c4d-fbf6-4d37-8579-920ec61a809e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by bhaumik0307** [comment]
i would like to solve this issue

**Comment by Srujitha-Raghava** [comment]
@Suchitra-Sahoo i can work on this issue,kindly assign this to me under gssoc!

**Comment by Suchitra-Sahoo** [comment]
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123376847/e59f9701-250b-423f-b9c0-538d1e1c2152)
Keep quick links on left and newsletter on right and in center copyright

**Comment by Srujitha-Raghava** [comment]
okay

**Comment by Srujitha-Raghava** [comment]
![Screenshot 2024-05-28 121804](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143430142/6f24802f-6949-4723-8e15-0691d3521ab2)


@Suchitra-Sahoo mam, have a look!

**Comment by Srujitha-Raghava** [comment]
![Screenshot 2024-05-29 104700](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143430142/5d3c54bb-05d8-4317-8c82-0b31fd94814a)

How about this ? @Suchitra-Sahoo
