### ISSUE TITLE
Feat: Submit button to disable

### ISSUE THREAD

**Issue by sanyaP19** [Suchitra-Sahoo/AgriLearnNetwork#488]
### Describe the feature

In the contact us section, if the message field is empty, the submit button should be disabled.  The minute data is entered in message field it should be enabled again.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/78594569/64256c18-d4bd-4b6e-aa8c-01cac16e232c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanyaP19** [comment]
Kindly assign this issue to me. 
Thank you!

**Comment by aman7100** [comment]
Can i work on this issue??
