### ISSUE TITLE
add logo

### ISSUE THREAD

**Issue by shuhaki** [Suchitra-Sahoo/AgriLearnNetwork#49]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

What problem is this feature trying to solve?

**Comment by shuhaki** [comment]
please assign me.  i wamt to do

**Comment by anvishelar** [comment]
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by Ishika0-0** [comment]
@Suchitra-Sahoo please assign me this issue under GSSOC'24

**Comment by anuni03** [comment]
![Screenshot 2024-05-10 215614](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/124747628/3346189f-3667-454e-9ed0-3c6d6b009a31)
Right now the logo is an anchor tag would add logo in svg or image format that would hover and expand on clicking.

**Comment by GAGGZ1** [comment]
hey @Suchitra-Sahoo 
I'd like to suggest incorporating a logo into the project to strengthen its brand identity and improve visual appeal. As a designer with experience in logo creation and integration, I'm excited to contribute to this aspect of the project. Let's work together to craft a memorable and impactful logo that enhances the project's overall aesthetic.

Looking forward to collaborating on this exciting addition!

**Comment by Gauri-Dabhade** [comment]
hey @Suchitra-Sahoo  
i would really like to work on this task could you plzz assign this task to me under GSsoc'24

**Comment by chaanakyaaM** [comment]
Hey, @shuhaki , i think adding a Github logo at the footer on the main page makes the website even more better, if any user has any issues or feature requests they could directly inform you.

i would like to solve this, would you assign it to me under GSSOC'24 ??
