### ISSUE TITLE
BUG: In Front page message is not  looking good.

### ISSUE THREAD

**Issue by theeayushkumar** [Suchitra-Sahoo/AgriLearnNetwork#491]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The message not looking good 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/128235540/0536efe0-19cc-4283-b53d-59c09c434859)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Explain about how will you improve?
