### ISSUE TITLE
BUG: Increase card's width in blogs section

### ISSUE THREAD

**Issue by jahnaviyallamelli** [Suchitra-Sahoo/AgriLearnNetwork#492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the cards are very close to each other and width is small it is not looking good need to improve the cards in blogs section.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Blog section is already being handeled by someone.
