### ISSUE TITLE
Feat: Make more responsive navbar

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#498]
### Describe the feature

I wish to make a navbar that becomes sleeks on scroll and thus create a better effect on the overall scroll  animations of the webpage

### Add ScreenShots

I can show it after creating with a videp

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
How will you improve?

**Comment by sau-mili** [comment]
I wish to make it sticky on scroll, and then go back at we scroll back to top
