### ISSUE TITLE
no hover effect to the logo and proper allignment between resource library and cards

### ISSUE THREAD

**Issue by sahithinandikula** [Suchitra-Sahoo/AgriLearnNetwork#50]
I would like to work on this and also add responsiveness to the hero section of the website .

**Comment by kanikaa-3018** [comment]
please assign this to me for GSSoc'24, i  have experience with frontend and can handle this issue

**Comment by Mohit5Upadhyay** [comment]
I want to work under GSSoC'24. Please assign this task to me  to make the web application responsive  and to make the navbar that is more engaging that will over all enhance the UI/UX.

**Comment by sahithinandikula** [comment]
@Suchitra-Sahoo I want to add the hover effect and make a proper alignment ,so I have raised the issue . Kindly assign this issue to me

**Comment by Anu00009** [comment]
Hello , I have done similar type of tasks previously in my projects I want to contribute in GSSOC’24 I request you to please assign this task to me . I assure you that I’ll do it .
