### ISSUE TITLE
BUG: Hover effect is not good

### ISSUE THREAD

**Issue by dhruv8433** [Suchitra-Sahoo/AgriLearnNetwork#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo 

check this out,
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/d546570f-c1da-4410-b09e-4ac4ec1f3361)

when i hover on card it overlap with other cards and also there are very few space between 2 cards

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Issue is resolved.
