### ISSUE TITLE
Feat: Add Detailed page for resource library

### ISSUE THREAD

**Issue by dhruv8433** [Suchitra-Sahoo/AgriLearnNetwork#501]
### Describe the feature

@Suchitra-Sahoo 

insted of rendering youtube video on hover, we can create seperate page for each one with some description, title, method and youtube video

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/8a7e7e51-4dbf-442c-8557-42831d4c1594)

we can create something like this

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/a4a18b4c-997e-4da0-b2ed-c4d72e238341)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Are you saying you want to create separate page for resource library?

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

yes, instead of displaying single component home page we display 3 cards and give one option to see more

when user click on see more we redirect user to `/resource-library` where all cards are listed with description and on that particulr card click we redirect user to youtube video

something like this
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/6f3071fb-9387-4520-b83f-854234ada3ba)

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 

thank you :)

**Comment by dhruv8433** [comment]
@Suchitra-Sahoo 
please add `level` lable in this issue

**Comment by Suchitra-Sahoo** [comment]
> @Suchitra-Sahoo please add `level` lable in this issue

Don't worry it will be added once your PR is merged
