### ISSUE TITLE
BUG: Links at the footer hovering effect can be improved

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Suchitra-Sahoo/AgriLearnNetwork#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Links at the footer hovering effect can be improved. The hovering effect for quick links at the footer looks odd..

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Footer section is already assigned to someone
