### ISSUE TITLE
improve or added some working icon

### ISSUE THREAD

**Issue by shuhaki** [Suchitra-Sahoo/AgriLearnNetwork#506]
### What's wrong with the existing documentation

i want to added movement of icon when clicking

### Add ScreenShots

<img width="1212" alt="Screenshot 2024-05-26 at 1 17 40 PM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145912232/8bc0b195-2188-4b60-bb01-f99da9720369">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GovindSharma0708** [comment]
can u elaborate on the issue i would like to work on it assign it to me

**Comment by Suchitra-Sahoo** [comment]
Blog page has been updated.
