### ISSUE TITLE
DOC: Want to change the logo 

### ISSUE THREAD

**Issue by kavyachandarkar** [Suchitra-Sahoo/AgriLearnNetwork#509]
### What's wrong with the existing documentation

The logo of agriLearnNetwork can be improved as it does not look that attractive , it should be simple but a statement 

### Add ScreenShots

<img width="221" alt="image" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/156076079/8d6ce395-907d-45fe-8945-4ee6761e6692">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
What kind of  logo you are planning to design?
