### ISSUE TITLE
No option to close chatbot

### ISSUE THREAD

**Issue by nisargaa20** [Suchitra-Sahoo/AgriLearnNetwork#51]
![AgriLearnNetwork - Google Chrome 10-05-2024 17_56_39](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125184228/e37192ec-de5f-427f-84f8-8dd4295767d7)

Not able to close chatbot need to refresh the page to close the chatbot

kindly assign me this task #gssoc24

**Comment by DevanshuSinghai** [comment]
hey, actually there is already the same issue which was opened earlier, so i think there is no need to open the same issue once again
