### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Shreesanyog** [Suchitra-Sahoo/AgriLearnNetwork#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a mistake in the spelling of sowing in Sowing Techniques. It is written sowning but it should be sowing.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/166977453/e76171db-73d9-4699-a246-cdf6b1374e2b)

Please assign this to me and please label it as gssoc and the level

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TitikshyaChanda** [comment]
Assign me this under gssoc'24

**Comment by Vaidehi0207** [comment]
I want to work on this project. Please assign it to me.

**Comment by Suchitra-Sahoo** [comment]
Issue is resolved.
