### ISSUE TITLE
Feat: Auto comment 

### ISSUE THREAD

**Issue by MohanRamSridhar** [Suchitra-Sahoo/AgriLearnNetwork#511]
### Describe the feature

- I woiuld like to create a work flow that will *auto comment on opened/closed issue*
- That will *self assign the issue* to a user given he or she has raised the issue 
- I would like to create a *workflow that will auto comment on opened/closed/merged PR*
- I would also enhance your already existing workflow 

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It is not required right now.
