### ISSUE TITLE
BUG: Chatbot Feature is not working well.

### ISSUE THREAD

**Issue by AditiPrabhakar** [Suchitra-Sahoo/AgriLearnNetwork#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Chatbot is not giving appropriate / correct answers.

![Screenshot (108)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/139689410/f8ac257d-7533-4ae3-b64d-948317081d53)

I have worked on this before, i can make it handle corner cases better, and i can improve it's styling, Please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Will you be able to design the chatbot in such a way that it is able to answer all questions related to website as well as how it is currently answering?

**Comment by AditiPrabhakar** [comment]
Yes I can, I'm more familiar with using Botpress, but if you want I can work on Voiceflow too, I have no issues on that. I will need the access to your workflow, so that I can update it and have the data about the website to include.
