### ISSUE TITLE
More Info button Inclusion

### ISSUE THREAD

**Issue by SHANMUGAPRIYA-1** [Suchitra-Sahoo/AgriLearnNetwork#514]
### What's wrong with the existing documentation

I like to place the more info button at the right corner of each container so that the user can use the button to see brief information about it instead of touching the screen and seeing the information

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Can you please explain what you want to do exactly?

**Comment by SHANMUGAPRIYA-1** [comment]
In this project only when the image is clicked the details of the specific
category is displayed instead we can keep a more info button at the down
right corner so that people knew that further information can be read nd
they can know about it more detaily

**Comment by SHANMUGAPRIYA-1** [comment]
I had completed the issue #514
