### ISSUE TITLE
Add effect

### ISSUE THREAD

**Issue by Nikuunj** [Suchitra-Sahoo/AgriLearnNetwork#526]
### Describe the feature

**Type of Issue**
- [x] Bug 🐛
- [x] New Feature 🚀
- [ ] Documentation 📚

---
**Description Issue**

Add a mouse effect when moving the mouse. The effect should be rendered.
I would fix the company logo in the footer so that it is not link.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

@singodiyashubham87 (Please assign me)

**Comment by Suchitra-Sahoo** [comment]
I an unable to understand what you want to create? Can you attach a screenshot from any website to explain.

**Comment by Nikuunj** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/134833235/ac27edf8-be5b-48e7-a136-bba98e4421f4


https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/134833235/935b0393-98cd-4649-9120-61c5dfa01c97

@Suchitra-Sahoo

**Comment by Nikuunj** [comment]
@Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
@Nikuunj try to create something relevant to agriculture

**Comment by Suchitra-Sahoo** [comment]
You are assigned
