### ISSUE TITLE
BUG: Back Top Button above chatbox

### ISSUE THREAD

**Issue by Ankur-Rai-19** [Suchitra-Sahoo/AgriLearnNetwork#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Require changes in the footer section. The "Back to Top" button should be positioned at the top of the chat box to improve its appearance.

![issue to another prject](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125396300/27c4aa19-fd9d-40e5-a2d1-903f50e180de)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Issue is already assigned.
