### ISSUE TITLE
Feat: Ui improvement of Blog cards

### ISSUE THREAD

**Issue by Yashgabani845** [Suchitra-Sahoo/AgriLearnNetwork#528]
### Currently Crads have only single font family and text are not aligned properly
i want to change fonts according to type
like title and blog work have differnet font family and colour and font weight 
Also you can see that time of blog need margin right 
i can imrove design of this cards

and i will make sure that other things will not be affected 

### Add ScreenShots

![Screenshot (141)_LI](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/127788321/a0e8a212-59b1-4ba1-9478-e1b52a0019f9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Yashgabani845** [comment]
@Suchitra-Sahoo  assign me this issue

**Comment by Yashgabani845** [comment]
@Suchitra-Sahoo please look over this issue and assign me if it is needed 
your feedback can give me clarification about this issue please respond
i will respect your feedback thank you

**Comment by Suchitra-Sahoo** [comment]
Sorry for late repy but one of the contributor is already working on it.
