### ISSUE TITLE
BUG: Blogs quick link is not linked with the blogs page

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Suchitra-Sahoo/AgriLearnNetwork#536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/153417476/d0cc8e3f-8bf3-4c39-ae00-4ff7666a4f78)
The quick links (blogs) is not linked with blogs website page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is resolved
