### ISSUE TITLE
BUG: Added hovering effect to quick links in footer

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Suchitra-Sahoo/AgriLearnNetwork#537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/153417476/f9b5268e-b813-4774-891c-51079d47ddd5)
Adding hovering effect to links in quick links in footer

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Abdul-momin24** [comment]
I can add hover effect on the quick links so that become quite user friendly please assign it to me
