### ISSUE TITLE
Improving footer appearance

### ISSUE THREAD

**Issue by krishan-07** [Suchitra-Sahoo/AgriLearnNetwork#544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/164178782/490959d0-36a5-48a3-b422-da966c249c41)
I want to improve the footer to look good on various devices and also enhancing its appearance by doing some changes
Also button to top icon is misaligned in smaller screens

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Issue is already assigned
