### ISSUE TITLE
Feat: Navbar Must be visible in Blog page as well

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#545]
### Describe the feature

Currently The navbar is not present in the blog page, I wish to add it.

### Add ScreenShots

![Screenshot 2024-05-29 103438](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146661411/35a4ff84-f122-401d-8519-e1b3ee1379b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by siddhant-2002** [comment]
please assign it to me i can do it

**Comment by hrishav2004** [comment]
Ma'am I would like to work on the issue, in fact I have also progressed a little bit on this. Please assign this issue to me, I shall try my best to resolve the issue. I'm also attaching an image of the solution I have come up with.
![Uploading Screenshot 2024-05-30 161422.png…]()

**Comment by hrishav2004** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/135991401/78daeef8-77b4-43c8-ae47-2ccd92ec1894



> Ma'am I would like to work on the issue, in fact I have also progressed a little bit on this. Please assign this issue to me, I shall try my best to resolve the issue.

**Comment by sau-mili** [comment]
@hrishav2004   it's assigned to me not you
