### ISSUE TITLE
footer is not added in blog section

### ISSUE THREAD

**Issue by siddhant-2002** [Suchitra-Sahoo/AgriLearnNetwork#546]
### Describe the feature

i want to add footer  in the blog section 

### Add ScreenShots

![Screenshot 2024-05-29 105143](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/112260375/c4af5a2e-a6bc-4525-a8dd-25fc3e2e2b2b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned
