### ISSUE TITLE
IMPROVE FEEDBACK BUTTON STYLING

### ISSUE THREAD

**Issue by ayushkrrana** [Suchitra-Sahoo/AgriLearnNetwork#553]
### Describe the feature

Change CSS properties to style the feedback button 

### Add ScreenShots

Updated:
![new updated](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/160728166/04498fb3-8845-4a62-818e-387153531db8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ayushkrrana** [comment]
I have done the changes as you said earlier and update it
Thank you @Suchitra-Sahoo

**Comment by ayushkrrana** [comment]
Can you please tell me why my pic is not shown in the contribution section @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
@ayushkrrana don't worry it gets updated automatically in every 2-3 days. Also it will not have any impact on your gssoc contribution.

**Comment by ayushkrrana** [comment]
> @ayushkrrana don't worry it gets updated automatically in every 2-3 days. Also it will not have any impact on your gssoc contribution.

Ok thank you

**Comment by ayushkrrana** [comment]
Hello, my name is still not there in the contribution section after it get updated , due to this i did not receive my Pull Shark badge
@Suchitra-Sahoo
