### ISSUE TITLE
Make AgriBot Green

### ISSUE THREAD

**Issue by kashnx** [Suchitra-Sahoo/AgriLearnNetwork#556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to make AgriBot green to match the aesthetics of the website.

Please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required
