### ISSUE TITLE
Feat: Footer UI 

### ISSUE THREAD

**Issue by heli0707** [Suchitra-Sahoo/AgriLearnNetwork#559]
### Describe the feature

Improve the design of the Footer and make it more interactive

Please assign me this task, I will efficiently do it!

### Add ScreenShots

reference footer : 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/95361125/46e7228c-c36c-4f95-8137-e05d078589c1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned
