### ISSUE TITLE
BUG:Add FavIcon in the blogPage and scrollbar is not styled

### ISSUE THREAD

**Issue by Coding-Charvi** [Suchitra-Sahoo/AgriLearnNetwork#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when we redirect to the blog page favIcon is not there also the scrollbar is not styled.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aradhyajha** [comment]
Hello sir @Suchitra-Sahoo 
I'm a GSSOC'24 contributor...i want to work on this issue please assign this task to me..i will complete this task with in one day
