### ISSUE TITLE
BUG: Fixing Navbar in Mobile View

### ISSUE THREAD

**Issue by nandita27iitp** [Suchitra-Sahoo/AgriLearnNetwork#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The navbar in the mobile view is not fixed while scrolling.
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/94813932/43c119ed-2fb2-4e90-8f13-ca94fb7afa19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aradhya-005** [comment]
i would like to work on this issue . Please assign it to me under GSSoC
