### ISSUE TITLE
A whole empty page below footer css issue

### ISSUE THREAD

**Issue by sarthakdevil** [Suchitra-Sahoo/AgriLearnNetwork#57]
![Screenshot 2024-05-10 210348](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/77429824/7a14a1e9-db37-4379-922e-9d4f852a3852)

**Comment by sarthakdevil** [comment]
assign this to me

**Comment by Ayushvishwakarma04** [comment]
Hello! I'd be happy to help with this issue.

**Comment by Suchitra-Sahoo** [comment]
Already assigned to someone.
