### ISSUE TITLE
Feat:Enhanced Search Bar with Dynamic Scroll Positioning 

### ISSUE THREAD

**Issue by coderiksenthil** [Suchitra-Sahoo/AgriLearnNetwork#571]
### Describe the feature

The search bar right now doesn't move when you scroll down, which can block what you're trying to see and makes it hard to find. This change will make the search bar move with you as you scroll, so it's always easy to reach. Plus, you'll be able to hide or show the search bar whenever you want, making it simpler to use. This will work smoothly whether you're on a phone or a computer. 

**Additionally, the code is already prepared and ready for implementation, I kindly request to be assign me to this task of upgrading the search bar on the blog page.**

### Add ScreenShots

Before
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/66522620/6b100bde-55f6-4e32-ad3b-4e576e649e90)
After (ON PC)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/66522620/b35949fb-96ca-4ed6-b2ad-e2c3cdffc0bd)
When you click on Search Bar (ON PC)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/66522620/c5c54659-d68e-4186-9446-af29ba42e928)
When you scroll down (ON PC)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/66522620/f2677e65-f519-440e-9418-b27645540ec1)
After(On Mobile)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/66522620/aa7c568a-3a99-4f24-8453-ede7f1630d4d)
When you Click on Search Bar (On Mobile)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/66522620/73f0c05c-76aa-4e9c-ab4a-b60d6f10e331)
When you Scroll (On Mobile)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/66522620/54bdefd1-45cf-474b-97da-c0b85251b504)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This feature is not required.
