### ISSUE TITLE
Feat: Adding linkedIn link in footer section

### ISSUE THREAD

**Issue by harikasayani** [Suchitra-Sahoo/AgriLearnNetwork#586]
### Describe the feature

I want to add linkedIn link in footer section.

### Add ScreenShots

![Screenshot (136)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143275265/08d51933-9b70-4f6d-be5c-66dc397fb057)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aradhyajha** [comment]
Hello sir @Suchitra-Sahoo 
I'm a GSSOC'24 contributor...i want to work on this issue please assign this task to me..i will complete this task with in one day
