### ISSUE TITLE
Feat: Improving contact us page.

### ISSUE THREAD

**Issue by harinisayani** [Suchitra-Sahoo/AgriLearnNetwork#587]
### Describe the feature

I want to improve contact us page by adding icons and adding more CSS features.

### Add ScreenShots

![Screenshot (8)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143276011/25e54883-6198-4884-ac3c-c4aeb3ec2845)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by LakshmiMansi09** [comment]
Please assign this issue to me under GSSOC 24

**Comment by Ananya-Nair20** [comment]
Hello @Suchitra-Sahoo 

I am participating in GSSOC'24. I am interested in resolving this issue. Please assign this issue to me under GSSOC'24 with appropriate level labels.

Thank you
