### ISSUE TITLE
Feat: Disable Text Selection on Website

### ISSUE THREAD

**Issue by SahilThakur02** [Suchitra-Sahoo/AgriLearnNetwork#589]
### Describe the feature

Prevent text selection on specific elements or the entire webpage using CSS and JavaScript. This enhances content protection by making it harder to copy text while maintaining a seamless user experience.

### Add ScreenShots

<img width="911" alt="Screenshot 2024-05-31 102540" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/112742544/0b37d65d-e4db-43c1-87d7-d61e88923d01">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SahilThakur02** [comment]
@Suchitra-Sahoo /assign me the issue under GSSOC'24 please.

**Comment by Suchitra-Sahoo** [comment]
Sahil this feature is not required currently in the project.
