### ISSUE TITLE
preloader

### ISSUE THREAD

**Issue by gangwarsomya** [Suchitra-Sahoo/AgriLearnNetwork#591]
### Describe the feature

I would like to add a preloader to the site . It would be matching the UI of the site and would be fully responsive . It would render until the page is being loaded . Kindly assign this issue to me under GSSoC'24

### Add ScreenShots

![WhatsApp Image 2024-05-31 at 11 31 45 AM](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123868724/7c5f8c56-88e1-400f-8247-15f93ce094bd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by gangwarsomya** [comment]
@Suchitra-Sahoo please assign this task to me

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
