### ISSUE TITLE
BUG: Change the time in Blogs section

### ISSUE THREAD

**Issue by kashvi9** [Suchitra-Sahoo/AgriLearnNetwork#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### The Time in Blogs needs a change.

Here's a screenshot:
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/169376061/b622484d-4ab5-465d-9dc8-8848b57b5d77)

Instead of this _11 minutes ago_, There should be **2 years ago**.

Hello PA @Suchitra-Sahoo ,
I can change this time period in this page, if you assign me this issue under GSSOC'24.
Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shivathmikavemula** [comment]
I would like to work on the issue
