### ISSUE TITLE
Feat: Adding Login/registration form 

### ISSUE THREAD

**Issue by tanishaprasad** [Suchitra-Sahoo/AgriLearnNetwork#595]
### Describe the feature

I would like to add login/registration form to the website.

### Add ScreenShots

![Screenshot 2024-05-31 115147](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145560431/ad14a5e4-9cb6-4af1-b3c6-ab804f454156)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vaishnavi-jais** [comment]
I’m excited to propose adding a login and registration form to our website—a key feature that will unlock a more personalized user experience! This addition will not only streamline user access but also enhance overall site functionality.

I’d love to take on this task and bring the login/registration process to life. Could you please assign me this project for GSoC '24? I’m eager to get started and help make our website even more user-friendly and engaging!

Thanks for considering my request!
