### ISSUE TITLE
Feat: Show Progress in Scroll to top Button

### ISSUE THREAD

**Issue by zalabhavy** [Suchitra-Sahoo/AgriLearnNetwork#598]
### Describe the feature

I want to add feature that Show Progress in Scroll to top Button that show show much user Scroll down in website gives better user experience.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/33202239-3e9b-4a24-acd0-6e20f01ee8a3)
I will add other round border that show how much you scroll down 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Suchitra-Sahoo please Assign me.

**Comment by Suchitra-Sahoo** [comment]
This feature is not required
