### ISSUE TITLE
Feat:Add Login Page Sign-up And Sign-In

### ISSUE THREAD

**Issue by Mujtabaa07** [Suchitra-Sahoo/AgriLearnNetwork#600]
### Describe the feature

Sign up and Sign in both user login 

### Add ScreenShots

![login before agri ](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/70109255/b6c6e50b-eb41-47c5-b20f-a073030654cd)
I'll Add Login page 
Pls Assign Me I'll Be Happy Do it Asap 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
You will work on both frontendend and backend of sign up/login?

**Comment by Suchitra-Sahoo** [comment]
This issue is assigned

**Comment by Mujtabaa07** [comment]
yes sure

**Comment by Suchitra-Sahoo** [comment]
@Mujtabaa07 I'm saying this issue is already assigned to someone.

**Comment by Mujtabaa07** [comment]
Okay , I’ll find some other issue and resolve it
