### ISSUE TITLE
Feat: Display Reviews of users

### ISSUE THREAD

**Issue by Hemav009** [Suchitra-Sahoo/AgriLearnNetwork#602]
### Describe the feature

create a section of user reviews on the main page.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/0f680c5c-de39-4215-9b87-838723e52dcc)

for sample

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required right now
