### ISSUE TITLE
BUG: Navbar and Footer Absent in Blogs Section 

### ISSUE THREAD

**Issue by aarushi-taori** [Suchitra-Sahoo/AgriLearnNetwork#605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Navbar and Footer Absent in Blogs Section 

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/113369937/44412cbc-7245-4f09-9410-ebf2f077b5b6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aarushi-taori** [comment]
@Suchitra-Sahoo Please assign me this issue

**Comment by shivi028** [comment]
duplicate #603

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned
