### ISSUE TITLE
BUG: Feedback form Errors

### ISSUE THREAD

**Issue by techy4shri** [Suchitra-Sahoo/AgriLearnNetwork#607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

#413 #277 
The feedback form's content are all over the place. There should be an outline/box around the text to clearly show where they are and what space is assigned for what text.
The fields should have flags to determine whether correct value in being given in input: email in email field.
Further, we can just move it towards the side so it is not with the contact me form, like:

![Screenshot 2024-05-31 193448](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/141991095/48d96adc-8e11-487f-93d2-75970316eec2)

It should be like:
![Screenshot 2024-05-31 193448 edit](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/141991095/aa7fbc86-5b59-4296-a2b6-125b0b964441)
![Untitled design](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/141991095/7cf3366b-faaf-43af-93bd-c63b3951d1cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SuchitraSahoo2003** [comment]
I have just checked and on my side its not looking like that.

**Comment by Suchitra-Sahoo** [comment]
But on my side it is looking fine.
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123376847/d5c0d2d9-e7be-4775-b13a-f24e771ea41e)
