### ISSUE TITLE
Improve About section content styling

### ISSUE THREAD

**Issue by AnushkaJainFirst** [Suchitra-Sahoo/AgriLearnNetwork#61]
1) Increasing line-height of the content
2) Changing font as well as highlighting keywords with different color.

Plz assign this issue to me @Suchitra-Sahoo

**Comment by maniranjan2023** [comment]
Hello!! @Suchitra-Sahoo I am a contributor of GSSoC 24 and I would like to design this page in attractive way. So I request you to please assign me this task thankyou!!

**Comment by sonarani1** [comment]
Hello @Suchitra-Sahoo , I am a contributor of GSSoC 2024 and I would like to design this page. Kindly assign this issue to me.

**Comment by sonarani1** [comment]
Hi, Please assign this issue to me.

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Suchitra-Sahoo

**Comment by Suruchibharti** [comment]
Hii! @Suchitra-Sahoo ,
I'm GSSoc'24 contributor, I want to work on this issue,
so, I kindly requested to assign the task to me.

**Comment by Komalpreet-Kaur112** [comment]
Hi @Suchitra-Sahoo 
I would like to work on this issue. 
Please assign me this task.
