### ISSUE TITLE
Feat: add discord icon and hover the quicks link 

### ISSUE THREAD

**Issue by jayanththalla** [Suchitra-Sahoo/AgriLearnNetwork#612]
### Describe the feature

Add discord icon LinkedIn icon , change the quicks style make it hover and add small description about AgriLearnNetwork in footer
please assign me @pa

### Add ScreenShots

![Uploading image.png…]()

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required
