### ISSUE TITLE
Adding a Separate FAQ's Section 

### ISSUE THREAD

**Issue by vinay-reddy31** [Suchitra-Sahoo/AgriLearnNetwork#621]
### Describe the feature

I will add a separate FAQ's Section styling with Footer and navbar

### Add ScreenShots

I understand to raise an issue before Contributing. As this is my first PR in GSSoc. Please Assign me this issue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Issue is already assigned.
