### ISSUE TITLE
year was mentioned wrong

### ISSUE THREAD

**Issue by shivathmikavemula** [Suchitra-Sahoo/AgriLearnNetwork#622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

there was a error in the blog page the year was not mentioned properly
### Screenshot -
![Screenshot (19)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/133566953/6750b648-eaf8-4c85-9318-21fcd1f853f5)

### It should be like this -
![Screenshot (15)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/133566953/668b279f-fef7-40f0-9771-ff0339c7bee6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shivathmikavemula** [comment]
please assign me this @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned

**Comment by shivathmikavemula** [comment]
But the work was not finished yet..
@Suchitra-Sahoo
