### ISSUE TITLE
Feat: enhanced hover effect on navbar links

### ISSUE THREAD

**Issue by Ridhima10** [Suchitra-Sahoo/AgriLearnNetwork#626]
### Describe the feature

I would like to add an enhanced hiver effect on navbar links

### Add ScreenShots

![Screenshot 2024-06-01 145102](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/85826117/0d39d849-5ed9-495c-9d52-63b479f89cf3)
Right no it also changes color. I would like to add some animation to make it more appealing

Kindly assign me this issue
Best regards

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Abdul-momin24** [comment]
can you assign this task to me i can add hover animations on hover on the navbar links

**Comment by Ridhima10** [comment]
@Suchitra-Sahoo  Kindly review this
