### ISSUE TITLE
BUG: Feedback form should be emptied after submit

### ISSUE THREAD

**Issue by Madhu-mac** [Suchitra-Sahoo/AgriLearnNetwork#627]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Once I fill out the feedback form and hit submit, all the fields should be empty. If the filled form and text remain the same after the submission it doesn't look standard. 

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/88281761/41633255-2e92-48cd-9c7e-4c23f4ed4301

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Madhu-mac** [comment]
Hi @Suchitra-Sahoo, - Please add labels and assign this issue to me under GSSOC, Thanks.

**Comment by Suchitra-Sahoo** [comment]
The issue is already resolved
