### ISSUE TITLE
Feat: Redirecting to home page from login and registration page.

### ISSUE THREAD

**Issue by yeolesanskruti** [Suchitra-Sahoo/AgriLearnNetwork#628]
### Describe the feature

If a user wants to return to the home page to recheck details, it does not have any redirecting to the home page.
I want to add this feature to the login and registration page.

Details -
I would like to add a button for this feature.

### Add ScreenShots

Image reference -
![Screenshot 2024-06-01 150707](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/129084275/26d926c0-a3dd-4379-841b-557e6f7ce692)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SheetalDawar** [comment]
I would like to work on this project, please assign it to me
