### ISSUE TITLE
BUG: Extra space at the bottom of AgroBlogs page

### ISSUE THREAD

**Issue by Madhu-mac** [Suchitra-Sahoo/AgriLearnNetwork#630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I scroll all the way down in the AgroBlogs page there is an unwanted extra space. We need to remove it because it doesn't look good at all.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/88281761/95e968d9-12d3-44ad-9cf7-92281d3fb3e8

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Madhu-mac** [comment]
Hi @Suchitra-Sahoo , - Please add labels and assign this issue to me under GSSOC, Thanks.

**Comment by Suchitra-Sahoo** [comment]
But i just checked and everything seems to be fine on my side.
