### ISSUE TITLE
BUG: Search bar in the AgroBlogs page is not standard

### ISSUE THREAD

**Issue by Madhu-mac** [Suchitra-Sahoo/AgriLearnNetwork#631]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no proper spacing to the search bar in the Agroblogs page. Now the icon of search bar looks too big for the page and makes it less attractive to click or use it. If we decrease the search bar icon size a bit and add some padding to it the design will look more promising. 

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/99901964/9042165a-c2ca-49bd-aefd-19ebfaa30002)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Madhu-mac** [comment]
Hi @Suchitra-Sahoo , - Please add labels and assign this issue to me under GSSOC, Thanks.

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned
