### ISSUE TITLE
Feat:Add Style to footer's Quick Links

### ISSUE THREAD

**Issue by zalabhavy** [Suchitra-Sahoo/AgriLearnNetwork#633]
### Describe the feature

I will add CSS to footer's Quick Links for better view and add effects on that.

### Add ScreenShots

I want to make it stylish by adding hover effects and transitions to looks good.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/9f5703a8-6a12-4565-b5fd-226280c74691)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Pratiksha1661** [comment]
I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned
