### ISSUE TITLE
Feature: Adding FAQ section

### ISSUE THREAD

**Issue by Abhigna-arsam** [Suchitra-Sahoo/AgriLearnNetwork#637]
### Describe the feature

 Adding an FAQ section alongside a chatbot enhances user experience by providing quick access to common questions, reducing the chatbot's load, and offering a reliable backup. This allows users to conveniently find answers to frequent queries and manage the FAQ content on a website or application, ultimately improving overall user satisfaction and efficiency.

### Add ScreenShots

I propose to add FAQ section before footer section
![Screenshot 2024-06-01 181608](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125258286/0d52d842-1c3a-492c-9184-60336fb4ce08)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Abhigna-arsam** [comment]
@Suchitra-Sahoo please assign this to me

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned
