### ISSUE TITLE
updating contributing.md file

### ISSUE THREAD

**Issue by mahek0620** [Suchitra-Sahoo/AgriLearnNetwork#638]
### What's wrong with the existing documentation

mentioning Important point to keep in mind before starting 
Commit Message Guidelines using Commitlint
Need some help regarding the basics?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigend
