### ISSUE TITLE
Feedback: padding between Resource Library and portfolio layer

### ISSUE THREAD

**Issue by devlohani99** [Suchitra-Sahoo/AgriLearnNetwork#64]
**Is your feature request related to a problem? Please describe.**
There is no padding between the Resource Library and Portfolio layer 

**Describe the solution you'd like**
I will give padding between them that enhances its appearance.
![Screenshot 2024-05-10 223518](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142163543/a24f1a27-e26d-4d54-b550-d46f3fdbdd96)

**Additional context**
After effect
![Screenshot 2024-05-10 224219](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142163543/a68579c7-560f-4932-bdd1-4ab52fe2e7ce)

**Comment by devlohani99** [comment]
@Suchitra-Sahoo I want to work on this please assign me

**Comment by JainArchit16** [comment]
I want to work on this please assign me under GSSOC24

**Comment by Anou25** [comment]
Hi , I am good at frontend , please can you assign this task to me.

**Comment by Riyasharma28** [comment]
Please assign this issue to me (Riyasharma28) under GSSoC'24.
