### ISSUE TITLE
Feat: Addition of custom cursor

### ISSUE THREAD

**Issue by Anjaliavv51** [Suchitra-Sahoo/AgriLearnNetwork#641]
### Describe the feature

CUstom Cursor to the pointer.

### Add ScreenShots

![Screenshot 2024-06-01 172517](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/154777864/179a6672-d4f1-4e7e-84f7-6fa6890a6cf6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This feature is not required
