### ISSUE TITLE
Feat: Improper UI in quick links sections.

### ISSUE THREAD

**Issue by PrachiJadhav2310** [Suchitra-Sahoo/AgriLearnNetwork#645]
### Describe the feature

In the quick links sections , the home,blogs,etc links are written like normal text. Buttons should be added to it so that it will create an proper UI

### Add ScreenShots

![issue](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/157307149/ab761aab-9448-4b6a-ac6a-3a980df189f9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It is already assigned
