### ISSUE TITLE
acknowledgement and validation in contact us section

### ISSUE THREAD

**Issue by ASLSwetha** [Suchitra-Sahoo/AgriLearnNetwork#65]
**Describe the bug**
I have found that in the contact us section there was no acknowledgement regarding if the message was sent or not, and also before sending there should be a validation whether all the fields are filled or not, it would be more user friendly if you add that and I can definitely help with fixing that issue!

**Comment by pandey079** [comment]
I want to work on this issue, can you please assign it to me.

**Comment by Suchitra-Sahoo** [comment]
@ASLSwetha what's the update?

**Comment by ASLSwetha** [comment]
@Suchitra-Sahoo created a PR by solving this issue #65

**Comment by ASLSwetha** [comment]
@Suchitra-Sahoo before the mobile number actually got trimmed to 10 digits directly which may not give us a accurate or valid mobile number so i have changed that.
