### ISSUE TITLE
BUG:No response

### ISSUE THREAD

**Issue by mehrun171** [Suchitra-Sahoo/AgriLearnNetwork#650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

i had made changes for light mode and made a pr...she didnt accepted my pull request and made me work for her project for literally a week or so...she isnt responding now and i have wasted my time and hardwork...also i didnt get a pr in Leaderboard..what is this...i had wasted my time and didnt get pr accepeted and leaderboard uploaded...this is not fair...please address my issue and look forward in this case,.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@mehrun171 I request you to kindly mention your PR number so that i can check the issue why the level tag is not added. Don't worry if your pr is merged you will surely get a level tag.

**Comment by mehrun171** [comment]
pr number 428
it didnt get uploaded in the leaderboard?

**Comment by mehrun171** [comment]
Ok thq
Mehrun Shamshi
