### ISSUE TITLE
Feat: Improve the Login Page, use abit of animations to make it more responsive!

### ISSUE THREAD

**Issue by thepratham05** [Suchitra-Sahoo/AgriLearnNetwork#651]
### Describe the feature

Add responsiveness to the login page, and make it more visually appealing! Right now it does not look good!

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/135994674/2a62d580-e599-4bb6-ae9c-e33d99ae4538)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
How will you improve?
