### ISSUE TITLE
BUG: Add the Cursor pointer on LOGO 

### ISSUE THREAD

**Issue by Maheshwari-Love** [Suchitra-Sahoo/AgriLearnNetwork#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the cursor point should be there when user move mouse on logo
Currently is not pointer cursor so one cannot know that on clicking the logo he can redirect to home page itself

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@Suchitra-Sahoo Please assign me this issue..

**Comment by zahidalam05** [comment]
Please assign me this issue............
