### ISSUE TITLE
Feat:Availability of different languages

### ISSUE THREAD

**Issue by UdayaNarne** [Suchitra-Sahoo/AgriLearnNetwork#658]
### Describe the feature

Making the website available in different languages,so that everyone can switch the language basing on the language they know

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152365861/b3ad9d9d-c6cb-4002-9a5e-63cef7fed543)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152365861/aedb2be1-ed8a-4da8-bb6c-61a0cd918833)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Issue is already assigned
