### ISSUE TITLE
Update blog time ago with real time

### ISSUE THREAD

**Issue by gungunjain15** [Suchitra-Sahoo/AgriLearnNetwork#659]
### Describe the feature

For reference :- 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125124845/1753d985-5acf-4be4-abc5-8bd0cb8e2a67)

@Suchitra-Sahoo Please assign this issue to me 

### Add ScreenShots

After Changes look like this :- 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125124845/b197bfec-ba58-4d29-adef-73d8be205d15)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned
