### ISSUE TITLE
[feature]: Adding the social media links in the footer

### ISSUE THREAD

**Issue by SougataXdev** [Suchitra-Sahoo/AgriLearnNetwork#66]
**Is your feature request related to a problem? Please describe.**
Adding the social media links in the footer

**Describe the solution you'd like**
i will add social media links in the footer with icons

What problem is this feature trying to solve?
its going to improve the overall customer experience and believe , and aslo promotes your brand

**Comment by SougataXdev** [comment]
@Suchitra-Sahoo please assign this task to me

**Comment by Mohit5Upadhyay** [comment]
I want to work under GSSoC'24. Please assign this task to me  to make the web application responsive  and to make the navbar that is more engaging that will over all enhance the UI/UX.

**Comment by Mohit5Upadhyay** [comment]
I want to work under GSSoC'24. Please assign this task to me  to make the web application responsive and social media links in the footer that will over all enhance the UI/UX.

**Comment by Suchitra-Sahoo** [comment]
Already done by someone.
