### ISSUE TITLE
Feat: Adding a blog about fertilizers

### ISSUE THREAD

**Issue by ayush-848** [Suchitra-Sahoo/AgriLearnNetwork#660]
### Describe the feature

I want to add a fertilizer blog in the blog page

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126975547/ba46dc8e-61a9-40ae-b117-1c03bc026bb5)

I want to add this page as a blog

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It is not required right now
