### ISSUE TITLE
BUG: Adding styles and hovering effect to the Give feedback , back to top and chat icon

### ISSUE THREAD

**Issue by SuhainaFathimaM** [Suchitra-Sahoo/AgriLearnNetwork#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Adding styles and hovering effect to the Give feedback , back to top and chat icon.. Their color looks odd from the page..

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/153417476/47e6b265-4224-4528-987b-02e17e9aeb95)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DrishtiRai777** [comment]
I would like to contribute to this aspect of the project. Please assign this issue to me under GSSOC 2024.
Thank you,
Drishti Rai

**Comment by Suchitra-Sahoo** [comment]
This is not required
