### ISSUE TITLE
BUG: Adding header and footer to other pages

### ISSUE THREAD

**Issue by Sneha123-zudo** [Suchitra-Sahoo/AgriLearnNetwork#669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I want to add header and footer to the website where it is not present and improve the UI/UX of the website.

Please assign this issue to me under GSSOC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned
