### ISSUE TITLE
Can add an attachment option while sending a message in "Contact Us" section.

### ISSUE THREAD

**Issue by AkshaySobti** [Suchitra-Sahoo/AgriLearnNetwork#67]
Hello @Suchitra-Sahoo,
I can add an attachment option where the visitor that wants to send a message can also attach a file (if required).

Please assign me this issue under GSSoC'24 contribution.

**Comment by pandey079** [comment]
Hi,  I want to work on this issue, can you please assign it to me

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
@AkshaySobti what's the update?
