### ISSUE TITLE
Feat: Quote of the Day feature

### ISSUE THREAD

**Issue by coderiksenthil** [Suchitra-Sahoo/AgriLearnNetwork#670]
### Describe the feature

Daily farming tips and motivational quotes are provided in a visually appealing format, promoting ongoing learning and motivation for farmers.

How It Works:
1. Retrieves farming tips and quotes from JSON data.
2. Uses JavaScript to display this content on the HTML page.
3. Offers a user-friendly experience on AgriLearnNetwork.

The quote updates daily on its own.

**Additionally, the code is already prepared and ready for implementation, I kindly request to assign me this task.**

### Add ScreenShots

Here is how it looks like

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/66522620/840ab0f6-a5af-40cc-b1d7-fa330e41e2d1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This feature is not required
