### ISSUE TITLE
Feat: Adding FAQ section.

### ISSUE THREAD

**Issue by MuraliDharan7** [Suchitra-Sahoo/AgriLearnNetwork#671]
### Describe the feature

Adding FAQ section Increase user self-service by addressing common questions and reducing support load. I can add FAQ section before to the footer.

### Add ScreenShots

NO NEED

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by DrishtiRai777** [comment]
I would like to contribute to this aspect of the project. Please assign this issue to me under GSSOC 2024.
Thank you,
Drishti Rai

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned
