### ISSUE TITLE
BUG: Navbar Adjustment while at home page

### ISSUE THREAD

**Issue by isandhyadev** [Suchitra-Sahoo/AgriLearnNetwork#672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Getting out of the page and moving toward left while scrolling 
![Screenshot (385)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/95486852/f0939eb7-9d6b-4239-ba18-21f3a80ab22e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Gunjan-Rajput** [comment]
Please assign me this issue @Suchitra-Sahoo
