### ISSUE TITLE
BUG: Button in the navbar should in the right place 

### ISSUE THREAD

**Issue by upsaurav12** [Suchitra-Sahoo/AgriLearnNetwork#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The button is not is not in its current place 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/116784047/0dcc1cd6-20f0-4aad-b1dc-6d8d4296f25e)
we can ad

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by upsaurav12** [comment]
@Suchitra-Sahoo can you pls assign me this issue for gssoc ?

**Comment by Suchitra-Sahoo** [comment]
@upsaurav12 you are asigned

**Comment by upsaurav12** [comment]
Thank you for assigning me. 
Can you pls add level tag in this issue other wise it wont considered as contribution?

**Comment by Suchitra-Sahoo** [comment]
level tag is added after your PR is merged
