### ISSUE TITLE
Clicking upon cards in AgroBlogs should redirect to the respective blog.

### ISSUE THREAD

**Issue by RanjanaShenoy** [Suchitra-Sahoo/AgriLearnNetwork#69]
Hi @Suchitra-Sahoo 

Under AgroBlogs, title of blog should be clicked to open the blog. Clicking on anywhere in the card won't open/redirect to the blog.
Can I enhance this by making the whole card clickable ? 
This will also improve user experience of website.

**Comment by RanjanaShenoy** [comment]
Please assign this issue to me. 
I am a contributor in GSSOC 2024.
I would like to contribute to this project.

**Comment by Suchitra-Sahoo** [comment]
@RanjanaShenoy assigned. You may start working on it.

**Comment by RanjanaShenoy** [comment]
Thank you @Suchitra-Sahoo.
Is there any discord channel or any other communication channel? Please add me to that. Please provide me your discord username. I would be happy to discuss with you incase of doubts.
