### ISSUE TITLE
Tabs of navbar in blog page are not at proper place

### ISSUE THREAD

**Issue by Shreesanyog** [Suchitra-Sahoo/AgriLearnNetwork#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The tabs of the navbar in the blog page are not at proper place which make the page look bad. I will put them at right place.

<img width="836" alt="image" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/166977453/29a31550-6dc7-4222-8bd8-b9a63cb555b4">

Please assign this to me under gssoc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@Shreesanyog you are assigned

**Comment by puneet426** [comment]
@Suchitra-Sahoo please assign this project to me
