### ISSUE TITLE
BUG: Header is overlapping content in blogpage.html

### ISSUE THREAD

**Issue by nagalakshmi08** [Suchitra-Sahoo/AgriLearnNetwork#695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The header height is more on small devices and it is overlapping the blogs in blogpage.html

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/121669832/7b0f9bfa-f2ad-463d-ac78-d1572115ef3e)

Please assign me this issue, I would like to contribute to this project under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@nagalakshmi08 you are assigned

**Comment by puneet426** [comment]
@Suchitra-Sahoo please assign this project to me
