### ISSUE TITLE
Improve Responsiveness of Hero Section and Other Sections

### ISSUE THREAD

**Issue by dhruv389** [Suchitra-Sahoo/AgriLearnNetwork#70]
Is your feature request related to a problem? Please describe.
---
**The current layout of the hero section and other sections on the website is not optimal for small devices, leading to a poor user experience.**

Describe the solution you'd like
---

**Implement responsive design techniques to make the hero section adapt gracefully to various screen sizes, ensuring readability and usability on small devices. Similarly, optimize other sections of the website to be responsive, ensuring that content is properly displayed and accessible on mobile devices.**

Describe alternatives you've considered
---

**We could consider using media queries, flexible layouts, and other responsive design principles to achieve the desired results.**

Additional context
---
**Review the current design and layout of the hero section and other sections to identify specific areas where responsiveness needs improvement. Consider testing the changes thoroughly on various devices and screen sizes to validate the improvements and address any potential issues.**

**currenty looks like :**
---

![Screenshot 2024-05-10 234139](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/117587892/b94b56cf-1ae2-4c07-80f7-682eb9eaed65)

After changes : 
---
![Screenshot 2024-05-10 234107](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/117587892/4c0e65f8-d858-41c1-b6b4-aa62a34de8f6)

----
### Please assign me this issue under GSSOC'24
**I'm fully acquainted with the project's structure, code, and flow. Confident in my familiarity and understanding.**

**Comment by Riyasharma28** [comment]
Please assign this issue to me (Riyasharma28) under GSSoC'24.
