### ISSUE TITLE
Visibility of Logo in navbar

### ISSUE THREAD

**Issue by harsh02mishra** [Suchitra-Sahoo/AgriLearnNetwork#700]
The website logo is not clearly visible due to size of the logo.

![VisibilityLogo](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144336311/4f5732a9-79c1-4e4b-a085-93909c447001)

@Suchitra-Sahoo please assign this task to me under GSSoC'24.

**Comment by Suchitra-Sahoo** [comment]
Make changes in favicon too as it is not clearly visible.

**Comment by puneet426** [comment]
hey @Suchitra-Sahoo  please assign this project to me
