### ISSUE TITLE
BUG: there is overlapping of navbar and website content

### ISSUE THREAD

**Issue by GAGGZ1** [Suchitra-Sahoo/AgriLearnNetwork#702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When the navbar overlaps with the website content, it's likely due to issues with CSS positioning, z-index, responsive design, or padding/margins. To fix it, adjust CSS properties, ensure proper positioning, manage z-index values, and check responsiveness. Use browser developer tools to identify and resolve the root cause.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/81284966/f8812e27-8cfe-451d-9b2f-5b0aeeb1b99a)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/81284966/fd0b8dcc-86f9-4d64-aa01-1c1c95f8191c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by GAGGZ1** [comment]
@Suchitra-Sahoo please assign me this issue as i know front end

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned
