### ISSUE TITLE
Feat:adding error 404 page to the site

### ISSUE THREAD

**Issue by gangwarsomya** [Suchitra-Sahoo/AgriLearnNetwork#704]
### Describe the feature

the error page is not looking good i want to change that

### Add ScreenShots

![WhatsApp Image 2024-06-04 at 11 17 02 AM](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123868724/73fbcd15-200d-4ebe-a0a5-23e72f442ad6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required
