### ISSUE TITLE
Feat: Expert_Page

### ISSUE THREAD

**Issue by tishubohra** [Suchitra-Sahoo/AgriLearnNetwork#705]
### Describe the feature

We can add a Expert page which will have a team of experts  with whom u can contact for any queries.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/97802942/89cd56cb-a525-430b-bd58-e1bae657a9bc)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/97802942/04ebabb0-154c-491e-9abb-3da3fb3b2fb4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This feature is not required.
