### ISSUE TITLE
BUG:Missing Validation/successful alert upon Login or signup

### ISSUE THREAD

**Issue by ShristiSharan** [Suchitra-Sahoo/AgriLearnNetwork#714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When users Register as new and add the email and password but no successful registered message is shown nor failure one nor any validation error is shown 

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/95679078/e83e5481-79cb-453f-8154-4cecb2ceecd9)

the moment user clicks Log in or Register the input fields gets refreshed.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/95679078/e5fc0528-2f44-4f25-b79f-fd061fc21531)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShristiSharan** [comment]
Kindly assign this to me @Suchitra-Sahoo

**Comment by puneet426** [comment]
hello @Suchitra-Sahoo please assign this project to me

**Comment by puneet426** [comment]
there are many issue to change
