### ISSUE TITLE
BUG: Navbar is not responsive

### ISSUE THREAD

**Issue by gungunjain15** [Suchitra-Sahoo/AgriLearnNetwork#717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Create navbar effective for all devices and for all the dimensions layout
For reference : - 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125124845/dc3c106d-a6be-40dd-8df9-a1d577cb88a0)
@Suchitra-Sahoo please assign this issue to me to make website more attractive by my end.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kushagrasaxena061** [comment]
@Suchitra-Sahoo  Please assign this issue to me

 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
For which screen size this is happening?

**Comment by gungunjain15** [comment]
@Suchitra-Sahoo Mainly this problem occur in blog section only around 1222px
![Uploading image.png…]()
