### ISSUE TITLE
Improvisation of the pixel quality of the images in the website

### ISSUE THREAD

**Issue by nishantharkut** [Suchitra-Sahoo/AgriLearnNetwork#72]
### **Please Assign to me Under GSSoC'24**

**Describe the bug**
The Images in the website are not good and precise that degrades the quality of the product

**Expected behavior**
The website's images should be clear and precise so that it is clearly visible

**Screenshots**
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/156298209/6f461a6c-059b-40b4-a4f4-9ab0d4e6c534)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Mozilla FireFox
 - Version : 125.0.3

**Comment by Suchitra-Sahoo** [comment]
@nishantharkut what's the update?
