### ISSUE TITLE
Feat: Creating a 404 not found page for your website 

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [Suchitra-Sahoo/AgriLearnNetwork#720]
### Describe the feature

Creating a 404 not found page for your website 

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125277258/fd7f3a83-6d05-41b6-9504-aba22785c9cd)

something like this if you want i show you more

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RamakrushnaBiswal** [comment]
@Suchitra-Sahoo mam can i work upon it

**Comment by RamakrushnaBiswal** [comment]
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/125277258/5a4bd995-f774-44e4-a948-91c3b9c5b097)

**Comment by Suchitra-Sahoo** [comment]
Go back option should be there

**Comment by RamakrushnaBiswal** [comment]
@Suchitra-Sahoo yes is there but if you don't want it i can remove

**Comment by RamakrushnaBiswal** [comment]
can i start working now upon the issue
