### ISSUE TITLE
BUG: Responsiveness of the blog Cards

### ISSUE THREAD

**Issue by nishantharkut** [Suchitra-Sahoo/AgriLearnNetwork#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current cards is only hyperlinked to the Heading H1 text and not the whole cards.
This is not user friendly, as an UI/UX designer, the users visiting your websites would want that on clicking the card, it navigates to the specified blog of that respective card
Image - 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/156298209/3736a701-12ca-4357-9da9-8c36f4c78d0e)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/156298209/0224b20c-74fd-46d4-956b-fada1cf0af1b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
