### ISSUE TITLE
BUG:Proposal to Fix Blog and Home Navbar Elements

### ISSUE THREAD

**Issue by deepak00944** [Suchitra-Sahoo/AgriLearnNetwork#732]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

While exploring your website, I noticed that the elements of the blog navbar are not correctly positioned. This can impact navigation and user experience.

I propose to fix the placement of these elements to ensure that the blog navbar is organized and user-friendly. This adjustment will enhance the overall functionality and aesthetic appeal of your website.

**Supporting Screenshots:**
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119965267/6a62bfb0-2621-4fc3-a397-e3a07f6927a8)

Also in home page the login button is little bit outside of the nav bar.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119965267/41476acd-c225-45e2-9d93-6dabdec33e8d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!

**Comment by deepak00944** [comment]
Thank you @Suchitra-Sahoo I have raised one more issue ( #862 ) if you find it helpful please assign it to me .
