### ISSUE TITLE
Feat:REVAMP THE FOOTER SECTION

### ISSUE THREAD

**Issue by AbhinaySngh** [Suchitra-Sahoo/AgriLearnNetwork#733]
### Describe the feature

Improve the font family and manage some unwanted space between the text and also add insta link, x link, facebook link .

### Add ScreenShots

![Screenshot 2024-06-06 120832](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162811933/a0013367-a606-4683-8a4b-e499466247f9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AbhinaySngh** [comment]
@Suchitra-Sahoo please assign me this issue under GSSOC'24 Label.

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned
