### ISSUE TITLE
BUG: Improving the FAQ section so that it matches the design of the complete website.

### ISSUE THREAD

**Issue by Mohitbagul** [Suchitra-Sahoo/AgriLearnNetwork#738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @Suchitra-Sahoo ,
The FAQ's mentioned on the FAQ page are not in a good design and need to have changes which are like changing its styling, font changes, color-changes, some animations etc.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126978039/2c6474a6-8bd8-436f-a5e0-3655e0784103)

Please assign me this issue under ggsoc'24.
Thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
How are you planning to improve. You can attach a refrence image acoording to which you want to design.

**Comment by Mohitbagul** [comment]
Yes @Suchitra-Sahoo ,

I want the width of those questions to increase and make its answer to increase by "+" and decrease by "-" (as in the reference images).
I will also change its color to green.

Please suggest if you have any suggestions.

![Screenshot (400)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126978039/952b0f05-02b1-4d34-acb6-0c232c2ad06c)
![Screenshot (399)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126978039/e08c84a3-b565-470e-a4a1-a33f7c4806b5)
![Screenshot (398)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126978039/46e053be-192d-422e-89ea-93288b37bcbe)

**Comment by Suchitra-Sahoo** [comment]
remove the white space form left and right side of faq page too
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123376847/14f7eaf5-4365-4507-bfd2-c5c8116ef586)
