### ISSUE TITLE
The Color theme of the website

### ISSUE THREAD

**Issue by nishantharkut** [Suchitra-Sahoo/AgriLearnNetwork#74]
### Describe the feature

The current theme of the website is not user friendly as it direclty strikes the user's eye.
As an experienced UI/UX Designer, it would be great that i make some changes in the **GREEN** shades of the theme

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/156298209/d344657c-27a0-4ac6-b197-1eb2ec228600)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shilpajha29** [comment]
@HimanshuNarware kindly assign this task to me

**Comment by Monika3002** [comment]
Hello ,

I hope you are doing well. I am eager to contribute to the project and would appreciate it if you could assign me a task or let me know how I can get started. I am looking forward to collaborating with all of you!

Best regards,
Monika

**Comment by shendgeshraddha** [comment]
I am a contributor of Gssoc'24 I wanna work on this issue!!

**Comment by Suruchibharti** [comment]
I'm GSSoc'24 contributor,
I want to work on this issue,
kindly assign the task to me.
