### ISSUE TITLE
Feat: Add transition to login page background

### ISSUE THREAD

**Issue by thepratham05** [Suchitra-Sahoo/AgriLearnNetwork#740]
### Describe the feature

Will add transition to login page background

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/135994674/1760fa99-b1d0-4408-8c1f-3c591dd82901)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
can you explain what exactly you want to do?

**Comment by thepratham05** [comment]
> can you explain what exactly you want to do?

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/135994674/962c0309-d589-40aa-824a-876c2fcdabb5

this is the change i would like to suggest!
