### ISSUE TITLE
no validation in register and login pages

### ISSUE THREAD

**Issue by Srujitha-Raghava** [Suchitra-Sahoo/AgriLearnNetwork#741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot 2024-06-06 220816](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143430142/016d1f93-500a-43fd-9902-bee0916f1664)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned
