### ISSUE TITLE
The Space between the cards and the Heading text is not sufficient

### ISSUE THREAD

**Issue by nishantharkut** [Suchitra-Sahoo/AgriLearnNetwork#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When an user navigates to the bottom of the website, the text space between the heading and the cards under the resource library.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pandeyji711** [comment]
Hello @Suchitra-Sahoo,
I've noticed an issue with the website that I believe I can fix. 
Could you please assign this issue to me for contribution under GSSoC'24?
