### ISSUE TITLE
BUG: Uncaught TypeError: IntersectionObserver.observe: Argument 1 is not an object.

### ISSUE THREAD

**Issue by patelkiran185** [Suchitra-Sahoo/AgriLearnNetwork#752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The error message "Uncaught TypeError: IntersectionObserver.observe: Argument 1 is not an object" typically occurs when the argument passed to the observe method of the IntersectionObserver is not a valid DOM element or is not an object that the IntersectionObserver can observe.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by patelkiran185** [comment]
@Suchitra-Sahoo can you assign me this?

**Comment by Suchitra-Sahoo** [comment]
issue is resolved
