### ISSUE TITLE
Feat:carousel for blogs

### ISSUE THREAD

**Issue by P-lavanya16** [Suchitra-Sahoo/AgriLearnNetwork#754]
### Describe the feature

adding a carousels it makes blogs good

### Add ScreenShots

adding bootstrap feature

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by P-lavanya16** [comment]
@Suchitra-Sahoo Please kindly assign this to me!!

**Comment by Suchitra-Sahoo** [comment]
This is not required.
