### ISSUE TITLE
BUG:In FAQ's Scrollbar not have green background color as Home page.

### ISSUE THREAD

**Issue by zalabhavy** [Suchitra-Sahoo/AgriLearnNetwork#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/844c44d9-045c-450f-b7ed-80f906f22bf8)

There is no background color in FAQ's page i will add background color and make it like home page's Scrollbar.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is resolved
