### ISSUE TITLE
BUG: text in contact form not visible 

### ISSUE THREAD

**Issue by dhairyagothi** [Suchitra-Sahoo/AgriLearnNetwork#758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

text of contact form not visible after fiilling it 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142989448/3e6aeb6d-26a8-411e-9f03-fe6d78791f10)

@Suchitra-Sahoo please assign this issue too me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hello @Suchitra-Sahoo,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer

**Comment by Suchitra-Sahoo** [comment]
contact form is now updated.
