### ISSUE TITLE
Feat: Improving Footer UI

### ISSUE THREAD

**Issue by nagalakshmi08** [Suchitra-Sahoo/AgriLearnNetwork#76]
### Describe the feature

Hi @Suchitra-Sahoo , the footer is looking so empty because of much empty space between logos and the arrow. So adding a website title/logo in between would make it a complete footer. 

### Add ScreenShots

![Screenshot 2024-05-11 011404](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/121669832/1a9596fa-80b3-41fc-ab44-1b2342122cf6)

I would like to add the feature and improve the footer interface. I ensure that I will make it responsive on all devices. Kindly assign me this task I want to contribute to this project under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Damini2004** [comment]
Kindly assign this issue to me i can add theme change section in footer and back to main menu button as well as social media handle that can contribute in seeking more number of attention of people

**Comment by Sailza** [comment]
Please assign this task to me under GSSOC'24

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!
