### ISSUE TITLE
Feat: Add 'forgot password' page

### ISSUE THREAD

**Issue by RanjanaShenoy** [Suchitra-Sahoo/AgriLearnNetwork#764]
### Describe the feature

Upon clicking the 'forgot password' link, no redirection is happening to any of page. I would like to add 'forgot password' page by contributing to this feature. 

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/63968799/3fd19b4f-e56e-425e-9f63-69d9fe1599b1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RanjanaShenoy** [comment]
Hi @Suchitra-Sahoo, 
I am interested to contribute to this feature. Please assign this to me. 
I am a GSSOC'24 contributor.

**Comment by Suchitra-Sahoo** [comment]
The working of forgot password should be on same login page.

**Comment by Soujanya2004** [comment]
Hello @Suchitra-Sahoo 
I would like to add forgot password page to the login page which redirects to another page where users can retrieve their password. Please assign me the issue.
![Screenshot (113)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/157210374/3f3ab94a-057c-4a67-b07c-7b6bcd520784)
