### ISSUE TITLE
BUG: Upon clicking 'AgriLearnNetwork' logo, no redirection to website's home page. 

### ISSUE THREAD

**Issue by RanjanaShenoy** [Suchitra-Sahoo/AgriLearnNetwork#765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I clicked on  'AgriLearnNetwork' logo to redirect to Website's homepage, I found that redirection is not happening. Clicking on logo leads to nowhere. Logo is not clickable. 

Hence, I would like to resolve this bug by making sufficient changes like:- upon clicking logo, user should be on homepage of website. (Generally observed in all websites)

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/63968799/72421a61-b43f-4390-a767-036c7d82fa3d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RanjanaShenoy** [comment]
Hi @Suchitra-Sahoo ,
I would like to resolve this bug. Hence, improve the UX of AgriLearnNetwork. Please assign this issue to me.

I am a GSSOC'24 contributor. I would like to work on this issue.

**Comment by Suchitra-Sahoo** [comment]
This is not required
