### ISSUE TITLE
🐞 BUG: "404 page not found" Navigation error in FAQ Page "Footer" Section

### ISSUE THREAD

**Issue by MastanSayyad** [Suchitra-Sahoo/AgriLearnNetwork#767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/101971980/88f699ab-d8d7-4192-9632-0499f1fd725e

hey @Suchitra-Sahoo as you can see in above video, the navigations in footer section of FAQ page are not working properly and giving 404 page not found error

could you please assign this issue to me? under GSSoC 24, thank you.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!
