### ISSUE TITLE
BUG: The dates of all the blogs in blog page is same.

### ISSUE THREAD

**Issue by Taniishaaa** [Suchitra-Sahoo/AgriLearnNetwork#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The dates of all the blogs in blog page is same. All the blogs say that they have been published at the same date that is april 19th, 11 mins ago. We can change the dates according to original dates or different dates for all blogs without "11 mins ago" wtitten on it.
![Screenshot 2024-06-08 152822](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/155306736/d3435082-e4c9-4eb5-8856-f08a74f8ba47)
  

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Taniishaaa** [comment]
please assign this issue to me under gssoc'24 labels @Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned
