### ISSUE TITLE
BUG: Navigation issue. I want to contribute under GSSOC' 24.

### ISSUE THREAD

**Issue by ParnaRoyChowdhury777** [Suchitra-Sahoo/AgriLearnNetwork#772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when I am in the blog Page if i click on the resource library link in the navbar, it is directing me to the home section in the home page rather than the resource library section. I want to fix this.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
But i have just checked and it is redirecting to respective sections
