### ISSUE TITLE
BUG:  TypeError

### ISSUE THREAD

**Issue by patelkiran185** [Suchitra-Sahoo/AgriLearnNetwork#776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Error in script.js
Uncaught TypeError: IntersectionObserver.observe: Argument 1 is not an object.

![Screenshot from 2024-06-08 21-18-38](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/138752385/5899d6f3-e894-44d2-8520-834ece47c7f0)
I would like to fix this. Please assign me this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned
