### ISSUE TITLE
Feat: Add Github in social links

### ISSUE THREAD

**Issue by pani2004** [Suchitra-Sahoo/AgriLearnNetwork#777]
### Describe the feature

I can add Github icon in the footer section

### Add ScreenShots

![Screenshot (56)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/154724111/8a534d6a-5023-4ab6-a6df-ab198e5e2318)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pani2004** [comment]
@Suchitra-Sahoo can I work on this?

**Comment by Suchitra-Sahoo** [comment]
Github linnk is not required
