### ISSUE TITLE
Feat: for home gardening enthusiasts

### ISSUE THREAD

**Issue by kairveeehh** [Suchitra-Sahoo/AgriLearnNetwork#78]
### Describe the feature

add a separate tips/learning page for people who practice home gardening and lack resources like the agriculture ones ( like me) so that they can know tipes bout pruining , fertlisers available at home , ant attack solution , root filling etc ( which I have faced too ) and learn more 

### Add ScreenShots

It will be a complete feature page with categories as well 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kairveeehh** [comment]
@Suchitra-Sahoo  I am working on these issues as well , but as they are complete features it's taking a bit time I hope you understand .
thankyou

**Comment by kairveeehh** [comment]
@Suchitra-Sahoo  I wanted to know whether this feature needs to be integrated in the whole flow of the website or it will be a button directing to a new html file ? as currently for preparing purposes I have used a new html file so should I work to add in the hoem site , if yes below which section?

**Comment by kairveeehh** [comment]
> @Suchitra-Sahoo I wanted to know whether this feature needs to be integrated in the whole flow of the website or it will be a button directing to a new html file ? as currently for preparing purposes I have used a new html file so should I work to add in the hoem site , if yes below which section?

@Suchitra-Sahoo  please let me know so I can work acoordingly

**Comment by Suchitra-Sahoo** [comment]
I'll suggest you to go for whole workflow of website because i have seen some people tried to make separate pages but those are not working.

**Comment by kairveeehh** [comment]
> I'll suggest you to go for whole workflow of website because i have seen some people tried to make separate pages but those are not working.

ok sure i will add it below the blogs section

**Comment by kairveeehh** [comment]
should I take some inspo from here ? https://openfarm.cc/ 

@Suchitra-Sahoo

**Comment by Suchitra-Sahoo** [comment]
Sure
