### ISSUE TITLE
BUG:Image size in blogs page is not fixed 

### ISSUE THREAD

**Issue by laxmanp090404** [Suchitra-Sahoo/AgriLearnNetwork#785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While I was exploring the blogs page I noticed that the image of the blog card component is not fixed and there are no line clamps in the card.Also the UI of the card could be developed.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Explain how will you improve? You can attach a refrence image to show your idea.
