### ISSUE TITLE
BUG:Login Button in blog and faq page 

### ISSUE THREAD

**Issue by parikhitritgithub** [Suchitra-Sahoo/AgriLearnNetwork#786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In blog page login button come to center here we to adjust the login button in right position . please assign this issue to me under GSSOC 2024 .
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/124444610/7bda105b-2017-463b-a6b9-884c0427e5ef)
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/124444610/bd30c616-f007-436f-9cb0-d752cc31c18c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123376847/9249fcf1-413c-460f-9b26-a19474a1f78c)
Resolve this problem of login option going out of navbar in hamburger menu option.  For larger screen size it is looking fine on my side
![Uploading Screenshot 2024-06-09 113824.png…]()

**Comment by Suchitra-Sahoo** [comment]
Resolve this issue of login option going out of navbar in hambergur menu option
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123376847/48836980-9310-4997-9ced-78115b96dbff)
For larger screen navbar is looking fine
![Screenshot 2024-06-09 113824](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123376847/82d69cbb-2ed8-4046-8acd-bc53d8e17752)
