### ISSUE TITLE
In this Project we can add theme changing mechanism

### ISSUE THREAD

**Issue by Damini2004** [Suchitra-Sahoo/AgriLearnNetwork#79]
### Describe the feature

The project is used by various type of people who generally don't like always same theme.
This website can fully change in theme its animations,font,styles,etc
Kindly assigned this issue to me.

### Add ScreenShots

![Screenshot 2024-05-11 021300](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119414762/2d1c79ed-0163-4953-9700-73f805abba93)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
I feel this feature is not required as someone is already working on making dark mode.
