### ISSUE TITLE
Fixing navbar in mobile view 

### ISSUE THREAD

**Issue by dhairyagothi** [Suchitra-Sahoo/AgriLearnNetwork#799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_2024_0610_123206](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142989448/9a86c1b6-bf49-4437-af69-5597487bd62a)

I would like to fix the navbar in mobile view

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by PAPIYA-DUTTA** [comment]
I want to make it responsive in mobile view.

**Comment by dhairyagothi** [comment]
Please merge the PR @Suchitra-Sahoo
