### ISSUE TITLE
Improve the design of the website

### ISSUE THREAD

**Issue by Suchitra-Sahoo** [Suchitra-Sahoo/AgriLearnNetwork#8]
Improve the current visualization with more eye-catching details and improvements. Feel free to experiment with more visualizations.

**Comment by Mohit5Upadhyay** [comment]
I want to work and contribute under GSSoC'24 . Please assign the task of improving the UI design  it became more interactive and engaging. Please assign it to me .

**Comment by rishyym0927** [comment]
Hi @Suchitra-Sahoo 

I'm interested in working on the task to "Improve the design of the website." With my experience in web design and a keen eye for aesthetics, I'm confident I can enhance the visual appeal and user experience of the website.

Looking forward to your approval.

**Comment by vaishnavip27** [comment]
Hey @Suchitra-Sahoo I would love to work on the enchancement of this website. Looking forward for your approval

**Comment by TechSenseiX** [comment]
Hii , With my background in front end and web design, I believe I'm well-equipped to tackle this issue effectively. I've also taken the time to thoroughly understand the problem and have some ideas on how to approach it. 
Can you please assign this task to me ?

**Comment by Suchitra-Sahoo** [comment]
> Hey @Suchitra-Sahoo I would love to work on the enchancement of this website. Looking forward for your approval

@vaishnavip27 assigned. You may start working on it.

**Comment by AshAk0** [comment]
I would like to contribute on the design

**Comment by AshAk0** [comment]
I would love to work in the design and responsiveness to multiple devices @Suchitra-Sahoo

**Comment by urgetolearn** [comment]
Hey, @Suchitra-Sahoo Can I collaborate with others who have already been assigned to work on this issue? I would really love to enhance the design of the website.

**Comment by debasmi** [comment]
kindly assign me this issue

**Comment by Suchitra-Sahoo** [comment]
@vaishnavip27 update me about your progress.
