### ISSUE TITLE
Feat:The nav bar hyperlink that i clicked in the navbar remains active even after scrolling down that section & contact hyperlink in navbar

### ISSUE THREAD

**Issue by K-kiran77** [Suchitra-Sahoo/AgriLearnNetwork#80]
### Describe the feature

We can improve the user experience by changing the behavior of the navbar hyper links

The feature is when scrolling if mouse on any of the section that hyperlink in the navbar whose attribute is located to this section becomes active and when the mouse is not on that section it doesn't become active from this feature the user can and also add contact hyperlink in navbar to direct to the contact section when clicked on it

kindly, assign me this to solve the issue and also to add contact navlink in the navbar

### Add ScreenShots

![Screenshot 2024-05-11 065439](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/132844726/4668ce10-be75-4064-bf7f-78cabb039248)
In the attached screenshot you can see that i clicked on about hyperlink in the navbar but even after i scrolled to the resource library section that about hyperlink is still active 

we can solve this issue when a hyperlink is clicked that hyperlink is active until and unless scrolled to another section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saketh1714** [comment]
Hello @Suchitra-Sahoo , I am interested in doing this can you please assign this issue to me.

**Comment by Dark-S8uL** [comment]
@Suchitra-Sahoo I'd like to contribute to this project by changing the behaviour of the hyperlinks in the navbar section . This will results in enhancing the interactivity and improving the overall visuals of the hyperlinks. Assigning this task to me would be fantastic.
