### ISSUE TITLE
BUG:Email Validation missing in feedback form

### ISSUE THREAD

**Issue by swetha5157** [Suchitra-Sahoo/AgriLearnNetwork#800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### **Description:**
In the feedback form, the email validation is missing. 
Here is the **input typed** in the fields given.
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123291594/17b577ba-c340-45dc-90c5-c975fff99540)
**But the output is** 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/123291594/b791aef6-b637-4bad-9f49-2e00f5bfca72)

### **Desired outcome:**
With the necessary code changes, the email validation would work well.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned

**Comment by swetha5157** [comment]
Yes @Suchitra-Sahoo but it is assigned for login and sigup page 
not for feedback form page..
Kindly look into it and assign the issue to me @swetha5157

**Comment by swetha5157** [comment]
Kindly assign this issue since for feedback page form the email validation issue is not fixed yet..
