### ISSUE TITLE
Feat:Implementing Multilingual support

### ISSUE THREAD

**Issue by Damini2004** [Suchitra-Sahoo/AgriLearnNetwork#801]
### Describe the feature

I'll make sure users can view the website in their preferred language by adding a language selection option in the navbar. Users will be able to choose from available languages for a smoother browsing experience. As previously done in my last project, I used the Google translation widget to translate content on the website into multiple languages.
The below image is my last project where I made it available in different languages.

Implementing multilingual support in a project can significantly enhance its usability, accessibility, and reach. Here are several ways this feature could enhance the use of the project and the benefits it would bring to the project or community:

Increased Accessibility:
User Inclusivity: By supporting multiple languages, the project becomes accessible to a wider audience who may not be proficient in the primary language. This inclusivity ensures that users from different linguistic backgrounds can use and benefit from the project.
Improved Usability: Users can interact with the project in their native language, which improves their overall experience and satisfaction. This is particularly important for complex projects where understanding the content is crucial for effective use.
Global Reach:
Market Expansion: Multilingual support allows the project to be marketed and used globally. It opens up opportunities in regions and countries where the primary language is not spoken.
Diverse User Base: Attracting a diverse user base can provide richer feedback and insights, helping to improve the project based on varied user experiences and needs.
Enhanced Communication:
Better Support: Providing documentation, help files, and customer support in multiple languages can significantly improve the support experience for non-native speakers.
Community Engagement: Users are more likely to engage with the project and contribute to its community if they can communicate and collaborate in their preferred language.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119414762/d7fc4642-83ce-4244-9b53-7a62a4d8f432)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
No image is visible

**Comment by Damini2004** [comment]
@Suchitra-Sahoo Kindly review it

**Comment by Damini2004** [comment]
@Suchitra-Sahoo Assign this to me.
