### ISSUE TITLE
Feat:Adding search bar in the website

### ISSUE THREAD

**Issue by Vedanshimishra** [Suchitra-Sahoo/AgriLearnNetwork#803]
### Describe the feature

I want to add a search bar in the website which will help user to search for the topics he wants to.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143635091/5476414c-07cf-4765-9509-adea339bd5ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It is not required
