### ISSUE TITLE
Add dynamic year code in footer

### ISSUE THREAD

**Issue by arpit4521** [Suchitra-Sahoo/AgriLearnNetwork#809]
![Screenshot 2024-06-11 213643](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/127679958/446218bc-fcdd-4ee0-ac35-01aa65f621ca)

@Suchitra-Sahoo please assign me this issue under gssoc and apt level label

**Comment by Suchitra-Sahoo** [comment]
This is not required right now.
