### ISSUE TITLE
Feat: Attractive Font Style & Contact Form UI

### ISSUE THREAD

**Issue by Che140401** [Suchitra-Sahoo/AgriLearnNetwork#81]
### Describe the feature

Hi Suchitra-Sahoo,

Just wanted to share the latest updates on the project. I've revamped the font styles to make them more attractive and readable. Also, I've redesigned the contact form UI for better user experience. With 1.4 years of front-end development experience, I'm eager to hear your thoughts and feedback on these enhancements.

![contact-form-UI](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109230049/1a722e11-b554-4e44-a2aa-eab775084299)

### Add ScreenShots

**Bad UI Contact Form**
![contact-form-UI](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109230049/b60e3136-135f-4a26-a2d1-46c4efbae42d)

**Inconsistent Font**
![Inconsistent-font](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109230049/c3d54bae-1794-4a9e-81a0-91fe5dffca84)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ShrestyTyagi** [comment]
Describe:
The contact form in the website is the simple one. I would add the features to enhance this form and even change the font style. Contact form will also include invalid number/ email feature. I will try my best to make this contact form more look good.

I request you to kindly assign this issue to me. @Suchitra-Sahoo

**Comment by Che140401** [comment]
**Here we gooooooooooooooo**

- Made web page font style standard
 
![Screenshot 2024-05-11 152750](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109230049/6df52914-f635-45d5-a657-19d4b381c17b)

- Well designed contact form
![Screenshot 2024-05-11 153004](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109230049/21f7ea8e-29af-4881-bd69-0369b12192b2)

- Responsive form
 
![Screenshot 2024-05-11 153148](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109230049/145825d1-10e5-412c-886f-88dcae87dd3f)

- Alert form
 
![Screenshot 2024-05-11 153322](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109230049/110087e6-fc9f-4903-8ec8-e12b27af5bb6)
