### ISSUE TITLE
Bookmark button for blogs

### ISSUE THREAD

**Issue by paulkrishanu4** [Suchitra-Sahoo/AgriLearnNetwork#812]
### Describe the feature

want to add bookmark button to the blogs to save them is a favourite list, favourite list will be in a separate page.

### Add ScreenShots

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/169196836/4c338ee8-3065-4b07-bc52-6b1737d2a8d6

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by laxmi09-walker** [comment]
Hi, Please assign me this issue.
Thanks!
