### ISSUE TITLE
BUG:the footer is scrollable by moving down to the page 

### ISSUE THREAD

**Issue by DiwareNamrata23** [Suchitra-Sahoo/AgriLearnNetwork#813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1440" alt="Screenshot 2024-06-11 at 11 20 16 PM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/142529986/2ba801fd-0583-4273-9fc6-33f87a9dccec">
after the end of the page after the footer the page should not get scrolled

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hello @Suchitra-Sahoo,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer

**Comment by Suchitra-Sahoo** [comment]
I have just checked but this issue is no there.
