### ISSUE TITLE
Animation for navbar elements

### ISSUE THREAD

**Issue by Premkolte** [Suchitra-Sahoo/AgriLearnNetwork#814]
### Describe the feature

adding some basic animation to navbar icons

### Add ScreenShots

Hover effect

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!

**Comment by Premkolte** [comment]
I will do a PR by the end of the day
