### ISSUE TITLE
Feat: Add sign up with Google/ login with google option in popup

### ISSUE THREAD

**Issue by sau-mili** [Suchitra-Sahoo/AgriLearnNetwork#816]
### Describe the feature

This will be a new button with google logo 

### Add ScreenShots

![Screenshot 2024-06-12 002950](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/146661411/fa3b7aaf-12b3-4fcb-9052-e9d49fcebea7)
add something similar but will match the theme of rest of the website: color and transparencyetc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SohaFarhana** [comment]
I would like to work on this issue , can u assign me as a GSSOC'24 contributor

**Comment by Suchitra-Sahoo** [comment]
It is already assigned.
