### ISSUE TITLE
DOC:All files are scattered 

### ISSUE THREAD

**Issue by kanishk-2** [Suchitra-Sahoo/AgriLearnNetwork#818]
### What's wrong with the existing documentation

All files are scattered for html, css,js. Will be arranging all files properly like all html, css,js files in their respective folders.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Actually it was showing 404 error when the files are within folders.

**Comment by kanishk-2** [comment]
All files?

**Comment by kanishk-2** [comment]
Even if I keep files inside a folder except the index.html file still it shows error?

**Comment by Suchitra-Sahoo** [comment]
Okay you may try if it works then its good.

**Comment by kanishk-2** [comment]
Ok but which level tag will be added if it works 1 or 2?
