### ISSUE TITLE
Changes in Home section

### ISSUE THREAD

**Issue by Prateek2111** [Suchitra-Sahoo/AgriLearnNetwork#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

first of all, make a home section responsive and change the image in home section. try to add vector images or attractive images.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Prateek2111** [comment]
Could you please assign me to participate in this project?

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Suchitra-Sahoo

**Comment by Sailza** [comment]
Please assign this task to me under GSSOC'24
