### ISSUE TITLE
Feat: Google auth feature.

### ISSUE THREAD

**Issue by mukilan2815** [Suchitra-Sahoo/AgriLearnNetwork#827]
### Describe the feature

Implementing auth feature using google onclick signup. google provides one click signup for easy signup for users. 

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/71129858/18befe48-8a05-4d10-837e-d5c8968a2c87)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is already assigned.
