### ISSUE TITLE
Enchancing Contact Us Page

### ISSUE THREAD

**Issue by tempestanya** [Suchitra-Sahoo/AgriLearnNetwork#829]
I propose revamping the website's Contact Us page for improved aesthetics and usability. The current design lacks appeal, hindering user engagement. By enhancing its visual elements and user interface, we can create a more welcoming and effective platform for visitor interaction.

**Comment by Pavitra2128** [comment]
I propose revamping the website's Contact Us page for improved aesthetics and usability. The current design lacks appeal, hindering user engagement. By enhancing its visual elements and user interface, we can create a more welcoming and effective platform for visitor interaction.

**Comment by tempestanya** [comment]
Thanks for assigning the task! I'll start working on it right away and keep you updated on my progress.

**Comment by tempestanya** [comment]
Hi Suchitra,
I have made changes in the Contact Us section of the website.

**Before:** 
![Contact Us  - Before](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/98050185/b1266774-be39-40bd-9ad1-067f342ea269)

**After: **
1. Inputs have a subtle gradient background, smooth box shadows, and rounded corners for a sleek, 3D effect.
2. Focus and hover states include slight scaling, a glow effect, and border color changes, with smooth transitions for a polished experience.
3.  Inputs are consistently sized and well-spaced for clean form alignment.

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/98050185/517bd5c6-84ef-48d8-ae0e-01507311daf2

Please give your feedback.

**Comment by tempestanya** [comment]
@Suchitra-Sahoo please give your feedback on the contact us page.

**Comment by Suchitra-Sahoo** [comment]
Please update your branch and then add your changes.
