### ISSUE TITLE
Feat: Adding Hover effect to CONTACT US

### ISSUE THREAD

**Issue by madhurima316** [Suchitra-Sahoo/AgriLearnNetwork#83]
### Describe the feature

the CONTACT US section buttons need hover effect

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/145414858/eda0c894-9fb1-44a5-9dd1-d035fb7025a6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by madhurima316** [comment]
Please assign me this issue under GSSoC24

**Comment by sahiltambe18** [comment]
Can you please label the issue and assign me

**Comment by Ramu-chiluveru** [comment]
As a Gssoc'24 contributor i want to work on this issue. so, i kindly request you to assign this to me
@Suchitra-Sahoo

**Comment by Nih1tGupta** [comment]
I would like to work on this project. please assign it to me

**Comment by Rish-tech1** [comment]
I would like to work on this issue. Pls assign me this!!

**Comment by Sailza** [comment]
Please assign this task to me under GSSOC 24

**Comment by alamzia23** [comment]
Can u Please assign this task to me ? I had some similar task in my personal project.

**Comment by Anshika2608** [comment]
Please assign this task to me .I'm GSSOC'24 contributor.I want to work on this issue
