### ISSUE TITLE
 Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by rohitinu6** [Suchitra-Sahoo/AgriLearnNetwork#831]
### Describe the feature

I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

This feature will enhance user engagement by providing visible visitor statistics and can be a useful metric for site administrators to track traffic.

### Add ScreenShots

Preview of proposed Website Visitor widget:

![Screenshot 2024-06-12 143634](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/113301503/3b0c7b47-b649-42c8-825d-6c1695cc3872)

**Please assign this issue to me under the gssoc label**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!

**Comment by Suchitra-Sahoo** [comment]
This is not required
