### ISSUE TITLE
Responsive site

### ISSUE THREAD

**Issue by Vibha17** [Suchitra-Sahoo/AgriLearnNetwork#836]
### Describe the feature

I would like to make site more responsive and improve ui

I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/152614708/835156d7-f479-41f8-8748-67c3eb477b66)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
readme section is fine no need to make changes.
