### ISSUE TITLE
Update CONTRIBUTION.md

### ISSUE THREAD

**Issue by 1754riya** [Suchitra-Sahoo/AgriLearnNetwork#838]
### Is there an existing issue for this?
 I have searched the existing issues

### Feature Description
I want to include the following in your contribution MD:

1.  Code Reviews
2. Feature Requests
3. Spread the Word
4. Community Guidelines

### Priority
High

### Record
 I have read the Contributing Guidelines
 I'm a GSSOC'24 contributor
 I have starred the repository

# Suchitra Sahoo, Please assign me this issue.

**Comment by Suchitra-Sahoo** [comment]
This is not required right now.
