### ISSUE TITLE
DOC:Improving index.html

### ISSUE THREAD

**Issue by kanishk-2** [Suchitra-Sahoo/AgriLearnNetwork#839]
### What's wrong with the existing documentation

Adding comments for better understanding in index.html as there are very less comments in index.html file.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SheetalDawar** [comment]
i would like to work on this project, please assign this to me

**Comment by Suchitra-Sahoo** [comment]
This is not required.
