### ISSUE TITLE
The glassy welcome div making the Text very dull and blury 

### ISSUE THREAD

**Issue by SumithThota** [Suchitra-Sahoo/AgriLearnNetwork#842]
### Describe the feature

The glassy welcome div making the Text very dull and blury so let me make it blur free so that clients can have a better view

### Add ScreenShots

check out this screen shot
![Screenshot 2024-06-13 164759](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/108344062/b47d16e0-7b76-42ae-95ac-a9f0c710787f)

Let me fix it as a gssoc24 contributor

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
How are you planning to improve it?

**Comment by SumithThota** [comment]
Let me remove the blur effect to the text and apply shadow  effect to the highlighted text
