### ISSUE TITLE
BUG: The login/Register button is overlapping with the scroll bar and the elements in the navbar are very small

### ISSUE THREAD

**Issue by SumithThota** [Suchitra-Sahoo/AgriLearnNetwork#843]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

BUG: The login/Register button is overlapping with the scroll bar and the elements in the navbar are very small
let me enlarge them and make login button free from overlapping
Let me solve this issue as a GSSOC24 contributor.

ScreenShots:

![Screenshot 2024-06-13 165549](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/108344062/fc7955c1-24c6-4750-b96d-2c4611ddee79)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!

**Comment by Suchitra-Sahoo** [comment]
It is already assigned.
