### ISSUE TITLE
Feat: Add Youtube icon to the website at the footer section 

### ISSUE THREAD

**Issue by GAVINESHWAR** [Suchitra-Sahoo/AgriLearnNetwork#844]
### Describe the feature

In the website there is no youtube icon in the footer section , all other social media icons are there if youtube iss also added then it would be better for promotion as well.

Assign me this issue @Suchitra-Sahoo to make contribution to the project.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/124431955/c76b0186-6f5e-479b-9345-c422a946b3ae)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!

**Comment by Suchitra-Sahoo** [comment]
This is not required
