### ISSUE TITLE
BUG: fixing nav bar in blog page

### ISSUE THREAD

**Issue by Hemav009** [Suchitra-Sahoo/AgriLearnNetwork#847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/b8b8afed-d78b-4a59-a21a-02b580abcf0d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It is already assigned
