### ISSUE TITLE
beeter look for faq section

### ISSUE THREAD

**Issue by Hemav009** [Suchitra-Sahoo/AgriLearnNetwork#848]
### Describe the feature

highlight each question when hovering over it and the color  gradient  on the faq box 

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/109607812/cb1e4532-83f9-4865-a3f2-3f8b948af669)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SheetalDawar** [comment]
i would like to work on this project, please assign this to me

**Comment by sakeel-103** [comment]
@Suchitra-Sahoo 
can please assign me this task, here I want to add some new feature in this section.

**Comment by sakeel-103** [comment]
@Suchitra-Sahoo 
Please assign me this under gssoc'24
