### ISSUE TITLE
BUG:Add Form Validation and enhance form filling experience.

### ISSUE THREAD

**Issue by Pratik2401** [Suchitra-Sahoo/AgriLearnNetwork#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1.Add Validation to email 
2.remove arrows from mobile number field
3.add a popup after successfully send meassage.
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/105542579/e929f4a1-34eb-498c-86b2-9ec16d581df8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by thunders123** [comment]
I would like to work on this project . please assign it to me.
