### ISSUE TITLE
Feat: Automatic Comment on Pull Request Raised

### ISSUE THREAD

**Issue by thevijayshankersharma** [Suchitra-Sahoo/AgriLearnNetwork#850]
### Describe the feature

Often, when pull requests (PRs) are raised, reviewers may lack crucial context about the changes proposed. This can lead to delays in the review process and misunderstandings between contributors and reviewers.

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by piyushsahujtp** [comment]
I would love the opportunity to contribute and work on this project.

Could you please assign the issue to me? I’m eager to dive in and make a meaningful impact. Thank you for considering my request!

**Comment by Suchitra-Sahoo** [comment]
This is not required right now
