### ISSUE TITLE
Feat:Add "Website Visitor" Widget in Footer

### ISSUE THREAD

**Issue by deepak00944** [Suchitra-Sahoo/AgriLearnNetwork#864]
### Describe the feature

The current website does not display the number of visitors it has received, which could be useful for tracking engagement and performance metrics.

I would like to add a "Website Visitor" widget in the footer of the website that shows the number of visitors so far. This widget will update in real-time or upon page refresh to provide an accurate count of the total visitors.

This feature will enhance user engagement by providing visible visitor statistics and can be a useful metric for site administrators to track traffic.

### Add ScreenShots

Preview of feature:

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/119965267/b0183a21-41f7-4dde-b57d-cf52b79f8064)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
this is not required
