### ISSUE TITLE
Feat: adding favicon icon 

### ISSUE THREAD

**Issue by solanki505** [Suchitra-Sahoo/AgriLearnNetwork#87]
### Describe the feature

I would like to add favicon icon please assign this to me under GSSOC'24

### Add ScreenShots

![Screenshot 2024-05-11 104449](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/158484284/97fd41c3-8e4b-4a13-bb8c-9013e368c4d9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
@solanki505 assigned. You may start working on it.

**Comment by ShrestyTyagi** [comment]
Describe:
There is no favicon in the website. Favicon enhances the users experience.

I would like to work on this issue.
I request you to kindly assign this issue to me @Suchitra-Sahoo

**Comment by solanki505** [comment]
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/pull/134#issue-2290960285
I already solved it

**Comment by solanki505** [comment]
Feat: adding favicon icon #87
![Screenshot 2024-05-12 103532](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/158484284/bcf7ffc2-49a0-43de-931c-927ed0c65568)
 is it better now??
@Suchitra-Sahoo
