### ISSUE TITLE
Feat:Theme image

### ISSUE THREAD

**Issue by soniya-malviy** [Suchitra-Sahoo/AgriLearnNetwork#873]
### Describe the feature

Image in FQA's section is so different from theme of website.This image needs to change.

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-06-16 at 11 47 25 PM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/151515611/7c7797f0-347e-45ee-afd0-579cda6c55ad">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
Explain about how will you improve?

**Comment by soniya-malviy** [comment]
Adding theme image means image which relates to website have a look the website is about farming which takes to green colour but image is totally different so i will design a image which relates to theme.
