### ISSUE TITLE
Feat: Integrating weather conditions

### ISSUE THREAD

**Issue by aswini-14** [Suchitra-Sahoo/AgriLearnNetwork#88]
### Describe the feature

I felt like it would be better if we include the weather conditions that will be updated daily since it will be very much helpful for farmers.

### Add ScreenShots

![farmingweather](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/127423807/75758d71-fea4-456f-90af-9abc94a695a0)
the above screenshot is just taken as a reference from online.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sailza** [comment]
please assign this task to me under GSSOC 2024 as contributor . I already worked on weather application system so i am able to do this

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
