### ISSUE TITLE
BUG: Blog page not have quick link hover effects like home page.

### ISSUE THREAD

**Issue by zalabhavy** [Suchitra-Sahoo/AgriLearnNetwork#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Home page have quick link hove effects like 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/06dd9fc0-637b-443d-87f8-997c1805308c)
In Blog page not have hover effects it have default effects like
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/f908cfbe-9fd7-4134-8ff0-b70cd9941de5)

I will add same hover effects in blogs quick links like home.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Suchitra-Sahoo Please assign me !

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.
