### ISSUE TITLE
Feat: Improving UI of feedback page

### ISSUE THREAD

**Issue by techinaina** [Suchitra-Sahoo/AgriLearnNetwork#893]
### Describe the feature

the feedback page is very simple and is also very different from the theme which is making it less attractive. I can enhance the UI of feedback form to make it look attractive and contrast it with the theme provided

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143960485/11c75af2-6837-4911-9916-443a4a0b431e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by aslams2020** [comment]
@Suchitra-Sahoo Please assign me this issue. As the collaborator has not done yet
