### ISSUE TITLE
Feat: Removing the underline effect from footer 

### ISSUE THREAD

**Issue by Amruta7203** [Suchitra-Sahoo/AgriLearnNetwork#896]
### Describe the feature

Removing the underline effect from footer and improving the hover effect

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/116087736/565f2b61-73d0-4145-89c8-4bdc51aa3050)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
It has already been resolved
