### ISSUE TITLE
Feat: Adding phone number validation in contact form 

### ISSUE THREAD

**Issue by Amruta7203** [Suchitra-Sahoo/AgriLearnNetwork#897]
### Describe the feature

Adding phone number validation in contact form 

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/116087736/e90175af-8c46-43b7-8f5a-1a1f559af663)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by JaiBansal007** [comment]
I Want to Work on this project @Suchitra-Sahoo Could you Please Assign this task to me under GSSoC'24?
