### ISSUE TITLE
Feat: want to add an important blog of terrace farming  in blog section .

### ISSUE THREAD

**Issue by ANKeshri** [Suchitra-Sahoo/AgriLearnNetwork#911]
### Describe the feature

we know terrace farming is an important metthod of farming and I wanted to add terrace farming blog in blog page .

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159682348/3b7dc1c3-2557-4480-966d-5028c630db7a)
 wanted to add a complete blog page of terrace farming .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ANKeshri** [comment]
@Suchitra-Sahoo please assign this issue to me under gssoc label .

**Comment by Suchitra-Sahoo** [comment]
Currently it is not required.
