### ISSUE TITLE
Adding pagination in Blogs section

### ISSUE THREAD

**Issue by driyash9881** [Suchitra-Sahoo/AgriLearnNetwork#912]
### Describe the feature

# Adding Pagination to the Blog Section
## Problem Description

The current blog section displays all posts on a single page, leading to a cluttered and overwhelming user experience as the number of posts increases. This can make it difficult for users to navigate through content and find specific posts. To improve usability and organization, we need to implement pagination, which will divide the blog posts into manageable pages.

## Solution Approach

To add pagination to the blog section

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/118407844/0aa3c841-3ce8-4c33-8aac-f85136b3ab6f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required.
