### ISSUE TITLE
Feat: To add feedback review section inside the feedback

### ISSUE THREAD

**Issue by sakeel-103** [Suchitra-Sahoo/AgriLearnNetwork#914]
### Describe the feature

Inside the feedback section, having a feedback review option would look good.

@Suchitra-Sahoo 
So please assign this to me under gssoc'24.

### Add ScreenShots

SS- 
![p22](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/136844498/7d754e86-776e-4568-871b-6e077e831fd3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required

**Comment by Suchitra-Sahoo** [comment]
I think it is not much helpful.
