### ISSUE TITLE
Feat: Adding Google Translate feature

### ISSUE THREAD

**Issue by MuraliDharan7** [Suchitra-Sahoo/AgriLearnNetwork#918]
### Describe the feature

I want to add google translate feature in this website. This will help the users to understand the content in their own language.

### Add ScreenShots

![GoogleTranslate](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/130668745/99a4b15e-bb6f-4215-9242-508d8a3a7c19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned.
