### ISSUE TITLE
BUG: Add Forget password page

### ISSUE THREAD

**Issue by MuraliDharan7** [Suchitra-Sahoo/AgriLearnNetwork#919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When I click the forget password text. It takes me again to the same page. This should not be done. There should be separate page for forget password. 

I want to add the same.

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/130668745/a9083229-fc10-4935-9dc8-01e857cc3df1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned.
