### ISSUE TITLE
BUG: Resource library card's don't fit 

### ISSUE THREAD

**Issue by dhruv8433** [Suchitra-Sahoo/AgriLearnNetwork#920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@Suchitra-Sahoo 

check this out,

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/114583978/10621c71-426a-4149-8117-171229efad7d)

the card's image not fit properly

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
on my side it seems fine.
