### ISSUE TITLE
Feat:Auto Commenting when an issue is closed by maintainer

### ISSUE THREAD

**Issue by Maana-Ajmera** [Suchitra-Sahoo/AgriLearnNetwork#924]
### Describe the feature

 By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts.

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162733812/0352485f-252b-4fe8-b57c-9e46772e0961)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This feature is not required right now.
