### ISSUE TITLE
Section of form overlapping with nav bar in login page

### ISSUE THREAD

**Issue by suhanigupta23** [Suchitra-Sahoo/AgriLearnNetwork#926]
### What's wrong with the existing documentation

Section of form overlapping with nav bar in login page.

### Add ScreenShots
<img width="1060" alt="Screenshot 2024-06-20 at 8 27 39 PM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144280247/f02bf060-040e-4a19-b988-306c2946e799">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Yashika2511** [comment]
I want to work on this issue
