### ISSUE TITLE
Feat:  Redesign the Logo

### ISSUE THREAD

**Issue by sanskritisahu21** [Suchitra-Sahoo/AgriLearnNetwork#936]
### Describe the feature

Redesign of the current logo.

### Add ScreenShots

The current logo is not visible clearly in the website.

![Screenshot 2024-06-22 112437](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/134837879/83fcef1e-e7b2-4bd6-946a-3c0bf3966c70)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sanskritisahu21** [comment]
@Suchitra-Sahoo Please assign me this issue under gssoc

**Comment by Suchitra-Sahoo** [comment]
Design a logo which looks clear in favicon as well

**Comment by sanskritisahu21** [comment]
Ok @Suchitra-Sahoo 
And thankyou for assigning me this issue
