### ISSUE TITLE
Feat: Login with google 

### ISSUE THREAD

**Issue by roushanverma23** [Suchitra-Sahoo/AgriLearnNetwork#940]
### Describe the feature

Login / signup with google functionality is not working

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/137530796/7b93dd4e-60cc-4302-99c4-8ad3bbd607a2)

@Suchitra-Sahoo please assign this issue , I want to work on this

### Add ScreenShots

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/137530796/2b4af9ee-805a-4ccf-8c36-87c014756e03

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RahulNaha** [comment]
@Suchitra-Sahoo willing to work on it please assign it to me
