### ISSUE TITLE
BUG: move to top and chat button hover color does not align with give feedback hover Color

### ISSUE THREAD

**Issue by Ayushi3023** [Suchitra-Sahoo/AgriLearnNetwork#943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/116361036/ef7e184d-2755-4974-8770-a8f7812eb1f2)
the color of buttons do not change on hovering as it changes in the feedback button

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required
