### ISSUE TITLE
quiz feature

### ISSUE THREAD

**Issue by Shivani756** [Suchitra-Sahoo/AgriLearnNetwork#946]
### Describe the feature

we can introduce a quizz feature that wiuld enable user to get more knowledge about the farming sector 
it would be a fun feature for users to test and gain some knowledge 

### Add ScreenShots

![Screenshot_2024-06-23-02-02-45-628_com google android googlequicksearchbox](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/139329176/d495d7ab-dc2a-4750-a712-cee99ad64a1a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This is not required.
