### ISSUE TITLE
Feat: Addition Of Google Translator in The footer

### ISSUE THREAD

**Issue by HishitaGupta** [Suchitra-Sahoo/AgriLearnNetwork#949]
### Describe the feature

Addition Of Google Translator in The footer to make the website multilingual and more accessible.

### Add ScreenShots

![Screenshot 2024-06-21 115052](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/159264060/f470cf63-345d-425e-b41c-9c8e18ca106c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meenakshiiyer2531** [comment]
Hello @Suchitra-Sahoo,
Can this issue be assigned to me for Gssoc'24. 
Regards,
V Meenakshi Iyer

**Comment by Suchitra-Sahoo** [comment]
this is not required
