### ISSUE TITLE
Feat: Improving the Navbar / Adding  a 404 Page

### ISSUE THREAD

**Issue by Poushik11** [Suchitra-Sahoo/AgriLearnNetwork#95]
### Describe the feature

Hello I want to improve the styling of Navbar also 
I want to add a 404 Not found page will help for invalid url

### Add ScreenShots

will add the ss 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Poushik11** [comment]
Please consider this issue and I request you to assign me to this. I am a participant of GSSOC'24 and I request you to also assign level label for contribution.

**Comment by Sailza** [comment]
Please assign this task to me under GSSOC'24

**Comment by Suchitra-Sahoo** [comment]
This issue is already assigned.

**Comment by Poushik11** [comment]
@Suchitra-Sahoo is not found page assigned too?
