### ISSUE TITLE
Feat: Loading contact us form on button click on user action and fixing the footer for the website.

### ISSUE THREAD

**Issue by Khushalsarode** [Suchitra-Sahoo/AgriLearnNetwork#958]
### Describe the feature

will load the form contact us when user click button in section dynamically!
making footer content align and better adjustments!

### Add ScreenShots

![Screenshot 2024-06-23 205318](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/105520366/93ba1553-687a-4bee-821b-e1ba052bd2c6)
![Screenshot 2024-06-23 205333](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/105520366/8fc68061-b61f-4cd9-82b1-cf49be97c685)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khushalsarode** [comment]
@Suchitra-Sahoo can i work on this?

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned.
