### ISSUE TITLE
BUG: Toggle button and login buttons are overlapping in the navbar of the homepage.

### ISSUE THREAD

**Issue by meetarora10** [Suchitra-Sahoo/AgriLearnNetwork#968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an overlapping of the login/register button and toggle button on the homepage's navbar.
Assign this task to me and I can create a proper navbar without any kind of overlapping.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by meetarora10** [comment]
@Suchitra-Sahoo I was talking about this overlapping of login and toggle buttons and this is present in desktop view also.
![Screenshot (501)](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/143121854/fde5c0ff-3691-469f-80de-17352019b1bc)

**Comment by Suchitra-Sahoo** [comment]
This issue is resolved.
