### ISSUE TITLE
DOC: Not properly aligned the content and updated photos are not add

### ISSUE THREAD

**Issue by nisargaa20** [Suchitra-Sahoo/AgriLearnNetwork#97]
### What's wrong with the existing documentation

Not properly aligned the content and updated photos are not add in the readme

Please assign me under #gssoc24 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Sailza** [comment]
Please assign this task to me under GSSOC'24

**Comment by Suchitra-Sahoo** [comment]
It will be updated after the program ends.
