### ISSUE TITLE
Feature:Navigating to Home page when AgriLearnNetwork logo is clicked

### ISSUE THREAD

**Issue by SumithThota** [Suchitra-Sahoo/AgriLearnNetwork#973]
### Describe the feature

Hello @Suchitra-Sahoo,
I want to add a new feature to AgrilearnNetwork Project i.e:
If a client/user clicks on the Logo of our project then it should able to navigate to Home Page of the Project. 

## This is a sample one check it
https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/108344062/9d49d363-d83b-4f60-93bc-00a806f16161

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This  is not required.
