### ISSUE TITLE
BUG:Improper Positon of Login button in blogs page

### ISSUE THREAD

**Issue by SumithThota** [Suchitra-Sahoo/AgriLearnNetwork#975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

## Login button is not properly aligned in blogs page

You can check that over here:

![Screenshot 2024-06-24 164751](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/108344062/754ecb56-243c-4706-b2f2-f046ba6b99e4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
I just checked but this issue is not there in website.

**Comment by SumithThota** [comment]
when your screen width is in between 1216px to 1320px this is happpening
