### ISSUE TITLE
BUG: In buy products page scrollbar is not like home page there is no green background color in products page scrollbar.

### ISSUE THREAD

**Issue by zalabhavy** [Suchitra-Sahoo/AgriLearnNetwork#976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/f2d8a155-ca9b-4dca-b413-7ca08e9286b1)

I will fix it and make this like home page's scrollbar.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Suchitra-Sahoo Please assign me this task !

**Comment by Suchitra-Sahoo** [comment]
scrollbar is working fine. Green background is not required.
