### ISSUE TITLE
Feat :Adding a Field visit section in the navbar

### ISSUE THREAD

**Issue by sahithinandikula** [Suchitra-Sahoo/AgriLearnNetwork#979]
### Describe the feature

Field visits allow farmers to witness best practices, engage with experts, and gain real-world insights. hence field visit section can be added to the navbar in which a form will be displayed asking for a field visit[farm visit] to help farmers resolve their issues and get tips from experts. This feature will be a game-changer as it creates a close interaction between agricultural experts and enthusiasts with the farmers. , a

### Add ScreenShots

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/138794574/231a43d9-3292-48da-bb57-33e04874c211)

this is just an example the actual form will not look the same as shown in the figure.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
This feature is not required.
