### ISSUE TITLE
BUG: Improving the login page as the icons are not working to sign in

### ISSUE THREAD

**Issue by meenakshiiyer2531** [Suchitra-Sahoo/AgriLearnNetwork#980]
### What happened?

In the login page the google, github and linkedin login is not working. Even there could be more login like on for apple users. Even the logo for google login is not correct

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/74537549/3e0bfdb0-b57a-47e6-8bef-d28490f5ba0a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
ISSUE is already assigned.
