### ISSUE TITLE
BUG:in checkout nothing to happen

### ISSUE THREAD

**Issue by Varsani2520** [Suchitra-Sahoo/AgriLearnNetwork#982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

when i click on checkout button for payment then nothing to show 
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/137641079/32ebb469-530c-42ff-8a98-4743281004a9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
@Suchitra-Sahoo ,please assign me

**Comment by Varsani2520** [comment]
@Suchitra-Sahoo ,also add the level label

**Comment by Suchitra-Sahoo** [comment]
level label is added when you resolve the issue and your PR is merged.

**Comment by Varsani2520** [comment]
ok

**Comment by vaishnavi-jais** [comment]
I’m eager to step in and troubleshoot this issue, ensuring the checkout process is as smooth and responsive as it should be. Could you please assign me this task for GSoC '24? I’m ready to make sure the checkout button takes center stage and delivers a seamless payment experience!

Thanks a lot for considering my request!
