### ISSUE TITLE
Correcting the nav bar of the webpages for overlapping issue

### ISSUE THREAD

**Issue by suhanigupta23** [Suchitra-Sahoo/AgriLearnNetwork#986]
### What's wrong with the existing documentation

Correcting the position of the nav bars link as somewhere they are overlapping or not proper in small screen. 

### Add ScreenShots

<img width="1240" alt="Screenshot 2024-06-25 at 12 50 29 PM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144280247/0651c131-940f-4924-b17d-b7646c8b48e0">
<img width="1240" alt="Screenshot 2024-06-25 at 12 50 38 PM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144280247/bd8b2c2f-9585-463d-81f0-e154aff68eb3">
<img width="1240" alt="Screenshot 2024-06-25 at 12 51 09 PM" src="https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/144280247/3f9aede5-250b-403b-baec-8030b519059f">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned
