### ISSUE TITLE
BUG: When submit feedback message of thank you and please fill all details not visible.

### ISSUE THREAD

**Issue by zalabhavy** [Suchitra-Sahoo/AgriLearnNetwork#987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/126322584/70ad6312-bc0d-4225-8513-6281a7d54e54)

Messages is present but there is some bug so that message not visible.
I will fix that.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@Suchitra-Sahoo Please assign me this task !

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned
