### ISSUE TITLE
Feat: FAQ section QnA hower effect

### ISSUE THREAD

**Issue by Yashaswale** [Suchitra-Sahoo/AgriLearnNetwork#992]
### Describe the feature

Issue : when we hover on the answers of the FAQ the background images as well as the answers zooms in 
Updates:
-Adding a smooth hover effect 
-Making the background image stable
-Alternative image for the FAQ image

### Add ScreenShots

https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/117583791/2cf2fc1b-c6c3-4d39-bdec-d4f08c8ef37e

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by amanp18** [comment]
hi, Can you assign me these under gssoc.
