### ISSUE TITLE
BUG: Alignment of items in the navbar

### ISSUE THREAD

**Issue by Ajita369** [Suchitra-Sahoo/AgriLearnNetwork#997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The logo is sticking to  'home' and the register button on hover is intersecting with light/dark theme button. I can fix this alignment.
Screenshot:
![image](https://github.com/Suchitra-Sahoo/AgriLearnNetwork/assets/162597493/414079d1-2ffc-423d-9ebf-382480f60f89)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Suchitra-Sahoo** [comment]
issue is already assigned.
